/*
********************************************************************************
*
* Copyright (C) 2003 Polycom Israel Ltd.
* This file contains confidential information proprietary to POLYCOM ISRAEL Ltd.
* The use or disclosure of any information contained In this file without the
* written consent of an officer of POLYCOM ISRAEL Ltd is expressly forbidden.
*
********************************************************************************

*****************************************************************************

 General Description:

 Generated By: Nir Brachel      Date: 7/12/2005

*****************************************************************************/

#ifndef __AUD_INDICATION_STRUCTURES_H
#define __AUD_INDICATION_STRUCTURES_H

/***** Include Files *****/

/***** Constants *****/

/***** Macros *****/

/***** Type Definition *****/
typedef struct
{
	APIS32	enDtmfEvent;	// EDtmfSymbol ename
} TAudioDtmfEventInd;


typedef struct
{
	APIS32	bnNoiseInd;
} TAudioNoiseDetInd;


/***** Public Global Variables *****/

/***** Public Functions Prototypes *****/








#endif


