/*
********************************************************************************
*
* Copyright (C) 2003 Polycom Israel Ltd.
* This file contains confidential information proprietary to POLYCOM ISRAEL Ltd.
* The use or disclosure of any information contained In this file without the
* written consent of an officer of POLYCOM ISRAEL Ltd is expressly forbidden.
*
********************************************************************************

*****************************************************************************

 General Description:

 Generated By: Nir Brachel      Date: 8/15/2005

*****************************************************************************/

#ifndef __HOST_COMMON_DEFINITIONS_H
#define __HOST_COMMON_DEFINITIONS_H

/***** Include Files *****/

/***** Constants *****/

/***** Macros *****/
#define DUMMY_PORT_ID			(0xFFFFFFFF)
#define DUMMY_PARTY_ID			(0xFFFFFFFF)
#define DUMMY_CONF_ID			(0xFFFFFFFF)
#define DUMMY_CONNECTION_ID		(0xFFFFFFFF)
#define DUMMY_ROOM_ID		    (0xFFFF)

#define STANDALONE_CONF_ID 		(0xBEBEBEBE)
#define DUMMY_UDP_PORT_ID		(0xFDFD)

#define CONF_PARTY_CONNECTION_ID    	(0x000003FD)
#define MCCF_CONNECTION_ID    		(0x000003FE)
#define LOBBY_CONNECTION_ID    		(0x000003FF)

/***** Type Definition *****/

/***** Public Global Variables *****/

/***** Public Functions Prototypes *****/








#endif


