#ifndef SELFCONSISTENCYDEFINES_H_
#define SELFCONSISTENCYDEFINES_H_

//ports
#define SC_NUM_OF_ART_PORTS_PER_PARTY					1

//descriptors
#define SC_NUM_OF_ART_DESCRIPTORS_FOR_IP_PARTY			3
#define SC_NUM_OF_ART_DESCRIPTORS_FOR_ISDN_PARTY		2

#define SC_NUM_OF_NET_DESCRIPTORS_FOR_IP_PARTY			0
#define SC_NUM_OF_NET_DESCRIPTORS_FOR_PSTN_PARTY 		1
#define SC_MINIMUM_NUM_OF_NET_DESCRIPTORS_FOR_ISDN_PARTY 1

#endif /*SELFCONSISTENCYDEFINES_H_*/
