/*
*****************************************************************************
*
* Copyright (C) 2005 POLYCOM NETWORKS Ltd.
* This file contains confidential information proprietary to POLYCOM NETWORKSO
*  Ltd. The use or disclosure of any information contained
* in this file without the written consent of an officer of POLYCOM NETWORKS
* Ltd is expressly forbidden.
*
*****************************************************************************

*****************************************************************************

 Module Name: LinuxSystemCallsApi.c

 General Description:  Module "" contains:

      1. 

 Generated By:	Yigal Mizrahi       Date: 26.4.2005

*****************************************************************************/
#ifndef _TDD_H_
#define _TDD_H_

/***** Include Files *****/
#include "DiagDataTypes.h"

/***** Public Variables *****/

/***** Global Variables *****/

/***** Public Functions Declarations *****/
extern void TestStart();
extern void TestEnd();
/***** Private Functions Declarations *****/
#endif //_TDD_H_
