/*
********************************************************************************
*
* Copyright (C) 2006 Polycom NSD Ltd.
* This file contains confidential information proprietary to POLYCOM NSD Ltd.
* The use or disclosure of any information contained In this file without the
* written consent of an officer of POLYCOM ISRAEL Ltd is expressly forbidden.
*
********************************************************************************

********************************************************************************

 General Description:

 Generated By: 	      Date: 

********************************************************************************/

#ifndef __RECORDING_REQUEST_STRUCTS_H
#define __RECORDING_REQUEST_STRUCTS_H

 
#define MAX_RECORDING_FILE_NAME_LENGTH			  128 /* value must be modulo 4! */
#define MAX_RECORDING_FULL_PATH_NAME              128 /* value must be modulo 4! */


typedef struct
{
	APIS8      ucPathName[MAX_RECORDING_FULL_PATH_NAME];
	
}   TStartupDebugRecordingParamReq;


typedef struct
{
		APIU32		unJunction;
        
        APIU32		unRate;
        
		APIU32		unStreamId;
		
        APIU32		unMaxRecFileLen; //0xFFFFFFFF if no limit
  	
		APIS8		ucFileName[MAX_RECORDING_FILE_NAME_LENGTH]; 
		
		APIU32      unApplicationType;
         
}   TDebugRecordingJunctionParams;

typedef struct  
{
	PHYSICAL_RESOURCE_INFO_S             physicalPort;
	
	TDebugRecordingJunctionParams		 tDebugRecordingJunction;

}TStartDebugRecordingReq;
  

#endif // __RECORDING_REQUEST_STRUCTS_H



