/*
********************************************************************************
*
* Copyright (C) 2006 Polycom NSD Ltd.
* This file contains confidential information proprietary to POLYCOM NSD Ltd.
* The use or disclosure of any information contained In this file without the
* written consent of an officer of POLYCOM ISRAEL Ltd is expressly forbidden.
*
********************************************************************************

********************************************************************************

 General Description:

 Generated By: 	      Date: 

********************************************************************************/
 

#ifndef __RECORDING_HOST_API_DEFINITIONS_H
#define __RECORDING_HOST_API_DEFINITIONS_H


typedef enum 
{
	E_RECORDING_JUNCTION_DUMMY = 0,

	E_RECORDING_JUNCTION_LAST
} ERecordingJunction;


typedef enum 
{
	E_RECORDING_JUNCTION_RATE_DUMMY = 0,

	E_RECORDING_JUNCTION_RATE_LAST
} ERecordingJunctionRate;

typedef enum 
{
	E_APPLICATION_TYPE_DUMMY = 0,

	E_APPLICATION_TYPE_LAST
} EApplicationType;


#endif // __RECORDING_HOST_API_DEFINITIONS_H



