/*
********************************************************************************
*
* Copyright (C) 2006 Polycom NSD Ltd.
* This file contains confidential information proprietary to POLYCOM NSD Ltd.
* The use or disclosure of any information contained In this file without the
* written consent of an officer of POLYCOM ISRAEL Ltd is expressly forbidden.
*
********************************************************************************

********************************************************************************

 General Description:

 Generated By: 	      Date: 

********************************************************************************/
#ifndef OPCODESMCMSCARDMNGRRECORDING_H
#define OPCODESMCMSCARDMNGRRECORDING_H

// =======================================
// =========== RSRCALLOC range ===========
// =======================================

//#define RESOURCE_CARDMNGR_RECORDING_FIRST_OPCODE	9040000
#define STARTUP_DEBUG_RECORDING_PARAM_REQ			9040010
#define START_DEBUG_RECORDING_REQ					9040011
#define STOP_ALL_DEBUG_RECORDING_REQ				9040012
//#define RESOURCE_CARDMNGR_RECORDING _LAST_OPCODE	9049999


#endif // __OPCODES_MCMS_CARD_MNGR_RECORDING_H



