


// =======================================
// =========== ConfParty range ===========
// =======================================

//#define CONF_PARTY_MRC_FIRST_OPCODE					1110000

#define CONF_PARTY_MRMP_OPEN_CHANNEL_REQ  		1110001
#define CONF_PARTY_MRMP_UPDATE_CHANNEL_REQ 		1110002
#define CONF_PARTY_MRMP_CLOSE_CHANNEL_REQ 		1110003

#define CONF_PARTY_MRMP_VIDEO_SOURCES_REQ 		1110004

#define CONF_PARTY_MRMP_SCP_STREAM_REQ_IND 		1110005
#define CONF_PARTY_MRMP_SCP_STREAM_ACK_REQ 		1110006

#define CONF_PARTY_MRMP_SCP_STREAM_NOTIFICATION_REQ 	1110007
#define CONF_PARTY_MRMP_SCP_STREAM_NOTIFICATION_ACK_IND 1110008

// SCP Notification - EP->Bridge
#define CONF_PARTY_MRMP_SCP_STREAM_NOTIFICATION_IND    	1110009
#define CONF_PARTY_MRMP_SCP_STREAM_NOTIFICATION_ACK_REQ 1110010

// FIR
#define CONF_PARTY_MRMP_RTCP_FIR_IND                 	1110011
#define CONF_PARTY_MRMP_RTCP_FIR_REQ                 	1110012

// More SCP notifications - Bridge->EP
#define CONF_PARTY_MRMP_SCP_IVR_STATE_NOTIFICATION_REQ			1110013
#define CONF_PARTY_MRMP_SCP_PIPES_MAPPING_NOTIFICATION_REQ   	1110014

// Party Monitoring
#define CONF_PARTY_MRMP_PARTY_MONITORING_REQ			1110015
#define CONF_PARTY_MRMP_PARTY_MONITORING_IND			1110016

//Temporary stream pause requests eliminator:
#define CONF_PARTY_MRMP_STREAM_IS_MUST_REQ              1110017


//#define CONF_PARTY_MRC_LAST_OPCODE   				1110999
