/*
*****************************************************************************
*
* Copyright (C) 2005 POLYCOM NETWORKS Ltd.
* This file contains confidential information proprietary to POLYCOM NETWORKSO
*  Ltd. The use or disclosure of any information contained
* in this file without the written consent of an officer of POLYCOM NETWORKS
* Ltd is expressly forbidden.
*
*****************************************************************************

*****************************************************************************

 Module Name: tdd.c

 General Description:  Module "" contains:

      1. 

 Generated By:	Yigal Mizrahi       Date: 26.4.2005

*****************************************************************************/

/***** Include Files *****/
#include <stdio.h>
#include "tdd.h"
#include "Print.h"



/***** Public Variables *****/

/***** Global Variables *****/
INT32 nPassTests = 0 , nFailTests = 0;
/***** Public Functions Declarations *****/

/***** Private Functions Declarations *****/

/***** Functions Code *****/






void TestStart()
{
	nPassTests = 0;
	nFailTests = 0;
}


void AddSuccess()
{
	nPassTests++;
	printf(">");
}

void AddFailure(UINT8 *pucTestName,UINT8 *pucMsg , INT32 uLine , UINT8 *pucFile)
{
	nFailTests++;
	printf("\n%s : %s : %s:%d\n",pucTestName,pucMsg,pucFile,uLine);
}

void AssertImplementation(UINT8 *pucTestName , UINT8 *pucMsg , INT32 uExpected , INT32 uActual , INT32 uLine , UINT8 *pucFile)
{
	INT8 aucBuffer[50];
	nFailTests++;
	
	snprintf(aucBuffer, sizeof(aucBuffer), "%s : exp %d was %d : %s",pucMsg,uExpected,uActual,pucTestName);
}



void TestEnd()
{
	printf("\nTotal Tests - %d Fail , %d Pass\n",nFailTests,nPassTests);
}


void TestAdd()
{
}

void TestAdd2()
{
}

void TestAddVectors()
{
}

void TestAddVectors2()
{
}
