/********************************************************************************
*
* Copyright (C) 2003 Polycom Israel Ltd.
* This file contains confidential information proprietary to POLYCOM ISRAEL Ltd.
* The use or disclosure of any information contained In this file without the
* written consent of an officer of POLYCOM ISRAEL Ltd is expressly forbidden.
*
********************************************************************************

*****************************************************************************

 General Description: File contains the definitions of the RTP requests structures

 Generated By: Eyal Leviav      Date: 7/25/2005

*****************************************************************************/

#ifndef __CM_IP_INDICATION_STRUCTS_H
#define __CM_IP_INDICATION_STRUCTS_H

/***** Include Files *****/
#include "DataTypes.h"
#include "IpChannelParams.h"
#include "IpPartyMonitorDefinitions.h"
#include "SrtpStructsAndDefinitions.h"

/***** Constants *****/
#define CNAME_STRING_MAX_LEN (255) //this number is derived from the RTCP standard. its the maximal length allowed for CNAME

/***** Macros *****/

/***** Type Definition *****/


////////////////////////////////////
//CM party monitoring
//IP_CM_PARTY_MONITORING_IND
//CONF_PARTY_MRMP_PARTY_MONITORING_IND
////////////////////////////////////
typedef struct {
	APIU32							unNumOfChannels;
	APIU32							ulTipChannelPartyID; //marks the TIP channel PartyID for which this indication is for
	APIS8							acMonitoringData[MaxChannelsPerCall * sizeof(TRtpChannelMonitoringInd)]; // sizeof(TRtpChannelMonitoringInd) is already aligned to 32.
	APIUBOOL  						bIsWebRtc;
} TCmPartyMonitoringInd;

////////////////////////////////////
//CM party statisitcs
//IP_CM_PARTY_VIDEO_CHANNELS_STATISTICS_IND
//MaxVideoDirectedChannelsPerCall is 2 :1 for video out and second for video content out
////////////////////////////////////
typedef struct {
	APIU32							unNumOfChannels;
	APIU32							ulTipChannelPartyID; //marks the TIP channel PartyID for which this indication is for
	APIS8							acMonitoringData[MaxVideoDirectedChannelsPerCall * sizeof(TRtpChannelMonitoringInd)]; // sizeof(TRtpChannelMonitoringInd) is already aligned to 32.
	APIUBOOL  						bIsWebRtc;
} TCmPartyInfoStatisticsInd;

////////////////////////////////////
//CM party packet loss
// IP_CM_PARTY_PACKET_LOSS_IND
////////////////////////////////////
typedef struct 
{
	APIU32		media_type;
	APIU32		media_direction;
} TCmPartyPacketLossInd;


////////////////////////////////////
//CM ITP SDES CNAME name indication. this is used when we identify a SDES packet
//    with a CNAME field that begins with Polycom (NOTEthe capital 'P')
// CM_SEND_CNAME_INFO_AS_STRING_IND
////////////////////////////////////
typedef struct
{
	//this is the string to hold the cname. as agreed with MCMS, the cname MUST be NULL terminated!!!
	APIS8 cCname[CNAME_STRING_MAX_LEN];
} TCmRtcpCnameInfoAsStringInd;

// IP_CM_DTLS_END_IND
typedef struct{

	APIU32		status;				// status 0 - OK, 1 Violate.
	APIU32		channelType;		// kChanneltype
	APIU32		channelDirection;	// cmCapDirection.

	sdesCapSt	sdesCap;			// remote sdes caps

} mcIndCmDtlsEnd;

//IP_CM_MEDIA_DISCONNECTED_IND
typedef struct{
	APIU32 		unChannelType; //kChanneltype, only detect on audio,video
	APIU32 		bIsRTP; //0: RTCP, 1: RTP
}TMediaDisconnectedIndStruct;

#endif /*__CM_IP_INDICATION_STRUCTS_H*/
