/********************************************************************************
*
* Copyright (C) 2003 Polycom Israel Ltd.
* This file contains confidential information proprietary to POLYCOM ISRAEL Ltd.
* The use or disclosure of any information contained In this file without the
* written consent of an officer of POLYCOM ISRAEL Ltd is expressly forbidden.
*
********************************************************************************

*****************************************************************************

 General Description: File contains the definitions of the RTP requests structures

 Generated By: Eyal Leviav      Date: 7/25/2005

*****************************************************************************/

//+========================================================================+
//                       H323MfaReq.h	                                   |
//            Copyright 1995 Polycom Ltd.					               |
//                   All Rights Reserved.                                  |
//-------------------------------------------------------------------------|
// NOTE: This software contains valuable trade secrets and proprietary     |
// information of Polycom Technologies Ltd. and is protected by law.        |
// It may not be copied or distributed in any form or medium, disclosed    |
// to third parties, reverse engineered or used in any manner without      |
// prior written authorization from Polycom Technologies Ltd.              |
//-------------------------------------------------------------------------|
// FILE:       IpWebRtcInd.h	                                               |
// SUBSYSTEM:  MFA/ConfParty                                                |
// PROGRAMMER: Amihay F.,													   |
// Date : 13/4/14														   |
//-------------------------------------------------------------------------|
// Who | Date       | Description                                          |
//-------------------------------------------------------------------------|
//     |            |                                                      |
//+========================================================================+


#ifndef __IP_CM_WEBRTCP_IND_H__
#define __IP_CM_WEBRTCP_IND_H__

/***** Include Files *****/
#include "DataTypes.h"



// IP_CM_WEBRTC_CONNECT_IND
typedef struct
{
	APIU32								status; //0 OK, 1 Violate
	APIU32								sdpSize;
	char								sdp[1];

} mcIndCmWebRtcConnectInd;



//#define IP_CM_WEBRTC_SERVER_STAT_CHANGE_IND
typedef struct
{
	APIU32 		    stun_udp_server_status;
	APIU32 		    stun_tcp_server_status;
	APIU32 		    relay_udp_server_status;
	APIU32 		    relay_tcp_server_status;


} mcIndCmWebRtcServerStatChangeInd;

#endif /*__CM_IP_INDICATION_STRUCTS_H*/
