// *********************************************************************************
// Copyright (C) 2011 Polycom Israel Ltd.
// This file contains confidential information proprietary to POLYCOM ISRAEL Ltd.
// The use or disclosure of any information contained In this file without the
// written consent of an officer of POLYCOM ISRAEL Ltd is expressly
// *********************************************************************************

// *********************************************************************************
// General Description:  File "802_1xApiDefinitions.h" 
// Generated By: inaveh      Date: 10/2012
// *********************************************************************************

#ifndef _802_1xAPI_REQ_H_
#define _802_1xAPI_REQ_H_

#include "802_1xApiDefinitions.h"

//this struct signals the Manager that a new conf is ready and
//it should get it and (re)start operating using this new conf
//the results is an IND with the status of the operation
//since we can have up to 4 NICS (NGB), we reserve place for all options.
//for each NIC we should have TRUE/FALSE so the manager can know which/how
//wpa_cli instances to run
typedef struct {
	APIU32 ulEnabled;
	UINT32 eEth0En;
	UINT32 eEth1En;
	UINT32 eEth2En;
	UINT32 eEth3En;
} s802_1x_NEW_CONFIG_REQ;


//request from MCMS to manager to query the status of a spesific NIC
//when requesting info about 802.1x, there is a seperate request per NIC -
//mimicing the model of EthHandling 
typedef struct {
	E_802_1xEth eNicId;
} s802_1x_CONNECTION_STATUS_REQ;




#endif
