// *********************************************************************************
// Copyright (C) 2011 Polycom Israel Ltd.
// This file contains confidential information proprietary to POLYCOM ISRAEL Ltd.
// The use or disclosure of any information contained In this file without the
// written consent of an officer of POLYCOM ISRAEL Ltd is expressly
// *********************************************************************************

// *********************************************************************************
// General Description:  File "802_1xApiDefinitions.h" 
// Generated By: inaveh      Date: 10/2012
// *********************************************************************************

#ifndef _802_1xAPIDEFINITIONS_H_
#define _802_1xAPIDEFINITIONS_H_

//the username can be up to 256 chars
#define P802_1x_USER_NAME_MAX_LENGTH (256)

//the passwd field can be up to 256 UNICODE (16bit) chars
#define P802_1x_PASSWD_MAX_LENGTH (256 * 2)

#define P802_1x_SSID_MAX_LENGTH (128)

//4 is the number of eth's in the NGB
#define P802_1x_MAX_ETH_NUM (4)

//this is max length for the path of the root dir of the 802.1x conf files
//its used by the managers and by the conf generator
#define P802_1x_FILES_PATH_MAX_LENGTH (512)

#define P802_1x_WPA_CONF_BOND_FILE_NAME_PREFIX "wpa_bond0"
#define P802_1x_WPA_CONF_FILE_NAME_PREFIX "wpa_eth"
#define P802_1x_WPA_CONF_FILE_NAME_SUFFIX ".conf"

#define MEDIA_CARD_CONF_FILES_PATH_1 "/mnt/mfa_cm_fs/802.1xConfFiles/media1/"
#define MEDIA_CARD_CONF_FILES_PATH_2 "/mnt/mfa_cm_fs/802.1xConfFiles/media2/"
#define MEDIA_CARD_CONF_FILES_PATH_3 "/mnt/mfa_cm_fs/802.1xConfFiles/media3/"
#define MEDIA_CARD_CONF_FILES_PATH_4 "/mnt/mfa_cm_fs/802.1xConfFiles/media4/"
#define SWITCH_CONF_FILES_PATH "/mnt/mfa_cm_fs/802.1xConfFiles/switch/"

typedef enum {
	E_802_1x_ETH0,
	E_802_1x_ETH1,
	E_802_1x_ETH2,
	E_802_1x_ETH3,
    E_802_1x_BOND0,
	E_802_1x_INVALID
} E_802_1xEth;

//these are the possible events generated by wpa_supplicant and sent
//to wpa_cli (and then passed to the application)
typedef enum {
	E_802_1x_STATE_DISCONNECTED,
	E_802_1x_STATE_CONNECTING,
	E_802_1x_STATE_CONNECTED,
	E_802_1x_STATE_BAD_CONF,
	E_802_1x_STATE_DISABLED,
	E_802_1x_STATE_INVALID
} E_802_1xConnState;


typedef enum {
	E_802_1x_METHOD_OFF,
	E_802_1x_METHOD_PEAP_MSCHAPV2,
	E_802_1x_METHOD_EAP_TLS,
	E_802_1x_METHOD_EAP_MD5,
	E_802_1x_METHOD_MAX
} E_802_1xMethod;


typedef enum {
	E_802_1x_PORT_STATUS_NOT_CONFIGURED,
	E_802_1x_PORT_STATUS_FAILED,
	E_802_1x_PORT_STATUS_AUTHENTICATED,
	E_802_1x_PORT_STATUS_INVALID
} E_802_1xSuppPortStatus;

typedef enum {
	E_802_1x_FR_OFF,
	E_802_1x_FR_LINK_STATUS_NOT_DETECTED,
	E_802_1x_FR_BAD_CONFIGURATION, //something is wrong with the conf MCMS gave us. no wpa_supplicant.conf file
	E_802_1x_FR_DTLS_ESTABLISHMENT_FAILURE, //this signals that there is something wrong with the dtls establishment process (e.g. with the cretificate)
	E_802_1x_FR_DTLS_AUTHENTICATION_FAILURE, //this signals something is wrong with username/passwd (for CHAP or with the user cert in TLS)
	E_802_1x_FR_INVALID
} E_802_1xFailureReason;


#endif //_802_1xAPIDEFINITIONS_H_
