#ifndef OPCODESLOGGER_H_
#define OPCODESLOGGER_H_

//#define LOGGER_PRIVATE_FIRST_OPCODE				3990000

#define OUT_TRACE_MESSAGE							3990001

//#define LOGGER_PRIVATE_LAST_OPCODE				3999999

#endif /*OPCODESLOGGER_H_*/
