/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.create-dataset.conf,v 5.4 2004/02/02 19:06:53 rstory Exp $
 */
#ifndef H323MCCONFIGTABLE_H
#define H323MCCONFIGTABLE_H

/*
 * function declarations 
 */

void H323Table_Init();
void H323Table_SetGK(const char* gatekeeperIP);


    
/*
 * column number definitions for table h323McConfigTable 
 */
#define COLUMN_H323MCCONFIGMCCALLSIGNALINGTAG		        1
#define COLUMN_H323MCCONFIGMCCALLSIGNALINGADDRESS	        2
#define COLUMN_H323MCCONFIGGATEKEEPERADDRESSTAG		        3
#define COLUMN_H323MCCONFIGGATEKEEPERADDRESS		        4
#define COLUMN_H323MCCONFIGISREGISTEREDWITHGATEKEEPER		5
#define COLUMN_H323MCCONFIGENABLENOTIFICATIONS		        6
#endif                          /* H323MCCONFIGTABLE_H */
