/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.create-dataset.conf,v 5.4 2004/02/02 19:06:53 rstory Exp $
 */

#include <iostream>
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

#include "h323McConfigTable.h"
#include "SnmpTableUtils.h"


netsnmp_table_row* CreateRowToH323Table(u_int index, const char * gatekeeperIP);



netsnmp_table_data_set *h323Table_table_set = NULL;


/** Initialize the h323McConfigTable table by defining its contents and how it's structured */
void H323Table_Init()
{    
    static oid      h323McConfigTable_oid[] = { 0, 0, 8, 341, 1, 1, 4, 2, 1 };
    size_t          h323McConfigTable_oid_len = OID_LENGTH(h323McConfigTable_oid);

    /*
     * create the table structure itself 
     */
    h323Table_table_set = netsnmp_create_table_data_set("h323McConfigTable");

    /*
     * comment this out or delete if you don't support creation of new rows 
     */
    h323Table_table_set->allow_creation = 1;

    /***************************************************
     * Adding indexes
     */
    DEBUGMSGTL(("H323Table_Init",
                "adding indexes to table h323McConfigTable\n"));
    netsnmp_table_set_add_indexes(h323Table_table_set, ASN_INTEGER,       /* index: ifIndex */
                                  0);

    DEBUGMSGTL(("H323Table_Init",
                "adding column types to table h323McConfigTable\n"));
    
    netsnmp_table_set_multi_add_default_row(h323Table_table_set,
                                            COLUMN_H323MCCONFIGMCCALLSIGNALINGADDRESS,
                                            ASN_OCTET_STR, 0, NULL, 0,
                                            COLUMN_H323MCCONFIGGATEKEEPERADDRESSTAG,
                                            ASN_INTEGER, 0, NULL, 0,
                                            COLUMN_H323MCCONFIGGATEKEEPERADDRESS,
                                            ASN_OCTET_STR, 0, NULL, 0,
                                            COLUMN_H323MCCONFIGISREGISTEREDWITHGATEKEEPER,
                                            ASN_INTEGER, 0, NULL, 0,
                                            COLUMN_H323MCCONFIGENABLENOTIFICATIONS,
                                            ASN_INTEGER, 0, NULL, 0, 0);

   
    netsnmp_register_table_data_set(netsnmp_create_handler_registration
                                    ("h323McConfigTable",
                                     NULL,
                                     h323McConfigTable_oid,
                                     h323McConfigTable_oid_len,
                                     HANDLER_CAN_RWRITE), h323Table_table_set, NULL);

    netsnmp_register_auto_data_table(h323Table_table_set, NULL);
}


void H323Table_SetGK (const char * gatekeeperIP)
{
    u_int index = 1;
    netsnmp_table_row *newRow = CreateRowToH323Table(index, gatekeeperIP);
    
    NetSnmpTableReplaceRowByIndex(h323Table_table_set, index, newRow, ASN_INTEGER);
}

netsnmp_table_row* CreateRowToH323Table(u_int index, const char * gatekeeperIP)
{
    u_int zero = 0;
    
    netsnmp_table_row *row = netsnmp_create_table_data_row();
    netsnmp_table_row_add_index(row, ASN_INTEGER, &index, sizeof(u_int));
    netsnmp_set_row_column(row,
                           COLUMN_H323MCCONFIGMCCALLSIGNALINGADDRESS,
                           ASN_OCTET_STR,
                           "",
                           strlen(""));
    
    netsnmp_set_row_column(row,
                           COLUMN_H323MCCONFIGGATEKEEPERADDRESSTAG,
                           ASN_INTEGER,
                           (const char*) &zero,
                           sizeof(u_int));
    
    netsnmp_set_row_column(row,
                           COLUMN_H323MCCONFIGGATEKEEPERADDRESS,
                           ASN_OCTET_STR,
                           gatekeeperIP,
                           strlen(gatekeeperIP));
    
    netsnmp_set_row_column(row,
                           COLUMN_H323MCCONFIGISREGISTEREDWITHGATEKEEPER,
                           ASN_INTEGER,
                           (const char*)&zero,
                           sizeof(u_int));
    netsnmp_set_row_column(row,
                           COLUMN_H323MCCONFIGENABLENOTIFICATIONS,
                           ASN_INTEGER,
                           (const char*)&zero,
                           sizeof(u_int));
    return row;
}
