/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.create-dataset.conf,v 5.4 2004/02/02 19:06:53 rstory Exp $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "ifTable.h"
#include "SnmpTableUtils.h"


netsnmp_table_row* CreateRowToIfTable(int IfIndex, const char *IfDescription, int IfType);




netsnmp_table_data_set *ifTable_table_set;
Netsnmp_Node_Handler ifTable_handler;
  
/** Initialize the ifTable table by defining its contents and how it's structured */
void IfTable_Init(void)
{
    static oid      ifTable_oid[] = { 1, 3, 6, 1, 2, 1, 2, 2 };
    size_t          ifTable_oid_len = OID_LENGTH(ifTable_oid);
    
    /*
     * create the table structure itself 
     */
    ifTable_table_set = netsnmp_create_table_data_set("ifTable");

    /*
     * comment this out or delete if you don't support creation of new rows 
     */
    ifTable_table_set->allow_creation = 1;

    /***************************************************
     * Adding indexes
     */
    DEBUGMSGTL(("initialize_table_ifTable",
                "adding indexes to table ifTable\n"));
    netsnmp_table_set_add_indexes(ifTable_table_set, ASN_INTEGER,       /* index: ifIndex */
                                  0);

    DEBUGMSGTL(("initialize_table_ifTable",
                "adding column types to table ifTable\n"));
    netsnmp_table_set_multi_add_default_row(ifTable_table_set ,
                                            //      COLUMN_IFINDEX, ASN_INTEGER, 0,
                                            //NULL, 0,
                                            COLUMN_IFDESCR, ASN_OCTET_STR,
                                            0, NULL, 0, COLUMN_IFTYPE,
                                            ASN_INTEGER, 0, NULL, 0,
                                            COLUMN_IFMTU, ASN_INTEGER, 0,
                                            NULL, 0, COLUMN_IFSPEED,
                                            ASN_GAUGE, 0, NULL, 0,
                                            COLUMN_IFPHYSADDRESS,
                                            ASN_OCTET_STR, 0, NULL, 0,
                                            COLUMN_IFADMINSTATUS,
                                            ASN_INTEGER, 1, NULL, 0,
                                            COLUMN_IFOPERSTATUS,
                                            ASN_INTEGER, 0, NULL, 0,
                                            COLUMN_IFLASTCHANGE,
                                            ASN_TIMETICKS, 0, NULL, 0,
                                            COLUMN_IFINOCTETS, ASN_COUNTER,
                                            0, NULL, 0,
                                            COLUMN_IFINUCASTPKTS,
                                            ASN_COUNTER, 0, NULL, 0,
                                            COLUMN_IFINNUCASTPKTS,
                                            ASN_COUNTER, 0, NULL, 0,
                                            COLUMN_IFINDISCARDS,
                                            ASN_COUNTER, 0, NULL, 0,
                                            COLUMN_IFINERRORS, ASN_COUNTER,
                                            0, NULL, 0,
                                            COLUMN_IFINUNKNOWNPROTOS,
                                            ASN_COUNTER, 0, NULL, 0,
                                            COLUMN_IFOUTOCTETS,
                                            ASN_COUNTER, 0, NULL, 0,
                                            COLUMN_IFOUTUCASTPKTS,
                                            ASN_COUNTER, 0, NULL, 0,
                                            COLUMN_IFOUTNUCASTPKTS,
                                            ASN_COUNTER, 0, NULL, 0,
                                            COLUMN_IFOUTDISCARDS,
                                            ASN_COUNTER, 0, NULL, 0,
                                            COLUMN_IFOUTERRORS,
                                            ASN_COUNTER, 0, NULL, 0,
                                            COLUMN_IFOUTQLEN, ASN_GAUGE, 0,
                                            NULL, 0, COLUMN_IFSPECIFIC,
                                            ASN_OBJECT_ID, 0, NULL, 0, 0);

    /*
     * registering the table with the master agent 
     */
    /*
     * note: if you don't need a subhandler to deal with any aspects
     * of the request, change ifTable_handler to "NULL" 
     */
    netsnmp_register_table_data_set(netsnmp_create_handler_registration("ifTable", ifTable_handler,
                                                                        ifTable_oid, ifTable_oid_len,
                                                                        HANDLER_CAN_RWRITE),
                                    ifTable_table_set, NULL);
    
/*
     * Finally, this actually allows the "add_row" token it the
     * * snmpd.conf file to add rows to this table.
     * * Example snmpd.conf line:
     * *   add_row netSnmpIETFWGTable eos "Glenn Waters" "Dale Francisco"
     */
    netsnmp_register_auto_data_table(ifTable_table_set, NULL);

    DEBUGMSGTL(("example_data_set", "Done initializing.\n"));
}

/** handles requests for the ifTable table, if anything else needs to be done */
int
ifTable_handler(netsnmp_mib_handler *handler,
                netsnmp_handler_registration *reginfo,
                netsnmp_agent_request_info *reqinfo,
                netsnmp_request_info *requests)
{
    /*
     * perform anything here that you need to do.  The requests have
     * already been processed by the master table_dataset handler, but
     * this gives you chance to act on the request in some other way
     * if need be. 
     */
    return SNMP_ERR_NOERROR;
}



void IfTable_AddRow(int IfIndex ,  const char *IfDescription, int IfType)
{ 
    netsnmp_table_row *newRow = CreateRowToIfTable(IfIndex, IfDescription, IfType);

    NetSnmpTableReplaceRowByIndex(ifTable_table_set, IfIndex, newRow, ASN_INTEGER);
}

netsnmp_table_row* CreateRowToIfTable(int IfIndex, const char *IfDescription, int IfType)
{
    netsnmp_table_row *row = netsnmp_create_table_data_row();
    netsnmp_table_row_add_index(row, ASN_INTEGER, &IfIndex,
                                sizeof(int));
    
    netsnmp_set_row_column(row,COLUMN_IFDESCR, ASN_OCTET_STR,
                           IfDescription , strlen(IfDescription));

    netsnmp_set_row_column(row,COLUMN_IFTYPE ,ASN_INTEGER,
                           (const char *)&IfType , sizeof(int));

    return row;
}

int IfTable_GetIfNum()
{
    int rowNum = GetNetSnmpTableRowNumber(ifTable_table_set);
    return rowNum;
}
