#ifndef __API_STATUSES_H_
#define __API_STATUSES_H_


#include "XmlDefines.h"



//General statuses
#define STATUS_IN_PROGRESS		 	  						1
#define STATUS_ILLEGAL 										100
#define STATUS_INCONSISTENT_PARAMETERS  	        		101
#define STATUS_OUT_OF_RANGE									102
#define STATUS_INVALID_ALIAS_TYPE                           103
#define STATUS_ACTION_ILLEGAL_AT_SYSTEM_STARTUP				104
#define STATUS_ILLEGAL_PBOJECT								105
#define STATUS_BAD_IP_ADDRESS_VERSION                       106
#define STATUS_IP_ADDRESS_NOT_VALID							108
#define OPERATION_BLOCKED                                   109
#define STATUS_ACTION_ILLEGAL_AT_FAILOVER_SLAVE_MODE		110
#define STATUS_ACTION_ILLEGAL_AT_FAILOVER_MASTER_MODE		111
#define STATUS_PORT_DOES_NOT_SUPPORT_SPEED_1G               112
#define STATUS_ILLEGAL_SYS_MODE 							113//2 modes cop/cp

#define STATUS_CERTIFICATE_CN_SHOULD_BE_EQUAL_TO_USERNAME    200
#define STATUS_CERTIFICATE_SHOULD_INCLUDE_SANS_PRINCIPLE     201
#define STATUS_CERTIFICATE_SHOULD_INCLUDE_SANS               202
#define STATUS_CERTIFICATE_FILE_NOT_EXIST                    203
#define STATUS_CERTIFICATE_COMMON_NAME_NOT_EXIST             204
#define STATUS_PRECONDITION_FAILED							412	//for Rest Api status

//file status
#define STATUS_MAX_FILES_EXCEEDED							905
#define STATUS_FILE_ALREADY_EXISTS							906
#define STATUS_FILE_NOT_EXISTS								907
#define STATUS_NOT_APPROPRIATE_MSG_FILE						908
#define STATUS_ILLEGAL_SERVICE_NAME							909
#define STATUS_FAILED_TO_CREATE_FOLDER						910

#define STATUS_FILE_OPEN_ERROR					911
#define STATUS_FILE_WRITE_ERROR					912
#define STATUS_FILE_READ_ERROR					913
#define STATUS_FILE_SEEK_ERROR					914
#define STATUS_FILE_DELETE_ERROR				915
#define STATUS_FILE_RENAME_ERROR				916
#define STATUS_FILE_FORMAT_ERROR				917

#define STATUS_FOLDER_CREATE_ERROR				930
#define STATUS_FOLDER_REMOVE_ERROR				931
#define STATUS_FOLDER_RENAME_ERROR				932
#define FAULT_ID_AND_FILE_NUM_MISMATCH           933
//!!!!!
//reservation status
#define STATUS_RESERVATION_NAME_EXISTS         1000
#define STATUS_RESERVATION_NOT_EXISTS          1001
#define STATUS_MAX_RESERVATIONS_EXCEEDED       1002
#define STATUS_MAX_PARTIES_EXCEEDED            1003
#define STATUS_ILLEGAL_RESERVATION_TIME        1004
#define STATUS_ILLEGAL_RESERVATION_NAME        1005
#define STATUS_INSUFFICIENT_NUMBER_OF_PARTIES  1006
#define STATUS_UNSUPPORTED_TRANSFER_RATE       1007
#define STATUS_BONDING_IS_NOT_SUPPORTED        1008
#define STATUS_NUMBER_OF_PARTICIPANTS_EXCEEDS_THE_DEFINED_MAXIMUM_FROM_PROFILE 1009
#define STATUS_PROFILE_NAME_ALREADY_EXISTS     1010
//reservation predetermined video source status
#define STATUS_VIDEO_SOURCE_NOT_EXISTS            1011
#define STATUS_VIDEO_SOURCE_EXISTS                1012
#define STATUS_CELL_ID_NOT_EXISTS                 1013
#define STATUS_CELL_ID_EXISTS                     1014
//illegal reservation status
//#define STATUS_ILLEGAL_PARTY_NUMBER_OF_CHANNEL       1015
#define STATUS_INVALID_PARTY_H320_BITRATE       	 1015 //new status for RMX (VNGR-7461)
#define STATUS_H320_DEFINED_DIALIN_IS_NOT_SUPPORTED  1016
/*#define STATUS_ILLEGAL_PARTY_BONDING_MODE            1016
#define STATUS_ILLEGAL_PARTY_NUMBER_OF_PHONES        1017
#define STATUS_UNEXPECTED_T120_BIT_RATE              1018
#define STATUS_INVALID_CHARACTER_IN_SERVICE_NAME     1019
#define STATUS_INVALID_CHARACTER_IN_SUBSERVICE_NAME  1020 */
#define STATUS_INVALID_CHARACTER_IN_PARTY_NAME       1021
#define STATUS_INVALID_CHARACTER_IN_CONFERENCE_NAME  1022
//#define STATUS_ILLEGAL_IDENTIFICATION_METHOD         1023
#define STATUS_ILLEGAL_OPERATOR_CONFERENCE           1024
//#define STATUS_CONFERENCE_TYPE_NOT_ALLOWED           1025
#define STATUS_UNSUPPORTED_H0_BIT_RATE               1026
/*#define STATUS_UNSUPPORTED_ATM_BIT_RATE              1027
#define STATUS_ILLEGAL_AGGREGATION_MODE              1028  */
#define STATUS_UNEXPECTED_VIDEO_PROTOCOL             1029
#define STATUS_UNAPPROPRIATED_H0_BIT_RATE            1030
/*#define STATUS_UNSUPPORTED_V35_BIT_RATE              1031
#define STATUS_ILLEGAL_ATTENDED_CONFERENCE           1032 */
#define STATUS_UNDEFINED_MCU_NUMBER                  1033
#define STATUS_UNDEFINED_PARTY_NUMBER                1034
#define STATUS_ILLEGAL_CASCADE_CONFERENCE            1035
#define STATUS_ILLEGAL_CASCADE_TOPOLOGY              1036
/*#define STATUS_32M_RAM_MAX_RESERVATIONS_EXCEEDED     1036
#define STATUS_BUSY_RESERVING                        1037*/
#define STATUS_MAX_VIDEO_LAYOUTS_EXCEEDED         1038
#define STATUS_RESERVATION_NAME_EXISTS_IN_MEETING_ROOM_DB         1039/*
#define STATUS_ILLEGAL_RESTRICT_PARTY_AT_NON_RESTRICT_CONFERENCE  1040 */
#define STATUS_ILLEGAL_NUMBER_OF_MEETING_ROOM_OCCURENCES          1041
#define STATUS_UNSUPPORTED_AUDIO_ALGORITHM                        1042
//#define STATUS_ILLEGAL_RSRV_REGULAR_CONF_ON_6x2_AUD_BRDG          1043
#define STATUS_VIDEO_PARTY_IN_AUDIO_CONF                          1044
#define STATUS_VOICE_PARTY_CANNOT_BE_AUTODETECT                   1045
#define STATUS_AN_AUDIO_ONLY_PARTICIPANT_CANNOT_BE_SELECTED_AS_LECTURER         1046
/*#define STATUS_YOU_CANNOT_DEFINE_AN_ATTENDED_CONFERENCE_IN_DUO_CONFERENCE_MODE  1047
#define STATUS_YOU_CANNOT_SELECT_CONTINUOUS_PRESENCE_MODE_IN_DUO_CONFERENCE     1048
#define STATUS_YOU_CANNOT_ENABLE_THE_LECTURE_MODE_IN_DUO_CONFERENCE             1049
#define STATUS_DUO_CONFERENCE_MODE_IS_NOT_SUPPORTED                             1050 */
#define STATUS_YOU_CANNOT_ADD_A_H320_PARTY_TO_A_SOFTWARE_CP_CONFERENCE          1051
#define STATUS_LECTURE_SHOW_IS_NOT_SUPPORTED                                    1052
#define STATUS_YOU_CANNOT_SCHEDULE_AN_EMPTY_LECTURE_SHOW_CONFERENCE             1053
#define STATUS_YOU_CANNOT_SCHEDULE_A_LECTURE_SHOW_WITHOUT_LECTURER              1054
//#define STATUS_YOU_CANNOT_DELETE_THE_LECTURER_FROM_THE_LECTURE_SHOW             1055
#define STATUS_UNSUPPORTED_H323_T120_PARTY                     1056
/*#define STATUS_VISUAL_CONCERT_PC_NOT_SUPPORTED                 1057
#define STATUS_ILLEGAL_VIDEO_SESSION_IN_VISUAL_CONCERT_PC      1058
#define STATUS_ILLEGAL_VIDEO_PROTOCOL_IN_VISUAL_CONCERT_PC     1059
#define STATUS_ILLEGAL_VIDEO_FORMAT_IN_VISUAL_CONCERT_PC       1060
#define STATUS_DUO_CONFERENCE_CANNOT_BE_WITH_AUTO_VIDEO_PROTOCOL           1061
#define STATUS_UNABLE_TO_MOVE_PARTY_FROM_LECTURE_SHOW_CONFERENCE           1062
#define STATUS_UNABLE_TO_MOVE_PARTY_TO_LECTURE_SHOW_CONFERENCE             1063
#define STATUS_CANNOT_UPDATE_LECTURER_IN_LECTURE_SHOW_CONFERENCE           1064
#define STATUS_ILLIGAL_CHANGE_TO_ENTRY_QUEUE_ACCESS_IN_RESERVATION         1065 // Changed from 1061 in V4d50 due to conflict in merge
#define STATUS_CANNOT_USE_AUTODETECT_IN_VIDEO_SWITCH_CONF                  1066 */
#define STATUS_VIDEO_CONF_DOES_NOT_SUPPORT_START_REQUIRES_CHAIRPERSON      1067
#define STATUS_CANNOT_UPDATE_ACTIVE_MR_OR_EQ                              1068
#define STATUS_PARTY_IP_ALIAS_ALREADY_EXISTS                              1069
#define STATUS_CANNOT_ADD_DEFINED_PARTY_TO_EQ                             1070
#define STATUS_DONGLE_ENCRYPTION_VAL_IS_FALSE                             1071
#define STATUS_PROFILE_IN_USE_CANNOT_BE_DELETED                           1072
#define STATUS_MAX_PROFILES_EXCEEDED                                      1073
#define STATUS_CONNECT_DISCONNECT_BLOCKED                                 1074
#define STATUS_ILLEGAL_BILLING_DATA_LENGTH                                1075
#define STATUS_AUTO_SELECT_NOT_SUPPORTED_IN_LECTURE_MODE                  1076
#define STATUS_CANNOT_ADD_DEFINED_DIAL_IN_CASCADED_LINK                   1077
#define STATUS_CONFERENCE_RATE_BELLOW_HD_THRESHOLD                        1078
#define STATUS_PARTY_IP_ALREADY_EXISTS				                      1079
#define STATUS_PARTY_ALIAS_ALREADY_EXISTS			                      1080
#define STATUS_ILLEGAL_CHARS_IN_FLAG					                      1081
#define STATUS_MAX_VIDEO_PARTIES_EXCEEDED                                     1082
#define STATUS_TELEPRESENCE_CHANGED_TO_OFF_ITP_CERTIFICATION_IS_OFF_IN_SYSTEM 1083
#define STATUS_CONF_RATE_BELLOW_MIN_TIP_COMPATIBILITY_LINE_RATE				  1084
#define STATUS_PARTY_RATE_BELLOW_MIN_TIP_COMPATIBILITY_LINE_RATE			  1085
#define STATUS_PARTY_VIDEO_RESOLUTION_IS_NOT_TIP_COMPATIBLE					  1086
#define STATUS_PARTY_VIDEO_PROTOCOL_IS_NOT_TIP_COMPATIBLE					  1087
#define STATUS_CONF_NAT_KEEP_ALIVE_PERIOD_HIGHER_THAN_EXPECTED				  1088
/*#define STATUS_ILLEGAL_AUDIO_MIX_DEPTH                                     1101
#define STATUS_WARNING_ILLEGAL_AUDIO_MIX_DEPTH                             1102  */
#define STATUS_UNSUPPORTED_RECORDING_PARTY                                 1103
#define STATUS_MINIMUM_NUMBER_OF_PARTICIPANTS_EXCEEDS_THE_DEFINED_MAXIMUM  1104
//#define STATUS_LEADER_PASSWORD_EXIST                            1105
#define STATUS_ILLEGAL_LAYOUT_IN_SOFTWARE_CP_CONFERENCE         1106
/*#define STATUS_CONFERENCE_PASSWORD_EXIST                        1107
#define STATUS_CONFERENCE_PASSWORD_EXIST_IN_OTHER_ENTRY_QUEUE   1109
#define STATUS_OPERATOR_CONFERENCE_CANNOT_BE_IP_ONLY_CONFERENCE 1110
#define STATUS_DUO_CONFERENCE_CANNOT_BE_IP_ONLY                 1111

#define STATUS_ILLEGAL_DUAL_VIDEO_MODE                          1112
#define STATUS_VISUAL_CONCERT_FX_NOT_SUPPORTED                  1113
#define STATUS_ILLEGAL_VIDEO_SESSION_IN_VISUAL_CONCERT_FX       1114
#define STATUS_ILLEGAL_VIDEO_PROTOCOL_IN_VISUAL_CONCERT_FX      1115
#define STATUS_ILLEGAL_VIDEO_FORMAT_IN_VISUAL_CONCERT_FX        1116
#define STATUS_PEOPLE_AND_CONTENT_IS_NOT_SUPPORTED              1117
#define STATUS_ANNEXES_N_P_OR_F_ARE_NOT_SUPPORTED               1118
#define STATUS_PEOPLE_AND_CONTENT_MUST_HAVE_ANNEXES_N_P_F       1119
#define STATUS_LEADER_PASSWORD_EXIST_IN_OTHER_ENTRY_QUEUE       1120
*/
#define STATUS_ILLEGAL_WHILE_ENTRY_QUEUE_EXISTS                 1121
#define STATUS_ILLEGAL_LAYOUT_IN_ADVANCED_LAYOUTS_CP_CONFERENCE 1122
#define STATUS_ILLEGAL_LAYOUT_IN_REGULAR_CP_CONFERENCE          1123
#define STATUS_VIDEO_FEATURE_CONFLICTS_WITH_VIDEO_CARD_TYPE     1124
/*#define STATUS_LOW_LINE_RATE_IN_INTERLACE_MODE_CONF             1125
#define STATUS_INTERLACE_MODE_IS_ALLOWED_AT_VIDEO_SWITCH_CONF_ONLY 	1126 */
#define STATUS_ENTRY_QUEUE_FEATURE_MUST_USE_AUDIO_PLUS_CARD         1127
#define STATUS_VIDEO_CONF_NOT_SUPPORT_MUTE_MEET_ME_PARTIES          1128
#define STATUS_ILLEGAL_PARAMETER_IN_ENTRY_QUEUE_ACCESSED_CONF       1129
#define STATUS_ILLEGAL_PASSWORD_LENGTH                              1130

#define STATUS_ILLEGAL_LAYOUT_IN_LECTURE_SHOW_CONFERENCE            1131
#define STATUS_ILLEGAL_ASYMMETRIC_LAYOUT_IN_LECTURE_MODE            1132
//#define STATUS_LECTURE_MODE_IS_ILLEGAL_IN_SOFTWARE_CP_CONFERENCE    1133
#define STATUS_ILLEGAL_VIDEO_SESSION_IN_H26L_CONFERENCE             1135
/*#define STATUS_ILLEGAL_PICTURE_FORMAT_IN_H26L_CONFERENCE            1136
#define STATUS_VIDEO_PLUS_NOT_CONFIGURED                            1137 */
#define STATUS_VIDEO_CONF_NOT_SUPPORT_CONFERENCE_ON_HOLD            1138
#define STATUS_ILLEGAL_ACTION_IN_OPERATOR_CONFERENCE                1139
#define STATUS_ILLEGAL_ATTEND_MODE_IN_ENTRY_QUEUE_ACCESSED_CONF     1140
#define STATUS_MAX_PASSWORD_REPEATED_DIGITS_EXCEEDED				1141
/*#define STATUS_POLYCOM_PEOPLE_AND_CONTENT_IS_NOT_SUPPORTED_BY_THE_MCU                       1134
#define STATUS_T120_IS_NOT_SUPPORTED_IN_A_POLYCOM_PEOPLE_AND_CONTENT_CONFERENCE             1141
#define STATUS_HSD_IS_NOT_SUPPORTED_IN_A_POLYCOM_PEOPLE_AND_CONTENT_CONFERENCE              1142
#define STATUS_LSD_IS_NOT_SUPPORTED_IN_A_POLYCOM_PEOPLE_AND_CONTENT_CONFERENCE              1143
#define STATUS_CASCADE_IS_NOT_SUPPORTED_IN_A_POLYCOM_PEOPLE_AND_CONTENT_CONFERENCE          1144
#define STATUS_CHAIR_CONTROL_IS_NOT_SUPPORTED_IN_A_POLYCOM_PEOPLE_AND_CONTENT_CONFERENCE    1145
#define STATUS_POLYCOM_PEOPLE_AND_CONTENT_IS_NOT_SUPPORTED_IN_GATEWAY_SESSIONS              1146
#define STATUS_POLYCOM_PEOPLE_AND_CONTENT_IS_NOT_SUPPORTED_IN_OPERATOR_CONFERENCES          1147
#define STATUS_GREET_AND_GUIDE_IS_NOT_SUPPORTED_IN_A_POLYCOM_PEOPLE_AND_CONTENT_CONFERENCE  1148
#define STATUS_POLYCOM_PEOPLE_AND_CONTENT_IS_NOT_SUPPORTED_IN_ENTRY_QUEUE_CONFERENCES       1149
#define STATUS_SELECTED_DUAL_VIDEO_MODE_IS_NOT_SUPPORTED_IN_AUDIO_ONLY_CONFERENCE           1150
#define STATUS_THE_SELECTED_LINE_RATE_IS_NOT_SUPPORTED_IN_A_POLYCOM_PEOPLE_AND_CONTENT_CONFERENCE       1151
#define STATUS_POLYCOM_PEOPLE_AND_CONTENT_IS_NOT_SUPPORTED_IN_SOFTWARE_CONTINUOUS_PRESENCE_CONFERENCES  1152
#define STATUS_NO_VIDEO_RESOURCES_AVAILABLE                                                 1153
#define STATUS_INTERLACE_MODE_WITHOUT_FIELD_DROP_IS_NOT_ALLOWED_AT_384_LINE_RATE            1154
#define STATUS_POLYCOM_PEOPLE_AND_CONTENT_IS_NOT_SUPPORTED_IN_H26L_CONFERENCE               1155
#define STATUS_POLYCOM_PEOPLE_AND_CONTENT_IS_NOT_SUPPORTED_WITH_QUAD_VIEWS                  1156
#define STATUS_CONF_ON_PORT_CANNOT_BE_OPERATOR_CONFERENCE                                   1157
#define STATUS_CONF_ON_PORT_CANNOT_BE_AN_AUDIO_ONLY_CONFERENCE                              1158
#define STATUS_CONF_ON_PORT_CANNOT_BE_A_SOFTWARE_CP_CONFERENCE                              1159
#define STATUS_CONF_ON_PORT_CONFLICTS_WITH_VIDEO_CARD_TYPE                                  1160 */
#define STATUS_H264_MAX_RATE_IS_384K								1250

//Presentation mode status
#define STATUS_PRESENTATION_MODE_IS_CURRENTLY_NOT_AVAILABLE									1161
#define STATUS_PRESENTATION_MODE_IS_NOT_AVAILABLE_IN_OPERATOR_CONFERENCES					1162
/*#define STATUS_LECTURE_MODE_IS_NOT_AVAILABLE_IN_SOFTWARE_CONTINUOUS_PRESENCE_CONFERENCES	1163
#define STATUS_PRESENTATION_MODE_IS_NOT_AVAILABLE_IN_VIDEO_SWITCHING_CONFERENCES			1180  */
#define STATUS_PRESENTATION_MODE_IS_NOT_AVAILABLE_IN_VIDEO_TRANSCODING_CONFERENCES			1181
/*#define STATUS_UNSUPPORTED_H320_IN_CASCDE_DUO_CONFERENCE
#define STATUS_YOU_CANNOT_SELECT_CONTINUOUS_PRESENCE_MODE_IN_CASCDE_DUO_CONFERENCE          1195  */
#define STATUS_YOU_MUST_CHOOSE_MASTER_NAME                                                  1196
#define STATUS_MASTER_LINK_PARTY_DOESNT_EXIST                                               1197
#define STATUS_FECC_IS_NOT_SUPPORTED_IN_DUAL_STREAM_CASCADING_CONFERENCE                    1214
#define STATUS_VIDEO_SETTINGS_CANNOT_BE_SET_TO_AUTO_IN_DUAL_STREAM_CASCADING_CONFERENCE		1215
#define STATUS_H264_IS_NOT_SUPPORTED_IN_DUAL_STREAM_CASCADING_CONFERENCE                    1216
//auto layout status
#define STATUS_AUTO_LAYOUT_IS_CURRENTLY_NOT_AVAILABLE										1164
#define STATUS_AUTO_LAYOUT_IS_NOT_AVAILABLE_IN_SOFTWARE_CONTINUOUS_PRESENCE_CONFERENCES		1165
#define STATUS_AUTO_LAYOUT_IS_NOT_AVAILABLE_IN_VIDEO_SWITCHING_CONFERENCES					1166
#define STATUS_AUTO_LAYOUT_IS_NOT_AVAILABLE_IN_OPERATOR_CONFERENCES							1167
#define STATUS_AUTO_LAYOUT_IS_NOT_AVAILABLE_IN_LECTURE_SHOW_CONFERENCES						1168
#define STATUS_AUTO_LAYOUT_IS_NOT_AVAILABLE_IN_VIDEO_TRANSCODING_CONFERENCES				1169
/*
#define STATUS_INTERLACE_MODE_IS_ONLY_PERMITTED_WITH_H263_VIDEO_PROTOCOL					1175
#define STATUS_INTERLACE_MODE_IS_NOT_PERMITTED_WITH_DUAL_STREAM_MODE						1176


#define STATUS_PREFIX_OR_H323_SERVICE_NOT_FOUND      1170
#define STATUS_H323_SERVICE_PREFIX_DO_NOT_MATCH      1171 */
#define STATUS_PREFIX_DO_NOT_MATCH_ANY_323_SERVICE   1172
#define STATUS_PREFIX_NOT_IN_DEFAULT_H323_SERVICE    1173
//#define STATUS_SERVICE_DOES_NOT_SUPPORT_GATEKEEPER   1174


#define STATUS_ILLEGAL_CONFERENCE_ID_LENGTH                                            1177
#define STATUS_NUMERIC_CONFERENCE_ID_OCCUPIED                                          1178
#define STATUS_LACK_OF_AVAILABLE_NUMERIC_ID                                         1179
#define STATUS_PHONE_MUST_BE_NUMERIC                                                  1180
#define STATUS_ILLEGAL_PHONE_LENGTH                                                    1181
#define STATUS_LECTURE_MODE_AND_SAME_LAYOUT_ARE_NOT_AVAILABLE_IN_THE_SAME_CONFERENCE   1182
#define STATUS_CONFERENCE_ID_MUST_BE_NUMERIC                                           1183
#define STATUS_PRESENTATION_MODE_AND_SAME_LAYOUT_ARE_NOT_AVAILABLE_IN_THE_SAME_CONFERENCE 1186
#define STATUS_IN_SAME_LAYOUT_MODE_VIDEO_FORCE_IS_FORBIDDEN 1187
#define STATUS_H239_SESSION_CANNOT_BE_ABORTED_FROM_A_SLAVE_CONFERENCE                     1220


//encryption
#define STATUS_ENCRYPTION_IS_CURRENTLY_NOT_AVAILABLE                                      1184
#define STATUS_ENCRYPTION_IS_NOT_AVAILABLE_IN_AUDIO_ONLY_H320_CONFERENCES                 1185
#define STATUS_ENCRYPTION_IS_NOT_AVAILABLE_IN_T120_CONFERENCES                            1187
#define STATUS_ENCRYPTION_IS_NOT_AVAILABLE_IN_LSD_H320_CONFERENCES                        1188
#define STATUS_ILLEGAL_PARTICIPANT_MOVE_BETWEEN_ENCRYPTED_AND_NON_ENCRYPTED_CONFERENCES   1189
#define PARTICIPANT_ENCRYPTION_SETTINGS_DO_NOT_MATCH_THE_CONFERENCE_SETTINGS              1212
#define STATUS_NO_CUSTOMER_PERMISSION_FOR_SOFTWARE_CP_CONF_WITH_H264                      1190
#define STATUS_PROFILE_USED_IN_AD_HOC_EQ_CAN_NOT_BE_QUAD_VIEW                             1191
/*#define STATUS_PROFILE_USED_IN_AD_HOC_EQ_CAN_NOT_BE_SOFTWARE_CONTINUOUS_PRESENCE          1192*/
#define STATUS_ENCRYPTION_IS_NOT_AVAILABLE_IN_H320_PARTY								  1193
#define STATUS_ENCRYPTION_NOT_AVAILABLE_IN_SIP_PARTY									  1213
/*#define STATUS_NUMERIC_CONFERENCE_ID_OR_PASSWORD_COLLISION                                1199
#define STATUS_ILLEGAL_EQ_NAME_LENGTH                                                     1200 */

#define STATUS_ILLEGAL_RECORDING_LINK_INTERFACE_TYPE									  1201
/*#define STATUS_CONF_CAN_NOT_BE_CREATED_WITH_DEFINED_RECORDING_LINK_PARTY                  1202
#define STATUS_CONFERENCE_RECORDING_MUST_BE_CONFIGURED_WITH_IVR							  1203
#define STATUS_CONFERENCE_RECORDING_MUST_BE_CONFIGURED_WITH_RECORDING_LINK				  1204
*/
#define STATUS_PROFILE_USED_IN_AD_HOC_EQ_CAN_NOT_BE_WITH_T120							  1205
#define STATUS_PROFILE_USED_IN_AD_HOC_EQ_CAN_NOT_BE_WITH_LSD							  1206
#define STATUS_PROFILE_USED_IN_AD_HOC_EQ_CAN_NOT_BE_WITH_INTERLACE_MODE					  1207
#define STATUS_PROFILE_USED_IN_AD_HOC_EQ_CAN_NOT_BE_WITH_DUAL_MODE						  1208
#define STATUS_PROFILE_USED_IN_AD_HOC_EQ_CAN_NOT_BE_WITH_ANNEX							  1209
#define STATUS_PROFILE_USED_IN_AD_HOC_EQ_CAN_NOT_BE_WITH_CHAIR_MODE						  1210
#define STATUS_PROFILE_USED_IN_AD_HOC_EQ_CAN_NOT_BE_WITH_CASCADE_MODE					  1211
#define STATUS_PROFILE_NOT_FOUND														  1217
#define STATUS_AD_HOC_EQ_MUST_HAVE_PROFILE												  1218
#define STATUS_PARTY_INTERFACE_TYPE_DOES_NOT_MATCH_SERVICE_TYPE							  1219
#define STATUS_GATEWAY_MUST_HAVE_DIAL_OUT_PROTOCOL										  1221

#define STATUS_IN_EVENT_MODE_CONFERENCE_PERSONAL_LAYOUT_IS_FORBIDDEN                      1222
#define STATUS_IN_VSW_CONFERENCE_PRIVATE_LAYOUT_IS_FORBIDDEN                              1223

#define PARTICIPANT_SIP_ENCRYPTION_SETTINGS_DO_NOT_MATCH_SERVICE_TYPE              		  1224

#define STATUS_GATEWAY_MISSED_DIALIN_NUMBER												  1225
#define STATUS_GATEWAY_WRONG_DIALIN_NUMBERS_RANGE										  1226
#define STATUS_NUMERIC_CONF_ID_OCCUPIED_BY_SIP_FACTORY									  1227

#define STATUS_OPERATOR_PARTY_CAN_NOT_BE_DELETED							              1228
#define STATUS_RESTRICT_CONTENT_CANNOT_BE_SET_ON_A_SLAVE_CONFERENCE                       1229
#define STATUS_RESERVATION_NAME_EXISTS_IN_EQ_LIST										  1230
#define STATUS_RESERVATION_ROUTING_NAME_EXISTS											  1231
#define STATUS_RESERVATION_ROUTING_NAME_EXISTS_IN_MEETING_ROOM_DB         				  1232

/*
//resource reservation/allocation status
#define STATUS_INSUFFICIENT_NET_RSRC             1500
#define STATUS_INSUFFICIENT_MUX_RSRC             1501
#define STATUS_INSUFFICIENT_NET_TDM_RSRC         1502
#define STATUS_INSUFFICIENT_MODULE_TDM_RSRC      1503
#define STATUS_INSUFFICIENT_PHONE_NUMBERS        1504
#define STATUS_INSUFFICIENT_DSP_RSRC             1505
#define STATUS_INSUFFICIENT_AUDIO_CODEC_RSRC     1506*/
#define STATUS_INSUFFICIENT_RSRC                 1507
/*#define STATUS_INSUFFICIENT_VIDEO_CODEC_RSRC     1508
#define STATUS_INSUFFICIENT_VIDEO_BRIDGE_RSRC    1509
#define STATUS_INSUFFICIENT_T123_RSRC            1510
#define STATUS_INSUFFICIENT_MCS_RSRC             1511

#define STATUS_INSUFFICIENT_MESSAGE_RSRC         1512
#define STATUS_INSUFFICIENT_MUSIC_RSRC           1513
#define STATUS_INSUFFICIENT_VIDEO_SLIDE_RSRC     1514
#define STATUS_INSUFFICIENT_IP_RSRC              1515
#define STATUS_INSUFFICIENT_V35_RSRC             1516
#define STATUS_INSUFFICIENT_ATM_RSRC             1517
#define STATUS_INSUFFICIENT_AUDIO_PLUS_RSRC      1518
#define STATUS_INSUFFICIENT_VIDEO_PLUS_RSRC      1519
#define STATUS_NUMBER_OF_AUDIO_PLUS_PARTICIPANTS_EXCEEDS_SYSTEM_CONFIGURATION 1520

// resources' improvement status
#define STATUS_AUD_DSP_FRAGMENTATION             1521
#define STATUS_VID_BRDG_FRAGMENTATION            1522
#define STATUS_MCS_FRAGMENTATION                 1523
#define STATUS_INSUFFICIENT_T1CAS_RSRC           1525

#define STATUS_INSUFFICIENT_MUX_PLUS_RSRC        1530
*/

#define STATUS_NET_SERVICE_NOT_FOUND                         1550
#define STATUS_FALIED_TO_RESET_UNITS                         1551
#define STATUS_FALIED_TO_ENABLE_UNITS                        1552
#define STATUS_FALIED_TO_DISABLE_UNITS                       1553

/*
#define STATUS_PHONE_NOT_IN_DEFAULT_ISDN_SERVICE             1551
#define STATUS_PHONE_NOT_IN_ANY_NET_SERVICE                  1552
#define STATUS_DIAL_IN_NUMBERS_OR_NETWORK_SERVICE_NOT_FOUND  1553


#define STATUS_RSRC_IS_ALREADY_ENABLED            1601
#define STATUS_RSRC_IS_NOT_ENABLED                1602
#define STATUS_UNIT_ID_EXIST_DIFFERENT_UNIT_TYPE  1603
#define STATUS_NO_H221_PER_MCU_NUMBER             1604
#define STATUS_NO_BOND_PER_MCU_NUMBER             1605
#define STATUS_TIME_TOO_FAR_OFF                   1606

#define STATUS_OP_NOT_YET_SUPPORTED               1702
#define STATUS_RSRC_ALREADY_ALLOCATED             1703
#define STAUTS_OUT_OF_CONNECTION_IDS              1704
*/
#define STATUS_RESERVATION_SUSPENDED			  1705
#define STATUS_CANNOT_CHANGE_CONTENT_OWNER_IN_LECTURE_MODE     1706


//party status (within reservation or within conference)
#define STATUS_PARTY_NAME_EXISTS                  2000
#define STATUS_PARTY_DOES_NOT_EXIST               2001 // replaces STATUS_PARTY_NOT_EXISTS
#define STATUS_ILLEGAL_PARTY_NAME                 2002
#define STATUS_MOVE_PARTY_NOT_COMPLETED           2003
#define STATUS_ADD_PARTY_NOT_COMPLETED            2004
#define STATUS_UPDATE_PARTY_NOT_COMPLETED         2005
#define STATUS_ILLEGAL_H263_PARTICIPANT_ACTION    2006
#define STATUS_PARTY_SERVICE_NOT_FOUND_IN_CONFERNCE_SERVICE_LIST   2007
#define STATUS_LEASED_LINE_PARTY_NOT_ALLOWED                       2008
#define STATUS_NOT_APPROPRIATE_NET_SERVICE_TYPE                    2009
#define STATUS_NOT_APPROPRIATE_VIDEO_PROTOCOL_FOR_MOVE_ACTION      2010
#define STATUS_ILLEGAL_MOVE_PARTY_BETWEEN_AUD_AND_AUDPLUS_CONFS    2015
#define STATUS_PARTY_NET_TYPE_CONFLICTS_WITH_CONF_NET_TYPE         2016
#define STATUS_AUDIO_PLUS_NOT_CONFIGURED                           2017
#define STATUS_323PARTY_NOT_ALLOWED_IN_ATTENDED_CONF               2018
#define STATUS_ILLEGAL_MOVE_PARTY_BETWEEN_VID_AND_VIDPLUS_CONFS    2019
#define STATUS_PARTY_VISUAL_NAME_EXISTS                            2020
#define STATUS_PARTY_VISUAL_NAME_NOT_EXISTS                        2021
#define STATUS_PERSONAL_LAYOUT_IS_MANAGED_INTERNALLY               2022
#define STATUS_CONFERENCE_LAYOUT_IS_MANAGED_INTERNALLY             2023
/*
//#define STATUS_AUDIO_ALGORITHM_NOT_SUPPORTED		2022 //Oshi: dont use this status
#define STATUS_ILLEGAL_MOVE_BETWEEN_SOFTWARE_CP_AND_DIFFERENT_CONFERENCE_TYPE         2023
#define STATUS_ILLEGAL_MOVE_BETWEEN_SOFTWARE_CP_CONFERENCES_WITH_DIFFERENT_RATE       2024
#define STATUS_ILLEGAL_MOVE_BETWEEN_ADVANCED_LAYOUTS_AND_DIFFERENT_CONFERENCE_TYPE    2025
#define STATUS_ILLEGAL_MOVE_WHILE_PARTY_IN_IVR                         2026  */
#define STATUS_AGC_IS_NOT_CONFIGURED                                   2027  /*
#define STATUS_ILLEGAL_MOVE_BETWEEN_CONFERENCES_WITH_DIFFERENT_INTERLACED_VIDEO_MODE              2028
#define STATUS_ILLEGAL_MOVE_BETWEEN_H26L_CONFERENCE_AND_CONFERENCE_WITH_DIFFERENT_VIDEO_PROTOCOL  2029
#define STATUS_T1_CAS_PARTICIPANT_MUST_BE_AUDIO_ONLY                   2030
#define STATUS_PARTY_NETWORK_T1CAS_CONFLICTS_WITH_AUDIO_CARD_TYPE      2031
#define STATUS_T1_CAS_PARTICIPANT_IS_NOT_ALLOWED_IN_A_VIDEO_CONFERENCE 2032
//#define STATUS_T1_CAS_PARTY_IS_NOT_ALLOWED_IN_AUDIO_CONFERENCE 2033
#define STATUS_AUDIO_PLUS_BOARD_FOR_T1CAS_IDLE_NOT_AVAILABLE           2034
#define STATUS_T1_CAS_DEFINED_DIAL_IN_NOT_PERMITTED                    2035
#define STATUS_ILLEGAL_VIDEO_SESSION_FOR_SAME_LAYOUT                   2036
#define STATUS_YOU_CANT_DELETE_MASTER_LINK_PARTY_WITHOUT_TERMINATING_CONF    2037
#define STATUS_WRONG_MASTER_NAME                                       2038  */
#define STATUS_ILLEGAL_QUALITY_VALUE_FOR_THIS_VIDEO_SESSION_TYPE       2039
#define STATUS_ILLEGAL_QUALITY_VALUE_FOR_THIS_VIDEO_PROTOCOL           2040
#define STATUS_RECORDING_PARTY_MUST_BE_AUDIO_ONLY				       2041

//ongoing conference status
#define STATUS_CONF_NOT_EXISTS            								2500
#define STATUS_CONF_NAME_EXISTS           					            2501
#define STATUS_ILLEGAL_END_TIME                                         2502
#define STATUS_TERMINATING_CONFERENCE     						        2503
#define STATUS_PARTIES_NUMBER_LIMIT_EXCEEDED    				        2506
#define STATUS_PARTY_IS_PRESENT_IN_SEVERAL_CELLS  						2507
#define STATUS_FORCE_ILLEGAL_IN_AUDIO_PLUS_CONF 				        2508  // Obsolete
#define STATUS_OTHER_OPERATOR_PARTY_JOINED_TO_THIS_CONFERENCE           2511  // Obsolete
#define STATUS_OPERATOR_PARTY_NOT_AVAILABLE                             2512  // Obsolete
#define STATUS_CONF_IS_SECURED                                          2513  // Obsolete
#define STATUS_ROLL_CALL_IS_DISABLED                                    2514  // Obsolete
#define STATUS_ROLL_CALL_IS_DISABLED_IN_IVR                             2516  // Obsolete
#define STATUS_ADD_PARTICIPANT_TO_SECURE_CONF                           2517
#define STATUS_SILENCE_IT_IS_DISABLED_IN_IVR	                        2521  // Obsolete
#define STATUS_MEETING_ROOM_NOT_EXISTS                                  2552
#define STATUS_CAN_NOT_ADD_SIP_H320_TO_VSW_LPR_CONFERENCE				2553
#define STATUS_ISDN_VIDEO_PARTICIPANT_IS_NOT_SUPPORTED_IN_VS_CONF		2554
#define STATUS_ISDN_CONNECTIONS_NOT_SUPPORTED						    2555
#define STATUS_AV_MCU_NOT_SUPPORTED_IN_MIXED_MODE_CONF          		2556
#define STATUS_NO_MORE_THEN_1_AV_MCU_LINK_IN_CONF_IS_ALLOWED          	2557

//#define STATUS_MEETING_ROOM_CAN_NOT_BE_OPERATOR_CONF            		2572


#define STATUS_ILLEGAL_WHILE_MEETING_ROOM_EXISTS						2574
#define STATUS_ILLEGAL_WHILE_CONFERENCES_EXISTS							11001

#define  STATUS_PHONE_NUMBER_WITH_FORBIDDEN_CHARACTERS 4013


//phone numbers status
#define  STATUS_PHONE_NUMBER_ALREADY_EXISTS             4000
#define  STATUS_PHONE_NUMBER_NOT_EXISTS         4001
#define  STATUS_PHONE_NUMBER_OCCUPIED           4002
#define  STATUS_MAX_PHONE_NUMBER_EXCEEDED       4003
#define  STATUS_PHONE_NUMBER_CONFIGURED_IN_EQ   4004

//operators configuration status
#define  STATUS_LOGIN_EXISTS											7000
#define  STATUS_LOGIN_NOT_EXISTS										7001
#define  STATUS_NO_PERMISSION											7002
#define  STATUS_LOGIN_INVALID											7003
#define  STATUS_PASSWORD_NOT_VALID                                      7004
#define  STATUS_NUMBER_OF_OPERATORS_IN_MCU_EXCEEDED   					7005
#define  STATUS_NUMBER_OF_CONNECTIONS_IN_MCU_EXCEEDED					7006
#define  STATUS_LAST_SUPERVISOR_OPERATOR_IN_MCU							7007
#define  STATUS_SUPPORT_USER_NAME_IS_NOT_ALLOWED_JITC  					7010

#define  STATUS_AT_LEAST_4_CHARACTERS_IN_PASSWORD_MUST_BE_CHANGED		7013
#define  STATUS_NEW_PASSWORD_WAS_USED_RECENTLY							7014


//Multiple links for ITP in cascaded conference feature
#define STATUS_MISMATCH_IN_NUMBER_OF_ITP_LINKS                           7030

// FIPS status
#define FIPS140_STATUS_FIRST_OPCODE						 8100
#define FIPS140_STATUS_FAILURE						 	 8101

#define FIPS140_STATUS_OK								 8130
#define FIPS140_STATUS_ERROR_SHA1_FAILURE                8131
#define FIPS140_STATUS_UNKNOWN_ERROR                     8132
#define FIPS140_STATUS_ERROR_SHA256_FAILURE              8133

#define FIPS140_CONTINUOUS_CONTROL_UNIT_POOL_GENERATION	 8140
#define FIPS140_CONTINUOUS_CONTROL_UNIT_BYPASS		  	 8141

//network services status
#define  STATUS_SERVICE_PROVIDER_NAME_EXISTS							10000
#define  STATUS_SERVICE_PROVIDER_NAME_NOT_EXISTS					    10001
#define  STATUS_SPAN_EXISTS												10002
#define  STATUS_SPAN_NOT_EXISTS										   	10003
#define  STATUS_SPAN_OCCUPIED                                           10004

// RtmIsdnMngr
#define STATUS_NUMBER_OF_ISDN_SERVICES_EXCEEDED							10007
#define STATUS_NUMBER_OF_PHONES_IN_SERVICE_EXCEEDED						10008
#define STATUS_NUMBER_OF_DIALIN_EXCEEDED								10009
#define STATUS_MCU_PHONE_NUMBER_ALREADY_EXISTS							10010

#define STATUS_NUMBER_OF_ISDN_SPAN_MAPS_EXCEEDED						10011
#define STATUS_SPAN_MAP_ALREADY_EXISTS									10012
#define STATUS_SPAN_MAP_NOT_EXISTS										10013
#define STATUS_MISMATCH_SERVICE_NAME_AND_SPAN_ATTACHED					10014

#define STATUS_ILLEGAL_PHONE_RANGE										10015
#define STATUS_PHONE_RANGE_NOT_EXISTS									10016
#define STATUS_PHONE_RANGE_ALREADY_EXISTS								10017
#define STATUS_PHONE_NUMBER_EXISTS_IN_OTHER_SERVICE						10018
#define STATUS_NUMBER_OF_PHONE_NUMBERS_IN_RANGE_EXCEEDED				10019

#define STATUS_SPAN_MAP_UPDATED										    10020


#define  STATUS_IP_SPAN_IS_NOT_ON_THE_SAME_SUBNET_AS_THE_OTHER_SPANS   	10022
//#define  STATUS_SPAN_EXISTS_IN_H323_SERVICE								10303
#define  STATUS_EMPTY_PARTY_ALIAS_NAME                     				10341
#define  STATUS_ALIAS_NAME_TOO_LONG										10342
#define  STATUS_ALIAS_NAMES_CANNOT_INCLUDE_A_COMMA      	 			10343
#define  STATUS_ILLEGAL_EMAIL_ID_ALIAS						 			10344
#define  STATUS_ALIAS_E164_TYPE_NAMES_MUST_BE_ALPHA_NUMERIC				10345
#define  STATUS_INVALID_ALIAS											10346

#define  STATUS_ILLEGAL_LANGUAGE_NAME                                   10543

#define STATUS_NO_CUSTOMER_PERMISSION_FOR_VIRTUAL_CONF_SUITE        14000

// IVR Status 10500 - 10600
#define  STATUS_MAX_AV_MSG_SERVICES_EXCEEDED     						10500
#define  STATUS_AV_MSG_SERVICE_NAME_EXISTS      	  					10501
#define  STATUS_AV_MSG_SERVICE_NAME_NOT_EXISTS     						10502
#define  STATUS_AV_MSG_FILE_DOESNT_EXISTS          						10503
#define  STATUS_AV_MSG_MUSIC_DISABLED              						10504

#define  STATUS_MAX_NUMBER_OF_IVR_SERVICES_EXCEEDED             		10520
#define  STATUS_IVR_SERVICE_NAME_EXISTS                         		10521
#define  STATUS_IVR_SERVICE_NAME_DOES_NOT_EXISTS                		10522
#define  STATUS_THIS_IS_NOT_A_NAME_OF_AN_IVR_SERVICE            		10523
#define  STATUS_THIS_AUDIO_CARD_DOES_NOT_SUPPORT_IVR_SERVICES   		10524
#define  STATUS_IVR_ILLEAGAL_DTMF_TBL             						10525
#define  STATUS_IVR_ILLEAGAL_ASSIST_REQEST        						10526
#define  STATUS_IVR_MSG_NAME_MISSING              						10527
#define  STATUS_IVR_MSG_ILLEGAL_NAME              						10528
#define  STATUS_INCOMPATIBLE_IVR_DEFAULT_SERVICE  						10529

#define  STATUS_MSG_SERVICE_NAME_ALREADY_EXISTS   						10530
#define  STATUS_MSG_SERVICE_NAME_DOES_NOT_EXISTS  						10531

#define  STATUS_IVR_SERVICE_DISABLED                   					10532
#define  STATUS_INCOMPATIBLE_IVR_SERVICE               					10533
#define  STATUS_INVALID_IVR_EXTERNAL_DB_CONFIGURATION  					10534
#define  STATUS_IVR_EXTERNAL_DB_DISABLED               					10535
#define  STATUS_DEFAULT_MSG_SERVICE_CANNOT_BE_REMOVED  					10536
#define  STATUS_INVALID_IVR_EXTERNAL_DB_PARAMETER	  					10537

#define  STATUS_THE_MAXIMUM_NUMBER_OF_LANGUAGES_IN_IVR_SERVICE_IS_EXCEEDED    10540
#define  STATUS_THIS_LANGUAGE_ALREADY_EXISTS_IN_THE_IVR_SERVICE			10541
#define  STATUS_THIS_LANGUAGE_DOES_NOT_EXIST_IN_THE_IVR_SERVICE			10542
#define  STATUS_ILLEGAL_LANGUAGE_NAME									10543

#define  STATUS_VIDEOCOMMANDER_IS_NOT_SUPPORTED							10546
#define  STATUS_ILLEGAL_DTMF_CODE_PERMISSON								10547
#define  STATUS_ILLEGAL_DTMF_CODE_LEN									10548
#define  STATUS_ILLEGAL_DTMF_CODE_CHARACTER								10549
#define  STATUS_IVR_ILLEGAL_WHILE_PROFILE_EXISTS						10550

#define	 STATUS_CASCADE_LINK_CANNOT_BE_SET_AS_CHAIRPERSON				10551
#define	 STATUS_PARTY_IN_IVR_CANNOT_BE_SET_AS_CHAIRPERSON				10552

#define  STATUS_IVR_LAST												10600
// IVR Status End (10600)

//Recorind Link Statuses
#define STATUS_RECORDING_LINK_DOES_NOT_EXIST						   10601
#define STATUS_MAX_RECORDING_LINKS_REACHED							   10603
#define STATUS_INVALID_RECORDING_LINK_NETWORK_SETTINGS				   10604
#define STATUS_CANNOT_DELETE_RECORDING_LINK_WHILE_ASSIGNED			   10605
#define STATUS_EQ_CANNOT_CONFIG_WITH_RECORDING_LINK                    10606

//ssl statuses
#define STATUS_SSL_CERTIFICATE_DOES_NOT_MATCH_THE_PRIVATE_KEY			16003
#define STATUS_UNABLE_TO_CREATE_SSL_CERTIFICATE_REQUEST					16008
#define STATUS_SSL_ILLEGAL_COUNTRY_NAME								 	16009
#define STATUS_SSL_ILLEGAL_STATE_OR_PROVINCE						  	16010
#define STATUS_SSL_ILLEGAL_LOCALITY_NAME							  	16011
#define STATUS_SSL_ILLEGAL_ORGANIZATION_NAME						  	16012
#define STATUS_SSL_ILLEGAL_ORGANIZATION_UNIT_NAME					  	16013
#define STATUS_SSL_ILLEGAL_COMMON_NAME								  	16014
#define STATUS_UNABLE_TO_CREATE_SSL_CERTIFICATE							16015
#define STATUS_CAN_NOT_SECURE_CONNECTION_WITHOUT_CERTIFICATE			16020
#define STATUS_CERTIFICATE_ALREADY_EXPIRED								16021
#define STATUS_CERTIFICATE_FILE_HAS_AN_ERROR							16022
#define STATUS_CERTIFICATE_COMMON_NAME_DIFFER_THAN_RMX_HOST_NAME		16024
#define STATUS_CERTIFICATE_NOT_VALID_YET								16025
#define STATUS_CERTIFICATE_IS_GOING_TO_BE_EXPIRED						16026
#define STATUS_CANT_CHANGE_DNS_NAME_IN_SECURED_MODE						16027
#define STATUS_CERTIFICATE_IS_EMPTY                                     16028
#define STATUS_SERIAL_NUMBER_IS_EMPTY                                   16029
#define STATUS_ISSUER_NAME_IS_EMPTY                                     16030
#define STATUS_CERTIFICATE_CTL_FOR_CRL_NOT_EXIST                        16031
#define STATUS_CERTIFICATE_ALREADY_EXIST                                16032
#define STATUS_UNABLE_TO_DELETE_LAST_CERTIFICATE                        16033
#define STATUS_CERTIFICATE_IS_NOT_CTL                                   16034
#define STATUS_CERTIFICATE_CTL_NOT_EXIST                                16035
#define STATUS_CERTIFICATE_OWN_NOT_EXIST                                16036
#define STATUS_CERTIFICATE_CRL_NOT_EXIST                                16037
#define STATUS_CERTIFICATE_CRL_EXCEEDED_MAX_SIZE                        16038
#define STATUS_CERTIFICATE_IS_SELF_SIGN									16039
#define STATUS_FAILED_TO_CHECK_SELF_SIGN								16040
#define STATUS_SSL_ILLEGAL_SUBJECT_ALT_NAME								16041
#define STATUS_NO_START_LINE_CERTIFICATE                                16042
//xml api (Statuses are DWORDs in order to maintain compatibility with XAP)
#define STATUS_FAIL_TO_LOCATE_USER                      				0x00010019//65561 //in use
#define STATUS_OBJECT_NOT_RECOGNIZED                    				0x00010029//65577  //in use
#define STATUS_NOT_FOUND												0x00010039//65593
#define STATUS_ACCESS_DENIED											0x00010040//65600	//Apache status
#define STATUS_SERVER_ERROR												0x00010047//65607		//Apache status
#define STATUS_PROCESS_FAILURE											0x00010048//65608	//Apache status
#define STATUS_DECOMPRESSION_FAILED										0x00010049//65609	//Apache status
#define STATUS_REQUEST_TOO_LONG											0x0001004a//65610	//Apache status
#define STATUS_INTERNAL_COMMUNICATION_PROBLEM                           0x0001004b//65611	//Apache status
#define STATUS_ILLEGAL_REQUEST                                          0x0001004c//65612	//Apache status

#define STATUS_TRANSACTION_DOES_NOT_EXIST               0x00010002  //65538
#define STATUS_NODE_MISSING                             0x00010023  //65571
#define STATUS_NODE_VALUE_INVALID                       0x00010024  //65572
#define STATUS_NODE_LENGTH_TOO_LONG                     0x00010025  //65573
#define STATUS_FAIL_TO_VALIDATE_RESPONSE                0x00010026  //65574
#define STATUS_TRANSACTION_IS_NOT_WELL_FORMED           0x00010027  //65575
#define STATUS_ACTION_NODE_IS_MISSING_OR_INVALID        0x00010028  //65576
#define STATUS_VALUE_OUT_OF_RANGE                       0x00010030  //65584
#define STATUS_INVALID_KEY			                    0x00010031  //65585
#define STATUS_NODE_LENGTH_TOO_SHORT                    0x00010032  //65586
#define STATUS_MIN_MAX_MISSING_IN_KEY					0x00010033  //65587
#define STATUS_API_INTERNAL_ERROR						0x00010034  //65588
#define STATUS_ENUM_VALUE_INVALID						0x00010035  //65589
#define STATUS_IP_ADDRESS_INVALID						0x00010036  //65590
#define STATUS_ATM_ADDRESS_INVALID						0x00010037  //65591
#define STATUS_DATE_TIME_INVALID						0x00010038  //65592

#define STATUS_ENCODING_CONVERTION_FAILED               0x00010050	//65616
#define STATUS_ENCODING_VALIDATION_FAILED               0x00010051	//65617
#define STATUS_CONVERTION_UTF8_TO_ORIGIN_FAILED			0x00010052  //65618

#define STATUS_NODE_VALUE_NOT_ASCII                     0x00010060	//65632
#define STATUS_UNKNOWN_CHARSET_ENCODING                 0x00010061  //65633
#define STATUS_CHARSET_ENCODING_UNDETERMINABLE          0x00010062  //65634


// IVR statuses - Range 30001 - 30200
#define STATUS_NO_IVR_SERVICE_IN_LIST									30001
#define STATUS_NO_EQ_SERVICE_IN_LIST									30002
#define STATUS_IVR_INTERNAL_ERROR										30003
#define STATUS_IVR_INVALID_AUDIO_FILE									30004
#define STATUS_IVR_INVALID_VIDEO_FILE									30005
#define STATUS_IVR_VIDEO_FILE_DOES_NOT_EXIST							30006
#define STATUS_IVR_AUDIO_FILE_DOES_NOT_EXIST							30007
#define STATUS_IVR_NUMERIC_ID_DISABLED									30008
#define STATUS_IVR_ILLEGAL_PARAMETERS									30009
#define STATUS_IVR_BILLING_CODE_MSG_ERROR								30010
#define STATUS_RECORDING_DISABLED_IN_CONF								30011
#define STATUS_IVR_DTMF_CODE_NOT_SUPPORTED_IN_SOFT_MCU					30012
#define STATUS_IVR_GENERAL_FEATURE_NOT_SUPPORTED_IN_SOFT_MCU			30013
#define STATUS_IVR_ROLL_COLL_NOT_SUPPORTED_IN_SOFT_MCU				    30014

//
#define STATUS_PARTY_NONE				0xff
#define STATUS_PARTY_INCONF 			2
#define STATUS_PARTY_IVR                3


//New statuses: Range 30201-59999 - the same range to all the processes
#define STATUS_FAIL_TO_GET_NEW_VERSION_NUMBER							30201
#define STATUS_ILLEGAL_VERSION_NUMBER									30202
#define STATUS_INSUFFICIENT_MNTR_CONF_ID                                30203
#define STATUS_SYSTEM_CFG_NO_VALID										30204
#define STATUS_BROKEN_PIPE                                   			30205
#define STATUS_QUEUE_TIMEOUT       							 			30206
#define STATUS_QUEUE_ID_INVALID    							 			30207
#define STATUS_TRANSPORT_NOTCONNECTED    							 	30208



#define STATUS_NO_REQUEST_OBJECT										30210
#define STATUS_SYSCALL_FAILURE											30211
#define STATUS_DUPLICATE_ADDRESS                                        30212
#define STATUS_BAD_GATEWAY_IP                                           30213
#define STATUS_OLD_PASSWORD_IS_INCORRECT								30214
#define STATUS_ADMIN_PASSWORD_IS_INCORRECT								30215


// CSMngr (30300 - 30399)
#define STATUS_TOO_MANY_SERVICES										30300
#define STATUS_NO_NUM_OF_PORTS											30302
#define STATUS_GK_PREFIX_NOT_NUMERIC									30306
#define STATUS_GK_PREFIX_TOO_MANY_DIGITS								30307
#define STATUS_GK_PREFIX_TOO_BIG										30308
#define STATUS_GK_ALIAS_EMPTY_NAME										30310
#define STATUS_SERVICE_NOT_EXIST										30311
#define STATUS_SERVICE_EXIST											30312
#define STATUS_SERVICE_NO_SPAN											30313
#define STATUS_SERVICE_DUPLICATE_IP_CS_MNGMNT							30314
#define STATUS_SERVICE_NO_NAME											30315
#define STATUS_NO_SERVICES												30316
#define STATUS_IP_ADDRESS_MISMATCHES_NETMASK							30317
#define STATUS_ILLEGAL_NUM_TCP_PORTS							        30318
#define STATUS_ODD_NUM_TCP_PORTS    							        30319
#define STATUS_SERVICE_LOCAL_IP_ADDRESS    						        30320
#define STATUS_INVALID_REGISTRATION_REFRESH_TIMEOUT                     30321
#define STATUS_INVALID_SERVICE                                          30322
#define STATUS_ILLEGAL_DNS_SERVERS_ADDRESSES					        30323
#define STATUS_ROUTER_CANT_BE_CHANGED_IN_SMCU							30324
#define STATUS_DNS_CANT_BE_CHANGED_IN_SMCU								30325
#define STATUS_INTERFACE_IS_NOT_CONFIGURED_IN_THE_SYSTEM				30326
#define STATUS_IP_ADDRESS_IS_DIFFERENT_FROM_THE_ONE_CONFIGURED_IN_THE_SYSTEM 30327
#define STATUS_SUBNET_MASK_CANT_BE_CHANGED_IN_SMCU						30328
#define STATUS_ONLY_IPV4_IS_SUPPORTED_IN_SMCU							30329
#define STATUS_PORT_SPEED_CANT_BE_CHANGED_IN_SMCU						30330
#define STATUS_SHM_IP_ADDRESS_CANT_BE_CHANGED_IN_SMCU					30331
#define STATUS_V35_CANT_BE_CHANGED_IN_SMCU								30332
#define STATUS_HOST_NAME_CANT_BE_CHANGED_IN_SMCU						30333
#define STATUS_ETHERNET_SETTING_CANT_BE_UPDATED_IN_SMCU					30334
#define STATUS_UNSUPPORTED_H323_PROTOCOL								30335
#define STATUS_ILLEGAL_FIRST_UDP_PORT_VALUE								30336
#define STATUS_MUST_ASSIGN_INTERFACE_IN_MFW								30337
#define STATUS_IP_ADDRESS_MISMATCHES_SYSTEM								30338
#define STATUS_IPV6_GLOBAL_ADDRESS_MISMATCHES_SYSTEM					30339
#define STATUS_IPV6_SITE_ADDRESS_MISMATCHES_SYSTEM						30340
#define STATUS_IPV6_LINK_ADDRESS_MISMATCHES_SYSTEM						30341
#define STATUS_NONE_IPV4_IPV6_ADDRESS									30342

#define STATUS_MANAGEMENT_INTERFACE_CANT_BE_CHANGED_IN_EDGE             30343
#define STATUS_SIGNALING_AND_MEDIA_MUST_BE_SAME_IN_EDGE                 30344

//new statuses range (30400 - 30499)
#define STATUS_DIRECTORY_ALREADY_EXISTS									30400
#define STATUS_CANT_FIND_VIRTUAL_DIRECTORY								30401

#define STATUS_KEYCODE_INVALID											30410
#define STATUS_KEYCODE_ILLEGAL											30411
#define STATUS_KEYCODES_VERSIONS_MISMATCH								30412
#define STATUS_MCU_VERSION_INSTALL_FAILED								30413
#define STATUS_NEW_MCU_VERSION_MISMATCHES_KEYCODE_VERSION				30414
#define STATUS_NEW_KEYCODE_VERSION_MISMATCHES_MCU_VERSION				30415
#define STATUS_EMPTY_USERNAME                                           30416
#define STATUS_VERSION_ALREADY_INSTALLED                                30417
#define STATUS_NO_FALLBACK_VERSION                                      30418

#define STATUS_ILLEGAL_OPERATION_VIDEO_CAPABILITIES_INACTIVE	        30420

// McuMngr
#define STATUS_CFG_PARAM_UNSUPPORTED_LAN_REDUNDANCY_IPV6              30426
#define STATUS_CFG_PARAM_MISSMATCH_LAN_REDUNDANCY_AND_MULTIPLE_SERVICES	30427
#define STATUS_CFG_PARAM_MISSMATCH_LAN_REDUNDANCY_AND_NETWORK_SEPARATION 30428
#define STATUS_CFG_PARAM_TRY_ADD_CS_LOGS_TRACE							30429
#define STATUS_BAD_RESTORE_TYPE											30430
#define STATUS_CFG_PARAM_NOT_EXIST										30431
#define STATUS_CFG_PARAM_TYPE_DONT_MATCH								30432
#define STATUS_CFG_PARAM_DATA_TYPE_DONT_MATCH							30433
#define STATUS_CFG_PARAM_SECTION_DONT_MATCH								30434
#define STATUS_FAIL_TO_CONFIG_MNGMNT_IP									30435
#define STATUS_FAIL_TO_CONFIG_DNS										30436
#define	STATUS_FAIL_TO_CONFIG_DHCP										30437
#define	STATUS_DUPLICATE_ADDRESS_CNTRL									30438
#define	STATUS_DUPLICATE_ADDRESS_SHELF									30439
#define STATUS_DUPLICATE_IPV4_ADDRESS_CNTRL								30440
#define STATUS_DUPLICATE_IPV6_ADDRESS_CNTRL								30441
#define	STATUS_OK_WARNING										        (STATUS_OK | WARNING_MASK)
#define STATUS_FAIL_TO_CONFIG_MNGMNT_ETHERNET							30442
#define STATUS_CFG_PARAM_UNSUPPORTED_JITC_MODE							30443
#define STATUS_CFG_PARAM_UNSUPPORTED_MULTIPLE_SERVICE_IPV6              30444
#define STATUS_CFG_PARAM_MISSMATCH_NETWORK_SEPARATION_AND_MULTIPLE_SERVICES		30445
#define STATUS_CFG_PARAM_MISSMATCH_MULTIPLE_SERVICES_AND_V35_ULTRA_SECURED		30446
#define STATUS_CFG_PARAM_UNSUPPORTED_SEPARATE_MANAGEMENT_V35            30447
#define STATUS_IPV6_FORCE_DNS                                           30448
#define STATUS_IP_SERVICE_DNS_TYPE_DNS                                  30449

//NTP_PEER_RELATED
#define STATUS_NTP_PEER_REJECT                                          30450
#define STATUS_NTP_PEER_FALSETICK                                       30451
#define STATUS_NTP_PEER_EXCESS                                          30452
#define STATUS_NTP_PEER_OUTLYER                                         30453
#define STATUS_NTP_PEER_CANDIDAT                                        30454
#define STATUS_NTP_PEER_SELECTED                                        30455
#define STATUS_NTP_PEER_SYS_PEER                                        30456
#define STATUS_NTP_PEER_PPS_PEER                                        30457

#define STATUS_SMART_REPORT_ERRORS                                      30460
#define STATUS_CFG_PARAM_UNSUPPORTED_MULTIPLE_SERVICE_LICENSE           30461
// Installer

// /Libs/XmlPars/XmlDefines
//#define WARNING_MASK                0x80000000

#define STATUS_CFS_MSG_0												30470
#define STATUS_CFS_MSG_1												30471
#define STATUS_CFS_MSG_2												30472
#define STATUS_CFS_MSG_3												30473
#define STATUS_CFS_MSG_4												30474
#define STATUS_CFS_MSG_5												30475
#define STATUS_CFS_MSG_6												30476
#define STATUS_CFS_MSG_7												30477
#define STATUS_CFS_MSG_8												30478
#define STATUS_CFS_MSG_9												30479
#define STATUS_CFS_MSG_10												30480
#define STATUS_CFS_MSG_11												30481
#define STATUS_CFS_MSG_12												30482

#define STATUS_INSTALLATION_IN_PROGRESS                                 30483
#define STATUS_NEW_VERSION_CANNOT_BE_INSTALLED							30484
#define STATUS_PRODUCT_FAMILY_TYPE_MISMATCH								30485	// for Call Generator - ValidateProductFamily
#define STATUS_INSTALLTION_WHILE_DEBUG_MODE								30486
#define STATUS_NEW_VERSION_CANNOT_BE_INSTALLED_IN_RMX1500				30487
#define STATUS_CFS_MSG_13												30488 //kobig - have no other choice inorder not to break comptability jumped to 30488

// Backup Restore
#define	STATUS_BACKUP_IN_PROGRESS										30490
#define STATUS_RESTORE_IN_PROGRESS										30491
#define STATUS_BACK_TO_FACTORY_DEFAULTS_IN_PROGRESS						30492

#define STATUS_CFS_MSG_0_WARNING_MASKED									(STATUS_CFS_MSG_0 | WARNING_MASK)

#define STATUS_CFS_MSG_2_WARNING_MASKED									(STATUS_CFS_MSG_2 | WARNING_MASK)
#define STATUS_CFS_MSG_3_WARNING_MASKED									(STATUS_CFS_MSG_3 | WARNING_MASK)
#define STATUS_CFS_MSG_4_WARNING_MASKED									(STATUS_CFS_MSG_4 | WARNING_MASK)
#define STATUS_CFS_MSG_5_WARNING_MASKED									(STATUS_CFS_MSG_5 | WARNING_MASK)
#define STATUS_CFS_MSG_6_WARNING_MASKED									(STATUS_CFS_MSG_6 | WARNING_MASK)
#define STATUS_CFS_MSG_7_WARNING_MASKED									(STATUS_CFS_MSG_7 | WARNING_MASK)

#define STATUS_CFS_MSG_9_WARNING_MASKED									(STATUS_CFS_MSG_9 | WARNING_MASK)
#define STATUS_CFS_MSG_10_WARNING_MASKED								(STATUS_CFS_MSG_10 | WARNING_MASK)
#define STATUS_CFS_MSG_11_WARNING_MASKED								(STATUS_CFS_MSG_11 | WARNING_MASK)

// Logger
#define STATUS_FILE_SYSTEM_DISABLED										30500
#define STATUS_FAILED_TO_FLUSH		                                    30501
#define STATUS_INSUFFICIENT_DISK_SPACE		                            30502

#define STATUS_CONFERENCE_CREATION_IS_BLOCKED							30510
#define STATUS_ILLEGAL_WHILE_EQ_IS_ACTIVE                               30511
#define STATUS_ILLEGAL_WHILE_MR_IS_ACTIVE                               30512
#define STATUS_ILLEGAL_LAYOUT_COMPOSITION                               30513
#define STATUS_CONFERENCE_CREATION_IS_BLOCKED_FOR_INVALID_CERTIFICATE   30514

#define STATUS_FAIL_TO_UPDATE_GK										30520
#define STATUS_FAIL_TO_CHANGE_CS_LOG_MODE								30521


#define STATUS_ILLEGAL_IN_MPM_MODE				 						30522
#define STATUS_ILLEGAL_IN_MPM_PLUS_MODE			 						30523
#define STATUS_ILLEGAL_IN_FIXED_MPM_PLUS_MODE		 					30524
#define STATUS_ILLEGAL_IN_NOT_FIXED_MPM_PLUS_MODE	 					30525
#define STATUS_ILLEGAL_PORTS_CONFIGURATION		 						30526
#define STATUS_PORTS_CONFIGURATION_DOES_NOT_USE_FULL_SYSTEM_CAPACITY	30527
#define STATUS_SYSTEM_BUSY_SETTING_LAST_CONFIGURATION	 				30528
#define STATUS_SYSTEM_SHOULD_BE_RESET									30529
#define DEFAULT_PROFILE_CANNOT_BE_DELETED                               30530
#define STATUS_MAX_CONF_TEMPLATES_EXCEEDED                              30531
#define STATUS_CONF_TEMPLATE_NAME_ALREADY_EXISTS                        30532


#define STATUS_NUM_OF_AUDIO_PARTIES_EXCEEDS_MIN_AUDIO_PARTIES                 30533
#define STATUS_NUM_OF_VIDEO_PARTIES_EXCEEDS_MIN_VIDEO_PARTIES                 30534
#define STATUS_NUM_OF_PARTIES_EXCEEDS_MIN_VIDEO_PLUS_AUDIO_PARTIES            30535
#define STATUS_CONFERENCE_CAN_NOT_BE_SAVED_AS_TEMPLATE                        30536
#define STATUS_ILLEGAL_WHILE_ONGOING_CONFERENCE_EXISTS						  30537
#define STATUS_NUMBER_OF_MAX_PARTIES_EXCEEDED                                 30538
#define STATUS_CURRENT_SLIDER_SETTINGS_REQUIRES_MORE_RESOURCES_THAN_AVAILBLE  30539
#define STATUS_MIN_AUDIO_PARTIES_EXCEEDS_MAX_PARTIES_PER_CONF                 30540
#define STATUS_MIN_VIDEO_PARTIES_EXCEEDS_MAX_VIDEO_PARTIES_PER_CONF           30541
#define STATUS_MIN_VIDEO_PLUS_AUDIO_PARTIES_EXCEEDS_MAX_PARTIES_PER_CONF      30542
#define STATUS_ONLY_ONE_ACCOUT_PER_ROLE_ALLOWED				      30543
#define STATUS_ACCOUNT_AUTHORIZATION_LEVEL_NOT_ALLOWED			  30544

//operators configuration status
#define  STATUS_ILLEGAL_CHARACTERS_IN_LOGIN_NAME						30550
#define  STATUS_ILLEGAL_CHARACTERS_IN_PASSWORD							30551
#define  STATUS_PASSWORD_CANNOT_BE_CHANGED_YET							30553
#define  STATUS_INVALID_STRONG_PASSWORD									30554
#define  STATUS_INVALID_JITC_STRONG_PASSWORD							30555
#define  STATUS_EMPTY_PASSWORD                                          30556
#define  STATUS_PASSWORD_LENGTH_IS_TOO_SHORT							30558
#define  STATUS_ACCOUNT_DISABLED										30559
#define  STATUS_FORCE_CHANGE_PASSWORD									30560
#define  STATUS_SYSTEM_SESSION_LIMIT_EXCEEDED							30561
#define  STATUS_USER_SESSION_LIMIT_EXCEEDED							    30562
#define  STATUS_LAST_ENABLED_SUPERVISOR_OPERATOR_IN_MCU					30563
#define  STATUS_ACCOUNT_LOCKED											30564

#define  STATUS_SIP_TLS_NOT_SUPPORTED_IN_JITC_MODE                      30570

#define STATUS_MOVE_VSW_VSW_IS_FORBIDDEN                                      30571
#define STATUS_MOVE_CP_VSW_IS_FORBIDDEN                                       30572
#define STATUS_MOVE_ENC_NON_ENC_IS_FORBIDDEN                                  30573
#define STATUS_MOVE_TELEPRESENCE_NON_TELEPRESENCE_IS_FORBIDDEN                30574
#define STATUS_MOVE_CASCADED_LINK_IS_FORBIDDEN                                30575
#define STATUS_MOVE_IP_LPR_NON_LPR_IS_FORBIDDEN                               30576
#define STATUS_PARTY_ILLEGAL_STATE_FOR_MOVE                                   30577
#define STATUS_MAX_PARTIES_OF_DESTINATION_CONF_EXCEEDED                       30578
#define STATUS_MAX_VIDEO_PARTIES_OF_DESTINATION_CONF_EXCEEDED                 30579

// operator conf
#define STATUS_ILLEGAL_OPERATOR_CONFERENCE_NOT_LOGIN_NAME         30580
#define STATUS_ILLEGAL_OPERATOR_CONFERENCE_WRONG_NUM_OF_PARTIES   30581
//#define STATUS_ILLEGAL_OPERATOR_CONFERENCE_AUTO_TERMINATE         30582
//#define STATUS_ILLEGAL_OPERATOR_CONFERENCE_VSW                    30583
#define STATUS_ILLEGAL_OPERATOR_CONFERENCE_ALREADY_EXIST          30584
#define STATUS_ILLEGAL_HOME_CONF_NOT_FOUND                        30585
#define STATUS_ILLEGAL_HOME_CONF_EQ                               30586
#define STATUS_ILLEGAL_OPERATOR_CONF_NOT_FOUND                    30587
#define STATUS_ILLEGAL_MOVE_DEST_CONF_NOT_FOUND                   30588
#define STATUS_ILLEGAL_MOVE_PARTY_NOT_FOUND                       30589
#define STATUS_ILLEGAL_DEST_CONF_EQ                               30590
#define STATUS_MOVE_DIFFERENT_COP_CONFIG                          30591
#define STATUS_ILLEGAL_MOVE_TIP_PARTY		                      30592
#define STATUS_MEDIA_RECORDING_FOLDER_EXCEEDED_MAX_SIZE           30593

// operator conf

// GW dial out protocols
#define STATUS_ALL_DIAL_OUT_PROTOCOS_OK							  30600
#define STATUS_ILLEGAL_DIAL_OUT_PROTOCOL_H323					  30601 //(STATUS_ALL_DIAL_OUT_PROTOCOS_OK | GW_H323_OUT)
#define STATUS_ILLEGAL_DIAL_OUT_PROTOCOL_SIP					  30602 //(STATUS_ALL_DIAL_OUT_PROTOCOS_OK | GW_SIP_OUT )
#define STATUS_ILLEGAL_DIAL_OUT_PROTOCOL_H323_SIP				  30603 //(STATUS_ALL_DIAL_OUT_PROTOCOS_OK | GW_H323_OUT | GW_SIP_OUT)
#define STATUS_ILLEGAL_DIAL_OUT_PROTOCOL_ISDN					  30604 //(STATUS_ALL_DIAL_OUT_PROTOCOS_OK | GW_H320_OUT )
#define STATUS_ILLEGAL_DIAL_OUT_PROTOCOL_H323_ISDN				  30605 //(STATUS_ALL_DIAL_OUT_PROTOCOS_OK | GW_H320_OUT | GW_H323_OUT)
#define STATUS_ILLEGAL_DIAL_OUT_PROTOCOL_SIP_ISDN				  30606 //(STATUS_ALL_DIAL_OUT_PROTOCOS_OK | GW_H320_OUT | GW_SIP_OUT )
#define STATUS_ILLEGAL_DIAL_OUT_PROTOCOL_H323_SIP_ISDN            30607 //(STATUS_ALL_DIAL_OUT_PROTOCOS_OK | GW_H323_OUT | GW_SIP_OUT | GW_H320_OUT)r

#define STATUS_RESPONSE_TOO_LONG 								  30700

// Exchange Module statuses 31001 - 31500
#define  STATUS_EXCHANGE_BAD_PARAMETERS					31001
#define  STATUS_EXCHANGE_USERNAME_EMPTY					31002
#define  STATUS_EXCHANGE_PASSWORD_EMPTY					31003
#define  STATUS_EXCHANGE_WEB_URL_EMPTY					31004
#define  STATUS_EXCHANGE_WEB_URL_ILLEGAL				31005
#define  STATUS_EXCHANGE_FAILED_CONNECTING_TO_EXCHANGE	31006
#define  STATUS_EXCHANGE_DOMAIN_EMPTY					31007

// From v4.6 31501 - 32000
#define STATUS_COP_LEVELS_IDENTICAL                     31501
#define STATUS_COP_LEVEL_HIGHER_THAN_PREVIOUS           31502
#define STATUS_COP_LEVEL_LOW_BIT_RATE                   31503
#define STATUS_COP_LEVEL_INVALID_VIDEO_PROTOCOL         31504
#define STATUS_COP_LEVEL_PARAMS_HIGHER_THAN_MAX_PARAMS  31505

//failover
#define STATUS_ILLEGAL_WHILE_ONGOING_CONFERENCE_AND_RESERVATIONS_EXISTS	    31600
#define STATUS_ONGOING_CONFERENCE_AND_RESERVATIONS_EXISTS		    31601
//#define STATUS_START_MASTER_WHILE_RESERVATIONS_EXISTS			    31603

#define STATUS_EMPTY_USER_NAME_IN_ICE_ENVIRONMENT					31605

// High Profile
#define STATUS_VIDEO_PREVIEW_NOT_SUPPORTED_WITH_HIGH_PROFILE        31620
#define STATUS_H261_H263_NOT_SUPPORTED_WITH_HIGH_PROFILE            31621


//Multiple Services
#define STATUS_PORT_IS_ALREADY_OCCUPIED_BY_ANOTHER_SERVICE			31630
#define STATUS_IPV6_ALREADY_DEFINED_DIFFERENTLY_IN_ANOTHER_SERVICE  31631
#define STATUS_IPV4_ALREADY_DEFINED_THE_SAME_IN_ANOTHER_SERVICE		31632
#define STATUS_VIDEO_PREVIEW_DISABLED        					31633

//V35 GW
#define STATUS_V35_GATEWAY_IS_ALREADY_CONFIGURED_IN_ANOTHER_SERVICE	31640
#define STATUS_MAX_NUM_OF_PORTS_EXCEEDED							31641
#define STATUS_V35_SERVICE_IS_NEEDED						 		31642
#define STATUS_V35_MUST_BE_DEFINED_IN_THE_FIRST_PORT				31643

//Collector
#define STATUS_COLLECTING_ALREADY_IN_PROGRESS						31650
#define STATUS_COLLECTOR_IS_NOT_ACTIVE_AT_THE_MOMENT				31651
#define STATUS_ABORT_COLLECTOR_ALREADY_STARTED						31652

// 1500Q HD license
#define STATUS_1500Q_NO_CP_HD_LICENSE								31653

// Ldap module (Active Directory) statuses 32001 - 32100
///#define  STATUS_DIRECTORY_TYPE_EMPTY						32001
#define  STATUS_DIRECTORY_TYPE_INCORRECT					32002
#define  STATUS_DIRECTORY_NAME_ADDRESS_EMPTY				32003
///#define  STATUS_DIRECTORY_PORT_EMPTY						32004
#define  STATUS_DIRECTORY_PORT_INCORRECT					32005
#define	 STATUS_BASE_DN_EMPTY								32006
#define  STATUS_BASE_DN_INCORRECT							32007
///#define  STATUS_AUTHENTICATION_TYPE_EMPTY				32008
#define  STATUS_AUTHENTICATION_TYPE_INCORRECT				32009
#define  STATUS_ALL_DIR_AUTHORIZATION_GROUPS_ARE_EMPTY		32010
#define  STATUS_LDAP_CONFIGURATION_UPDATE_FAILED			32011
#define  STATUS_ACTIVE_DIRECTORY_SERVER_IS_NOT_AVAILABLE	32012
#define	 STATUS_ACCOUNT_AUTHORIZATION_LEVEL_NOT_ALLOWED_LDAP 32013
#define  STATUS_ONLY_ONE_ACCOUNT_IS_ALLOWED_IN_JITC_LDAP	32014
#define  STATUS_INVALID_SECURE_MODE_IN_JITC_LDAP			32015

// Extrenal DB application - returned status
#define STATUS_EXT_APP_STATUS_OK						     32016
#define STATUS_EXT_APP_ILLEGAL_MCU_USER_NAME_OR_PASSWORD     32017
#define STATUS_EXT_APP_REQUEST_TIMEOUT			             32018
#define STATUS_EXT_APP_ILLEGAL_NUMERIC_ID					 32019
#define STATUS_EXT_APP_ILLEGAL_CLI					         32020
#define STATUS_EXT_APP_ILLEGAL_CLI_OR_NUMERIC_ID	         32021
#define STATUS_EXT_APP_INTERNAL_ERROR				         32022
#define STATUS_EXT_APP_ILLEGAL_USER_ID				         32023
#define STATUS_EXT_APP_ILLEGAL_USER_NAME_OR_PASSWORD		 32024

#define STATUS_CFG_PARAM_CANT_REMOVE_ULTRA_SECURED_MODE		 32100


//Content Transcoding
#define STATUS_CONTENT_XCODE_NOT_SUPPORTED							32101
#define STATUS_VSW_CONTENT_XCODE_CONFLICT							32102
#define STATUS_CONTENT_XCODE_ONLY_SUPPORTED_FOR_CP					32103

//CDR
#define STATUS_FAILED_REGISTER_TO_CDR_SERVER					32201
#define STATUS_AT_LEAST_ONE_CDR_SERVICE							32202

// NotificationManager statuses: 32501-32599
//#define STATUS_OK                                             0;
#define STATUS_NOTIF_INTERNAL_ERROR                         32501
#define STATUS_NOTIF_ID_GENERATION_FAILED                   32502
#define STATUS_NOTIF_SUBSCRIPTION_NOT_FOUND                 32503
#define STATUS_NOTIF_RESOURCE_NOT_SUPPORTED                 32504
#define STATUS_NOTIF_MAXIMAL_SUBSCRIPTIONS_NUMBER_REACHED   32505

// SVC and SVC-AVC Mix conference media type
#define STATUS_ILLEGAL_CONFERENCE_MEDIA_TYPE				32550
#define STATUS_EQ_NOT_ALLOWED_IN_MEDIA_RELAY_CONF           32551
#define STATUS_ILLEGAL_DEST_CONF_MEDIA_RELAY				32552
#define STATUS_ILLEGAL_H320_PARTY_IN_MEDIA_RELAY_CONF		32553
#define STATUS_CANNOT_ADD_DIAL_OUT_PARTY_TO_MEDIA_RELAY_CONF 32554
#define STATUS_CANNOT_ADD_H323_PARTY_TO_MEDIA_RELAY_CONF    32555
#define STATUS_SVC_CONFERENCE_NOT_SUPPORTED_BY_LICENSING    32556

// TIP Compatibility mode
#define STATUS_TIP_COMPATIBILITY_NOT_SUPPORTED_IN_VSW					32600
#define STATUS_GATHERING_NOT_SUPPORTED_IN_TIP_COMPATIBILITY_MODE		32601
#define STATUS_MESSAGE_OVERLAY_NOT_SUPPORTED_IN_TIP_COMPATIBILITY_MODE	32602
#define STATUS_SITE_NAMES_NOT_SUPPORTED_IN_TIP_COMPATIBILITY_MODE		32603
#define STATUS_LEGACY_CONTENT_NOT_SUPPORTED_IN_TIP_COMPATIBILITY_MODE	32604
#define STATUS_TIP_COMPATIBILITY_NOT_SUPPORTED_BY_LICENSING				32605

#define STATUS_INVALIDE_OR_EXPIRED_LICENSING							32606

#define STATUS_IPV6_MTU_SIZE_MUST_NO_LESS_THAN_1280                     32607

#define STATUS_CFG_PARAM_NUM_OF_PCM_APPLICABLE_MPMX_ONLY                32608

#define STATUS_INVALID_MFW_SNMP_CONFIGURATION					32609

//New statuses: Range 30201-59999 - the same range to all the processes
//Dont add status with higher value then 59999!! (higher values belong to internal statuses)

#endif /*__API_STATUSES_H_*/
