// FaultsDefines.h
// Error Statuses & Fault Types

#ifndef __FAULTS_DEFS_H_
#define __FAULTS_DEFS_H_

#define MAX_FAULT_ID	1000000
#define FAULT_DESCRIPTION_LENGTH 400

// error levels
enum ErrorLevelsEnum
{
	STARTUP_ERROR_LEVEL = 0,
//	MINOR_ERROR_LEVEL = 1,
	MAJOR_ERROR_LEVEL = 2,
	SYSTEM_MESSAGE = 3,
};

// faults subjects types
enum FaultSubjectsEnum
{
	FAULT_STARTUP_SUBJECT = 0,
	FAULT_ASSERT_SUBJECT = 1,
	FAULT_FILE_SUBJECT = 2,
	FAULT_CARD_SUBJECT = 3,
	FAULT_RESERVATION_SUBJECT = 4,
	FAULT_CONFERENCE_SUBJECT = 5,
	FAULT_GENERAL_SUBJECT = 6,
	FAULT_EXCEPTION_SUBJECT = 7,
	FAULT_MEETING_ROOM_SUBJECT = 8,
	FAULT_DONGLE_SUBJECT = 9,
	FAULT_UNIT_SUBJECT = 10,
	FAULT_MPL_SUBJECT = 11,
};

#define PROCESS_COLLECTOR				(BYTE)eProcessCollector
//MCU files
#define VERSION_CONFIGURATION       0
#define CARDS_CONFIGURATION         1
#define NETWORK_CONFIGURATION       2
#define OPERATORS_CONFIGURATION     3
#define SYSTEM_CONFIGURATION        4
#define LOGGING                     5
#define RESERVATION_DATABASE        6
#define MESSAGE_CONFIGURATION       7
#define MEETING_ROOM_DATABASE       8
#define PROFILES_DATABASE		    9
#define REC_LINK__DATABASE		    10

//Card's Units types
#define UNIT_TYPE_PARTICIPANT		0
#define UNIT_TYPE_BRIDGE			1
#define UNIT_TYPE_CONTROLLER		2
#define UNIT_TYPE_ART				3
#define UNIT_TYPE_VIDEO				4
#define UNIT_TYPE_PQ				5
#define UNIT_TYPE_SMART				6


//Faults' types
#define FAULT_TYPE_ILLEGAL		0
#define FAULT_TYPE_MPM			1
#define FAULT_TYPE_SWITCH		2
#define FAULT_TYPE_ART			3
#define FAULT_TYPE_VIDEO		4
#define FAULT_TYPE_PQ			5
#define FAULT_TYPE_MCMS_CPU		6
#define FAULT_TYPE_FAN			7
#define FAULT_TYPE_PWR_SPLY		8
#define FAULT_TYPE_LAN			9
#define FAULT_TYPE_BACKPLANE	10
#define FAULT_TYPE_ART_CNTRLR	11
#define FAULT_TYPE_IAM			12
#define FAULT_TYPE_FSM4000		13
#define FAULT_TYPE_RTM_LAN		14


//Error codes for logging
#define MCU_RESTART                0
#define SOFTWARE_ASSERT_FAILURE    1000
//#define EXCEPTION_HANDLER_MESSAGE  1001

//Files faults
#define FILE_NOT_EXIST             1100
//#define EMPTY_FILE                 1101
//#define INCONSISTENT_INFO_IN_FILE  1103
//#define NO_ACCESS_TO_FILE          1104


//reservations faults
#define RESERVED_CONFER_HAS_NO_SUFFICIENT_RESOURCES     1200
#define START_TIME_OF_RESERVED_CONFER_IS_OVER           1201
//#define RESERVED_MEETING_ROOM_HAS_NO_SUFFICIENT_PHONES  1202


//conferences faults
//#define CONFERENCE_HAS_NO_SUFFICIENT_RESOURCES  1500
//#define END_TIME_OF_ON_GOING_CONF_IS_OVER       1501
//#define CARD_IS_IN_SIMULATOR_MODE               2000
#define ACK_FAILED                              2004
#define ACK_NOT_RECEIVED                        2005
#define ILLEGAL_CONFERENCE_PARAMETERS       2006
#define INVALID_OPCODE_RESPONSE             2007
#define INSUFFICIENT_EVENT_MODE_CONFERENCE_RESOURCES 	2008
#define CONFERENCE_END_DUE_TO_RESOURCE_DEFICIENCY     	2009
#define CALL_END_DUE_TO_ICE_CONNECTIVITY_CHECK_FAILURE   2010
#define CALL_END_DUE_TO_ICE_INSUFFICIENT_BANDWIDTH   2011



//Card and component error codes  (for operator display)
//#define CARD_STARTUP_NOT_IN_TIME                    2051
//#define CARD_TYPE_NOT_EXIST_IN_CONFIG               2052
//#define UNEXPECTED_HARDWARE_VERSION                 2053
//#define CARD_SOFTWARE_FILE_NOT_EXIST                2054
//#define UNEXPECTED_CARD_TYPE                        2055
//#define SLOT_IS_EMPTY                               2056
//#define UNEXPECTED_EMPTY_SLOT                       2057
//#define NETWORK_SERVICE_ERROR                       2058
//#define CCOM_FATAL_ERROR                            2060
//#define NO_DUAL_SLOT_MASTER_VIDEO_CARD              2061
//#define NO_DUAL_SLOT_SLAVE_VIDEO_CARD               2062
//#define MESSAGE_TRANSMISSION_PROBLEM                2063
//#define MESSAGE_DOWNLOAD_HARDWARE_PROBLEM           2064
//#define NOT_ATTENDED_HARDWARE_VERSION               2065
//#define ATM_LINK_DOWN                               2066
//#define ATM_CONNECTION_DOWN                         2067
//#define ATM_ILMI_REGISTERED_DOWN                    2068
//#define LINE_PM_ERROR                               2069
//#define H323_LAN_CONNECTION_DOWN                    2070
//#define H323_LAN_CONTROLLER_DOWN                    2071
//#define ATM_STATUS_NOT_LOAD                         2072
//#define VIDEO_HIGH_BIT_RATE_NOT_SUPPORTED_BY_CARD   2073
//#define VIDEO_HIGH_FRAME_RATE_NOT_SUPPORTED_BY_CARD 2074
//#define LARGE_CONF_NOT_SUPPORTED_BY_CARD            2075
//#define NET_CARD_STARTUP_PROBLEM                    2076
//#define H323_LAN_LINK_STATUS_DOWN                   2077
//#define H323_LAN_LINK_STATUS_NEGOTIATING            2078
//#define AUDIO_ALGORITHM_NOT_SUPPORTED_BY_CARD       2079
//#define FAULTY_UNIT_RECOVERED                       2080
#define CARD_MANAGER_RECONNECT						2081
#define CARD_MANAGER_DISCONNECT						2082



//#define H323_LAN_LINK_STATUS_OK_ATM_DISABLE               2100
//#define H323_LAN_LINK_STATUS_DOWN_ATM_DISABLE             2101
//#define H323_LAN_LINK_STATUS_NEGOTIATING_ATM_DISABLE      2102
//#define H323_LAN_LINK_STATUS_OK_ATM_DISCONNECTED          2103
//#define H323_LAN_LINK_STATUS_DOWN_ATM_DISCONNECTED        2104
//#define H323_LAN_LINK_STATUS_NEGOTIATING_ATM_DISCONNECTED 2105
//#define H323_LAN_LINK_STATUS_DOWN_ATM_CONNECTED           2106
//#define H323_LAN_LINK_STATUS_NEGOTIATING_ATM_CONNECTED    2107
//#define H323_LAN_LINK_STATUS_NEGOTIATING_ATM_NULL         2108
//#define H323_LAN_LINK_STATUS_DOWN_ATM_NULL                2109

//#define H323_LAN_LINK_STATUS_DUPLICATE_IP_ATM_DISABLE         2110
//#define H323_LAN_LINK_STATUS_DUPLICATE_IP_ATM_DISCONNECTED    2111
//#define H323_LAN_LINK_STATUS_DULPICATE_IP_ATM_CONNECTED       2112
//#define H323_LAN_LINK_STATUS_DUPLICATE_IP_ATM_NULL            2113

//SIP Error levels
//#define IP_CARD_STATUS_FAULTY_SECTION_ERROR                   2114
//
//// new IP card errors
//#define IP_CARD_STATUS_DHCP_SERVER_TIMEOUT                    2115
//#define IP_CARD_STATUS_NAT_AUTODISCOVERY_FAIL                 2116
//#define IP_CARD_STATUS_DNS_SERVER_TIMEOUT                     2117
//#define IP_CARD_STATUS_DNS_SERVER_IP_NOT_PROVIDED             2118
//#define IP_CARD_STATUS_SIP_PROXY_IP_NOT_PROVIDED              2119
//#define IP_CARD_STATUS_NOT_PROVIDED                           2120
//#define IP_CARD_STATUS_ADDRESS_CHANGED                        2121

//general faults
//#define RESET_MCU_BY_OPERATOR                        3002
//#define LOW_MEMORY_ALERT                             3003
//#define NO_AUDIO_MESSAGE_IN_CONFIGURATION            3004
//#define NO_MUSIC_IN_CONFIGURATION                    3005
//#define EMPTY_PERFORMANCE_MONITORING_TRASH_HOLD      3006
//#define GATE_KEEPER_ERROR                            3007 // moved to AA_GATE_KEEPER_ERROR in ActiveAlarms range
#define BAD_SPONTANEOUS_INDICATION                   3008
#define DIFFERENT_DECODED_TS_IN_VARIOUS_AUDIO_PLUS_HARDWARE_VERSIONS     3009
//#define ILLEGAL_CONFIGURATION_FILE__PLEASE_CONTACT_SUPPORT               3010
//#define INSUFFICIENT_TDM_ALERT                                           3011
#define GATEKEEPER_MESSAGE                                               3012
//#define UNSUITABLE_AUDIO_PLUS_CONF_FREQUENCY_SETTING_TO_SUPPORT_SIREN_14 3013
//#define UNSUITABLE_MUSIC_SETTING_TO_SUPPORT_SINGLE_PARTY_HEARS_MUSIC     3014
//#define UNSUITABLE_PASSWORD_LENGTH_CONFIGURATION     3015
//#define RESET_MCU_ON_EXCEPTION                       3016
//#define RESET_MCU_ON_CARD_FAILURE                    3017
//#define RESET_MCU_ON_LOW_MEMORY                      3018
//#define FAN_1_FAILURE                                3019
//#define FAN_2_FAILURE                                3020
//#define HIGH_TEMPERATURE                             3021
//#define POWER_SUPPLY_FAILURE                         3022
//#define LCD_FAILURE                                  3023
//#define DONGLE_FAILURE                               3024
//#define WRONG_DONGLE_ATTACHED                        3025
//#define DONGLE_NOT_ATTACHED                          3026
//#define DONGLE_ERROR                                 3027
//#define EMPTY_DONGLE                                 3028
//#define VERSION_DOESNT_MATCH                         3029
//#define UNSUITABLE_CONFERENCE_ID_RANGE_CONFIGURATION 3030
#define APPLICATION_SERVER_INTERNAL_ERROR			 3032
//#define FAILED_TO_LOAD_XML_SCHEMAS					 3033
//#define PASSWORDS_CONFLICT__PLEASE_SEE_pscnflct_log_FILE_FOR_DETAILS     3034
//#define CAN_NOT_ESTABLISH_CONNECTION_WITH_SIP_REGISTRAR					 3035
//#define CONNECTION_ERROR                             3036




//-----------------------------------------------------------------------
// New Faults
//-----------------------------------------------------------------------


// General
#define INTERNAL_MCU_RESET                           4000
#define XML_PARSE_ERROR								 4001
#define SOCKET_DISCONNECT							 4003
#define SOCKET_RECONNECT							 4004
#define EXTERNAL_FAULT	                             4005 // fault from external source (as Embedded)
#define CANT_STORE_DATA	                             4006
#define INTERNAL_ICPA_EVENT                          4007



// Cards
#define FATAL_CARD_FAILURE							 4020
#define EXTERNAL_FAULT_EMB                           4021


// Apache
#define	APACHE_MODULE_EXCEPTION						 4040
#define	FAILED_TO_RECEIVE_SYNC_MESSAGE				 4041
#define	FAILED_TO_SEND_SYNC_MESSAGE					 4042


// Daemon
#define	PROCESS_FAILED								 4060
#define	TASK_FAILED									 4061
#define	WILD_RESET_IND  							 4062

// SNMP
#define	SNMPD_FAILURE								 4080

// McuMngr
#define EXTERNAL_NTP_SERVER_FAILURE					4100

//RtmIsdnMngr
#define	ISDN_SPAN_ATTACHED_TO_NONEXISTING_SERVICE	4110
#define	INCONSISTENT_SPAN_TYPE						4111
#define	NUM_OF_CONFIGURED_SPANS_EXCEEDED			4112

// CDR errors
#define CDR_FILE_REACH_MAX_CAPACITY	  			    4120

#define EXTERNAL_FAULT_CS                           4150

#define SESSION_TIMER_FAULT                           4200

//-----------------------------------------------------------------------
// Alerts only
//-----------------------------------------------------------------------

enum ActiveAlarmsEnum
{
	AA_RANGE_FIRST = 5000,

	// General alerts
	AA_NO_LICENSING = 5001,
	AA_NO_MEETING_ROOM = 5002, NO_MEETING_ROOM = AA_NO_MEETING_ROOM,
	AA_NO_IP_SERVICE_PARAMS = 5003,
	AA_TASK_TERMINATED = 5004, TASK_TERMINATED = AA_TASK_TERMINATED,
	AA_CFG_CHANGED = 5005, CFG_CHANGED = AA_CFG_CHANGED,
	AA_CFG_INVALID = 5006, CFG_INVALID = AA_CFG_INVALID,
	AA_DEBUG_MODE = 5007, DEBUG_MODE = AA_DEBUG_MODE,
	AA_LOW_PROCESS_MEMORY_ALERT = 5008, LOW_PROCESS_MEMORY_ALERT = AA_LOW_PROCESS_MEMORY_ALERT,
	AA_LOW_SYSTEM_MEMORY_ALERT = 5009, LOW_SYSTEM_MEMORY_ALERT = AA_LOW_SYSTEM_MEMORY_ALERT,
	AA_SYSTEM_CPU_USAGE_ALERT = 5010, SYSTEM_CPU_USAGE_ALERT = AA_SYSTEM_CPU_USAGE_ALERT,
	AA_TEST_ERROR = 5011, TEST_ERROR = AA_TEST_ERROR,
	AA_SIP_SECURED_COMMUNICATION_FAILED = 5012,
	AA_BAD_FILE = 5013,
	AA_HIGH_CPU_USAGE_PROCESS_ALERT = 5014, HIGH_CPU_USAGE_PROCESS_ALERT = AA_HIGH_CPU_USAGE_PROCESS_ALERT,
	AA_LOW_SYSTEM_DISK_SPACE = 5015, LOW_SYSTEM_DISK_SPACE = AA_LOW_SYSTEM_DISK_SPACE,

	// Infrastructure faults
	AA_IDLE_DEADLINE_REACHED = 5016, IDLE_DEADLINE_REACHED = AA_IDLE_DEADLINE_REACHED,
	AA_STARTUP_CONDITION_CONFIGURATION = 5017, STARTUP_CONDITION_CONFIGURATION = AA_STARTUP_CONDITION_CONFIGURATION,
	AA_RESTORING_DEFAULT_FACTORY = 5018, RESTORING_DEFAULT_FACTORY = AA_RESTORING_DEFAULT_FACTORY,
	AA_IP_VERSION_CHANGED = 5019, IP_VERSION_CHANGED = AA_IP_VERSION_CHANGED,

	// CSMngr alerts
	AA_NO_SERVICE_FOUND_IN_DB = 5050, NO_SERVICE_FOUND_IN_DB = AA_NO_SERVICE_FOUND_IN_DB,
	AA_NO_CONNECTION_WITH_CS = 5052, NO_CONNECTION_WITH_CS = AA_NO_CONNECTION_WITH_CS,
	AA_CS_COMPONENT_FATAL = 5053, CS_COMPONENT_FATAL = AA_CS_COMPONENT_FATAL,
	AA_CS_NOT_CONFIGURED = 5054, CS_NOT_CONFIGURED = AA_CS_NOT_CONFIGURED,
	AA_CS_SERVICE_STATE_FAIL = 5055, CS_SERVICE_STATE_FAIL = AA_CS_SERVICE_STATE_FAIL,
	AA_CS_STARTUP_FAILED = 5056, CS_STARTUP_FAILED = AA_CS_STARTUP_FAILED,
	AA_DUPLICATE_IP_CS_MNGMNT = 5058, DUPLICATE_IP_CS_MNGMNT = AA_DUPLICATE_IP_CS_MNGMNT,
	AA_IP_SERVICE_DELETED = 5059, IP_SERVICE_DELETED = AA_IP_SERVICE_DELETED,
	AA_IP_SERVICE_CHANGED = 5060, IP_SERVICE_CHANGED = AA_IP_SERVICE_CHANGED,
	AA_CS_RECOVERY_STATUS = 5061, CS_RECOVERY_STATUS = AA_CS_RECOVERY_STATUS,
	AA_EXTERNAL_ALERT_CS = 5062,
	AA_IP_SERVICE_ADDED = 5063, IP_SERVICE_ADDED = AA_IP_SERVICE_ADDED,
	AA_CS_IP_NOT_CONFIGURED = 5064, CS_IP_NOT_CONFIGURED = AA_CS_IP_NOT_CONFIGURED,
	AA_NETWORK_INTERFACE_IS_NOT_CONFIGURED = 5065, NETWORK_INTERFACE_IS_NOT_CONFIGURED = AA_NETWORK_INTERFACE_IS_NOT_CONFIGURED,
	AA_CS_IP_IS_ZERO = 5066, CS_IP_IS_ZERO = AA_CS_IP_IS_ZERO,
	
	// McuMngr alerts
	AA_PRODUCT_ACTIVATION_FAILURE = 5100,
	AA_NO_MANAGEMENT_IP_INTERFACE = 5101,
	AA_NO_TIME_CONFIGURATION = 5102,
	AA_MPL_STARTUP_FAILURE_AUTHENTICATION_NOT_RECEIVED = 5103,
	AA_MPL_STARTUP_FAILURE_MNGMNT_IP_CNFG_NOT_RECEIVED = 5104,
	AA_NO_DNS_CONFIGURATION = 5105,
	AA_DNS_REGISTRAION_FAILED = 5106,
	AA_FAILED_TO_OPEN_APACHE_CONFIGURATION_FILE = 5107,
	AA_FAILED_TO_SAVE_APACHE_CONFIGURATION_FILE = 5108,
	AA_PATCHED_VERSION = 5109,
	AA_PRIVATE_VERSION = 5110,
	AA_NTP_SYNC_FAILURE = 5111,
	AA_ILLEGAL_TIME = 5112,
	AA_EXTERNAL_NTP_SERVERS_FAILURE = 5113,
	AA_RUNNING_VERSION_MISMATCHES_CURRENT_VERSION = 5114,
	AA_IDE_NOT_IN_DMA_MODE = 5115,
	AA_BAD_ETHERNET_SETTINGS = 5116,
	AA_SMART_REPORT_ERRORS_ON_HD = 5117,
	AA_ILLEGAL_MCU_VERSION = 5118,
	AA_DEBUG_CFG_EXIST = 5119, DEBUG_CFG_EXIST = AA_DEBUG_CFG_EXIST,
	AA_INSTALLING_NEW_VERSION = 5120,
	AA_SSH_ENABLED = 5121,
	AA_PRODUCT_TYPE_MISMATCH = 5127,
	AA_UNKNOWN_CPU_SLOT_ID = 5128,
	AA_AA_NO_FIPS_140_TEST_RESULT_FROM_ENCRYPTIONKEYSERVER = 5129, AA_NO_FIPS_140_TEST_RESULT_FROM_ENCRYPTIONKEYSERVER = AA_AA_NO_FIPS_140_TEST_RESULT_FROM_ENCRYPTIONKEYSERVER,
	AA_AA_FIPS_140_FAILURE_WITHIN_ENCRYPTIONKEYSERVER = 5130, AA_FIPS_140_FAILURE_WITHIN_ENCRYPTIONKEYSERVER = AA_AA_FIPS_140_FAILURE_WITHIN_ENCRYPTIONKEYSERVER,
	AA_HTTPS_DISABLED_IN_JITC = 5131,
	AA_EVENT_MODE_RESOURCE_DEFICIENCY_DUE_TO_WRONG_LICENSE = 5132,
	AA_LICENSE_EXPIRED = 5133,

	AA_FAN_MAJOR_PROBLEM = 5134,
	AA_FAN_CRITICAL_PROBLEM = 5135,
	AA_PWR_MAJOR_PROBLEM = 5136,
	AA_PWR_CRITICAL_PROBLEM = 5137,

	AA_TEMPERATURE_CRITICAL_SHUTDOWN = 5138, TEMPERATURE_CRITICAL_SHUTDOWN = AA_TEMPERATURE_CRITICAL_SHUTDOWN,
	AA_NO_SYSTEM_IP_YET = 5139,
	
	// CDR alerts
	AA_BACKUP_OF_CDR_FILES_IS_REQUIRED = 5140, BACKUP_OF_CDR_FILES_IS_REQUIRED = AA_BACKUP_OF_CDR_FILES_IS_REQUIRED,
	AA_CDR_SERVER_CONNECTION_DOWN = 5141,
	AA_CDR_CHECK_CONNECTION_TO_CDR_SERVER = 5142,
	AA_CDR_INFORMATION_TO_CDR_SERVER_LOST  = 5143,
	AA_FAIL_TO_REGISTER_TO_CDR_SERVER = 5144, FAIL_TO_REGISTER_TO_CDR_SERVER = AA_FAIL_TO_REGISTER_TO_CDR_SERVER,

	// Cards alerts
	AA_NO_MUSIC_SOURCE = 5150,
	AA_SWITCH_NOT_LOADED = 5151,
	AA_NO_ISDN_SERVICE_PARAMS = 5152,
	AA_MODULE_DOES_NOT_EXIST = 5153, MODULE_DOES_NOT_EXIST = AA_MODULE_DOES_NOT_EXIST,
	AA_NO_DEFAULT_ISDN_SERVICE = 5154,
	AA_EXTERNAL_ALERT_EMB = 5155,
	AA_VERSION_INSTALL_PROGRESS = 5156,
	AA_VERSION_IPMC_INSTALL_PROGRESS = 5157,

    //MFW startup with invalid configuration
    AA_LAST_CONFIGURED_NETWORK_INTERFACE_IS_INVALID = 5158, LAST_CONFIGURED_NETWORK_INTERFACE_IS_INVALID = AA_LAST_CONFIGURED_NETWORK_INTERFACE_IS_INVALID,

	// Switch KeepAlive components problems
	AA_VOLTAGE_PROBLEM = 5200,
	AA_TEMPERATURE_MAJOR_PROBLEM = 5201,
	AA_TEMPERATURE_CRITICAL_PROBLEM = 5202,
	AA_FAILURE_PROBLEM = 5203,
	AA_POWER_OFF_PROBLEM = 5204,
	AA_OTHER_PROBLEM = 5205,

	AA_NO_CONNECTION_WITH_CARD = 5206,
	AA_UNIT_NOT_RESPONDING = 5207,
	AA_MEDIA_IP_CONFIGURATION_FAILURE = 5208,
	AA_CARD_FOLDER_MOUNTING_FAILED = 5209,
	AA_CARD_STARTUP_FAILURE = 5211,
	AA_RTM_ISDN_STARTUP_FAILURE = 5212,
	AA_RTM_ISDN_STARTUP_PROBLEM = 5213,
	AA_NO_CONNECTION_WITH_RTM_ISDN = 5214,
	AA_RED_ALARM = 5215,
	AA_YELLOW_ALARM = 5216,
	AA_D_CHANNEL_NOT_ESTABLISHED = 5217,
	AA_CARDS_CONFIG_EVENT = 5218,
	AA_CARDS_WRONG_FILE_MODE = 5219,
	AA_CARDS_FLASH_ACCESS_PROBLEM = 5220,
	AA_RTM_LAN_OR_ISDN_MISSING = 5221,
    AA_NO_LAN_CONNECTION_PORT_1   =                      5222,
    AA_NO_LAN_CONNECTION_PORT_2   =                      5223,
    AA_NO_LAN_CONNECTION_PORT_3   =                      5224,
      AA_NO_LAN_CONNECTION_PORT_4   =                    5225,
	// MplApi alerts
//	AA_NO_CONTROL_IP_INTERFACE = 5250, NO_CONTROL_IP_INTERFACE = AA_NO_CONTROL_IP_INTERFACE,

	//SipProxy alerts
	AA_CAN_NOT_ESTABLISH_CONNECTION_WITH_SIP_REGISTRAR = 5300,
	AA_SIP_REGISTRATION_LIMIT_REACHED = 5301, SIP_REGISTRATION_LIMIT_REACHED = AA_SIP_REGISTRATION_LIMIT_REACHED,
	AA_FAILED_TO_SUBSCRIBE_WITH_THE_OCS = 5302,
	AA_RECEIVED_NOTIFICATION_FAILED = 5303,
	AA_SERVICE_REQ_FAILED = 5304,
	AA_INITIALIZE_ICE_STACK_FAILURE = 5305,
	AA_REGISTER_ICE_USER_FAILED = 5306,
	AA_RESOLVE_ICE_SERVER_NAME_FAILED = 5307,
	AA_REGISTER_FAILED_FOR_SOME_CONF = 5308, //Added for BRIDGE-4977
	AA_WEBRTC_ICE_SERVER_FAILED = 5309,

	//DNSAgent alerts
	AA_FAILED_TO_ACCESS_DNS_SERVER = 5350, FAILED_TO_ACCESS_DNS_SERVER = AA_FAILED_TO_ACCESS_DNS_SERVER,
	AA_NO_IND_DNS_SUCCESS = 5351, NO_IND_DNS_SUCCESS = AA_NO_IND_DNS_SUCCESS,

	//Logger alerts
	AA_FAILED_TO_INIT_FILE_SYSTEM = 5400, FAILED_TO_INIT_FILE_SYSTEM = AA_FAILED_TO_INIT_FILE_SYSTEM,
	AA_BAD_FILE_SYSTEM = 5401, BAD_FILE_SYSTEM = AA_BAD_FILE_SYSTEM,
	AA_BAD_HARD_DISK = 5402, BAD_HARD_DISK = AA_BAD_HARD_DISK,
	AA_BACKUP_OF_LOG_FILES_IS_REQUIRED = 5403, BACKUP_OF_LOG_FILES_IS_REQUIRED = AA_BACKUP_OF_LOG_FILES_IS_REQUIRED,
	AA_LOG_IS_DISABLED_BY_SYSTEM_LOAD = 5404, LOG_IS_DISABLED_BY_SYSTEM_LOAD = AA_LOG_IS_DISABLED_BY_SYSTEM_LOAD,

	// Audit alerts
	AA_BACKUP_OF_AUDIT_FILES_IS_REQUIRED = 5430, BACKUP_OF_AUDIT_FILES_IS_REQUIRED = AA_BACKUP_OF_AUDIT_FILES_IS_REQUIRED,

	// Apache Module alerts
	AA_FAILED_TO_FILL_ACTION_REDIRECTION = 5450,
	AA_HTTPD_FAILED_USE_REVOCATION_METHOD = 5451,

	// Auth Module alerts
	AA_FAILED_CONFIG_USER_LIST_IN_LINUX = 5500, FAILED_CONFIG_USER_LIST_IN_LINUX = AA_FAILED_CONFIG_USER_LIST_IN_LINUX,

	// General Configuration alerts. Added when unifying  PORT_CONFIGURATION_CHANGED  AA_ISDN_SERVICES_CONFIGURATION_CHANGED IP_SERVICE_CHANGED alerts
	AA_SYSTEM_CONFIGURATION_CHANGED = 5520, SYSTEM_CONFIGURATION_CHANGED = AA_SYSTEM_CONFIGURATION_CHANGED,

	// Resource alerts
	AA_INSUFFICIENT_RESOURCES = 5550, INSUFFICIENT_RESOURCES = AA_INSUFFICIENT_RESOURCES,
	AA_PORT_CONFIGURATION_CHANGED = 5551, PORT_CONFIGURATION_CHANGED = AA_PORT_CONFIGURATION_CHANGED,
	AA_NO_UTILIZABLE_UNIT_FOR_AUDIO_CONTROLLER = 5552, NO_UTILIZABLE_UNIT_FOR_AUDIO_CONTROLLER = AA_NO_UTILIZABLE_UNIT_FOR_AUDIO_CONTROLLER,
	AA_ALLOCATION_MODE_CHANGED = 5553, ALLOCATION_MODE_CHANGED = AA_ALLOCATION_MODE_CHANGED,
	AA_PORT_GAUGE_THRESHOLD_REACHED = 5554, PORT_GAUGE_THRESHOLD_REACHED = AA_PORT_GAUGE_THRESHOLD_REACHED,
	AA_AUDIO_PORT_GAUGE_THRESHOLD_REACHED = 5555, AUDIO_PORT_GAUGE_THRESHOLD_REACHED = AA_AUDIO_PORT_GAUGE_THRESHOLD_REACHED,
	AA_VIDEO_PORT_GAUGE_THRESHOLD_REACHED = 5556, VIDEO_PORT_GAUGE_THRESHOLD_REACHED = AA_VIDEO_PORT_GAUGE_THRESHOLD_REACHED,

	// Daemon alerts
	AA_PROCESS_TERMINATED = 5601, PROCESS_TERMINATED = AA_PROCESS_TERMINATED,
	AA_RESET_MCU_BY_TERMINAL = 5602, RESET_MCU_BY_TERMINAL = AA_RESET_MCU_BY_TERMINAL,
	AA_RESET_MCU_BY_OPERATOR = 5603, RESET_MCU_BY_OPERATOR = AA_RESET_MCU_BY_OPERATOR,
	AA_RESET_MCU_INTERNAL = 5604, RESET_MCU_INTERNAL = AA_RESET_MCU_INTERNAL,
	AA_RESET_MCU = 5605, RESET_MCU = AA_RESET_MCU, // (by unknown source)
	AA_RESET_MCU_DIAGNOSTICS = 5606, RESET_MCU_DIAGNOSTICS = AA_RESET_MCU_DIAGNOSTICS,
	AA_PROCESS_STARTUP_FAILED = 5607, PROCESS_STARTUP_FAILED = AA_PROCESS_STARTUP_FAILED,
	AA_SYSTEM_IN_SAFE_MODE = 5608, SYSTEM_IN_SAFE_MODE = AA_SYSTEM_IN_SAFE_MODE,
	AA_GUI_SYSTEM_CONFIG_IS_ILLEGAL = 5609, GUI_SYSTEM_CONFIG_IS_ILLEGAL = AA_GUI_SYSTEM_CONFIG_IS_ILLEGAL,

	// SystemMonitoring alerts
	AA_FILE_SYSTEM_FAILED_TO_SCAN = 5650, FILE_SYSTEM_FAILED_TO_SCAN = AA_FILE_SYSTEM_FAILED_TO_SCAN,
	AA_FILE_SYSTEM_OVERFLOW = 5651, FILE_SYSTEM_OVERFLOW = AA_FILE_SYSTEM_OVERFLOW,
	AA_HARD_DISK_FAILURE = 5652, HARD_DISK_FAILURE = AA_HARD_DISK_FAILURE,
	AA_NON_JITC_BIOS_VERSION = 5653, NON_JITC_BIOS_VERSION = AA_NON_JITC_BIOS_VERSION,
	AA_HIGH_SCHEDULER_LATENCY = 5654,  HIGH_SCHEDULER_LATENCY = AA_HIGH_SCHEDULER_LATENCY,
	AA_CORE_FILE_DETECTED = 5655, CORE_FILE_DETECTED = AA_CORE_FILE_DETECTED,

	// IPMCInterfaceManager alaert
	AA_CPU_IPCM_SOFTWARE_IS_NOT_UPDATED = 5690, CPU_IPCM_SOFTWARE_IS_NOT_UPDATED = AA_CPU_IPCM_SOFTWARE_IS_NOT_UPDATED,

	// Installer alerts
	AA_NEW_VERSION_INSTALLED = 5700, NEW_VERSION_INSTALLED = AA_NEW_VERSION_INSTALLED,
	AA_NEW_ACTIVATION_KEY_LOADED = 5701, NEW_ACTIVATION_KEY_LOADED = AA_NEW_ACTIVATION_KEY_LOADED,
	AA_SAFE_UPGRADE_OFF = 5702,
	AA_ACTIVATION_KEY_IS_NEEDED = 5703, ACTIVATION_KEY_IS_NEEDED = AA_ACTIVATION_KEY_IS_NEEDED,
	AA_UPGRADE_RECEIVE_VERSION = 5704, UPGRADE_RECEIVE_VERSION = AA_UPGRADE_RECEIVE_VERSION,
	AA_SHA1_VERSION = 5705, SHA1_VERSION = AA_SHA1_VERSION,
	AA_FPGA_CHECK_FAILED = 5706, FPGA_CHECK_FAILED = AA_FPGA_CHECK_FAILED,
	AA_FPGA_STARTUP_BURNING = 5707, FPGA_STARTUP_BURNING = AA_FPGA_STARTUP_BURNING,
	AA_NEW_VERSION_DOWNGRADE_FAILED = 5708, NEW_VERSION_DOWNGRADE_FAILED = AA_NEW_VERSION_DOWNGRADE_FAILED,

	// CSApi alerts
	// AA_CS_CSAPI_DISCONNECT = 5750, CS_CSAPI_DISCONNECT = AA_CS_CSAPI_DISCONNECT,
	AA_INSUFFICIENT_UDP_PORTS = 5751, INSUFFICIENT_UDP_PORTS = AA_INSUFFICIENT_UDP_PORTS,

	// Authentication errors
	AA_USERS_LIST_CORRUPTED = 5800,
	AA_DEFAULT_USER_EXISTS = 5801,
	AA_SUPPORT_OPERATOR_ILLEGAL_IN_FEDERAL_MODE = 5802,
	AA_MACHINE_ACCOUNT_EXPIRATION_ALERT = 5803,

	// RtmIsdnMngr errors
	AA_ISDN_SERVICES_CONFIGURATION_CHANGED = 5900,
	AA_NO_ISDN_PSTN_LICENSING = 5901,
	AA_NO_RTM_ISDN_CARD = 5902,
	AA_NO_CLOCK_SOURCE = 5903,
	AA_SINGLE_CLOCK_SOURCE = 5904,

	// GKManager errors
	AA_GKMNGR_AVF_WRONG_MCU_CONFIG = 5950, GKMNGR_AVF_WRONG_MCU_CONFIG = AA_GKMNGR_AVF_WRONG_MCU_CONFIG,
	AA_GATE_KEEPER_ERROR = 5951,

	// QAApi errors
	AA_CAN_NOT_ESTABLISH_CONNECTION_WITH_APPLICATION_SERVER = 6000,
	AA_SYSTEM_CONFIGURATION = 6001,
	AA_EXTERNAL_DB_CERTIFICATE_ERROR = 6002,

	// ConfParty errors
	AA_IVR_SERVICE_LIST_MISSING_DEFAULT_SERVICE = 6050,
	AA_CAN_NOT_CREATE_DEFAULT_PROFILE = 6051,
	AA_NO_READ_MR_DB_REQ_RECIEVED_FROM_RSRC = 6052,
	AA_FAILED_TO_CONNECT_RECORDING_LINK = 6053,
	AA_RECORDING_LINK_DISCONNECED_UNEXPECTEDLY = 6054,
	AA_SYSTEM_BASED_MODE_NOT_INTIALIZED = 6055,
	AA_CONF_ENCRYPTION_ERROR = 6056,
	AA_COP_MODE_NOT_SUPPORTED_MPM_PLUS_MODE = 6057,

	// Snmp alerts
	AA_SNMP_AGENT_INIT_FAILED = 6100, SNMP_AGENT_INIT_FAILED = AA_SNMP_AGENT_INIT_FAILED,

	// BackupRestore alerts
	AA_RESTORE_SUCCEEDED = 6200,
	AA_RESTORE_FAILED = 6201,

	// CSMngr errors
	AA_SIP_FORBIDDEN_TRANSPORT_TYPE_IN_JITC_MODE = 7000, SIP_FORBIDDEN_TRANSPORT_TYPE_IN_JITC_MODE = AA_SIP_FORBIDDEN_TRANSPORT_TYPE_IN_JITC_MODE,

	// Encryption Server Errors
	AA_ENCRYPTION_SERVER_ERROR = 7010,

	// ExchangeModule alarms
	AA_EXCHANGE_SERVER_CONNECTION_ERROR = 7050,

	// Failover alerts
	AA_HOT_BACKUP_PAIR_MCU_IS_UNREACHABLE = 8200,
	AA_HOT_BACKUP_MASTER_SLAVE_CONFIGURATION_CONFLICT = 8201,
	AA_HOT_BACKUP_NETWORK_ISSUE = 8202,

	// LDAP Module alerts
	AA_LDAP_FAILED_TO_CONNECT_TO_ACTIVE_DIRECTORY_SERVER = 8500,
	AA_INVALID_LDAP_MODULE_CONFIGURATION = 8501,
	AA_INVALID_LOCAL_USER_ACCOUNT_LIST_FOR_LDAP = 8502,
	AA_LDAP_FAILED_TO_CONNECT_TO_OCSP_SERVER = 8503,

	// CertMngr
	AA_FAILED_TO_VALIDATE_CERTIFICATE = 8650,
	AA_CERTIFICATE_EXPIRED = 8651,
	AA_CERTIFICATE_COMMON_NAME_ERROR = 8652,
	AA_CERTIFICATE_NOT_VALID_YET = 8653,
	AA_CERTIFICATE_GOING_TO_BE_EXPIRED = 8654,
	AA_CERTIFICATE_REPOSITORY_NOT_UPDATED = 8655,
	AA_CERTIFICATE_FOR_CS_NEED_RESET_TO_TAKE_EFFECT = 8656,
	AA_CERTIFICATE_SELF_CERT_NOT_ALLOWED_FOR_MS_SERVICE = 8657,

	// Utility active alarms
	AA_UTILITY_NETWORK_TRAFFIC_CAPTURE_ON = 8700,

	// MCCFMngr
	AA_MCCF_CHANNEL_IS_NOT_CONNECTED = 8750,

       //added by Richer for Video Recovery project om 2013.12.26
       AA_VIDEO_RECOVERY= 8751, VIDEO_RECOVERY = AA_VIDEO_RECOVERY,
	//McuMngr
	AA_LICENSE_ACQUISITION_FAIL = 8800,
	AA_LICENSE_WAS_MODIFIED     = 8801,

	// Last
	AA_RANGE_LAST = 10000,
};

#endif  // __FAULTS_DEFS_H_
