#ifndef __INTERNAL_PROCESS_STATUSES_H_
#define __INTERNAL_PROCESS_STATUSES_H_

typedef int ESTATUS;

//New statuses: Range 70000 - 99999
#define STATUS_FW_REQUEST_TO_RESOURCE						70000
#define STATUS_WAIT_FOR_AN_ANSWER_FROM_EXTERNAL_DB			70001

#define STATUS_SOCKET_TIMEOUT      							70002
#define STATUS_NEW_CONNECTION      							70003
#define STATUS_PRIVATE_FD          							70004

//Sip Proxy statuses
#define STATUS_UNKNOWN_SIP_REGISTRAR_STATUS					70005

#define STATUS_CONFERENCE_ALREADY_EXISTS					70006
#define STATUS_INSUFFICIENT_RSRC_CONF_ID					70007
#define STATUS_SPREADING_TIMER_OUT							70008
#define STATUS_CONFERENCE_NOT_EXISTS						70009
#define STATUS_NOT_ALL_PARTIES_DELETED						70010
#define STATUS_CONF_RSRC_STATE_MACH_NOT_FOUND				70011
#define STATUS_ALLOC_REQ_WITHOUT_SPREAD_FOR_NON_EQ_CONF		70012
#define STATUS_PARTY_ALREADY_EXISTS							70013
#define STATUS_INSUFFICIENT_RSRC_PARTY_ID					70014
#define STATUS_INSUFFICIENT_RSRC_CONNECTION_ID				70015
#define STATUS_INSUFFICIENT_RTM_RSRC						70016
#define STATUS_INSUFFICIENT_ART_RSRC						70017
#define STATUS_INSUFFICIENT_VIDEO_RSRC						70018
#define STATUS_INSUFFICIENT_UDP_PORTS						70019
#define STATUS_RTM_SERVICE_NOT_FOUND						70020
#define STATUS_RTM_DEALLOCATION_FAIL						70021
#define STATUS_PARTY_NOT_EXISTS								70022
#define STATUS_ART_DEALLOCATION_FAIL						70023
#define STATUS_VIDEO_DEALLOCATION_FAIL						70024
#define STATUS_START_RSRC_PARTY_MOVE_FAIL					70025
#define STATUS_END_RSRC_PARTY_MOVE_FAIL						70026
#define STATUS_UPDATE_RSRC_DESC_FAIL						70027
#define STATUS_ALREADY_EXISTS								70028
#define STATUS_NUMERIC_CONFERENCE_ID_NOT_EXISTS				70029
#define STATUS_INVALID_MNTR_CONF_ID							70030
#define STATUS_UNKNOWN										70031
#define STATUS_INTERNAL_ERROR								70032
#define STATUS_INSUFFICIENT_ROOM_ID							70033
#define STATUS_SOCKET_WOULD_BLOCKED							70034
#define STATUS_NUMBER_OF_AUDIO_PARTIES_EXCEEDED 			70035
#define STATUS_NUMBER_OF_VIDEO_PARTIES_EXCEEDED     		70036
#define STATUS_NO_UTILIZABLE_UNIT_FOR_AUDIO_CONTROLLER 		70037
#define STATUS_INSUFFICIENT_CHANNEL_ID						70038
#define STATUS_INSUFFICIENT_BONDING_TEMPORARY_PHONE_NUMBERS 70039

 //network services status
#define  STATUS_NUMBER_OF_SERVICE_PROVIDERS_EXCEEDED						70040
#define STATUS_NUMBER_OF_SPANS_IN_SERVICE_EXCEEDED							70041
#define STATUS_IP_ADDRESS_IN_SPAN_NOT_VALID                           		70042
#define STATUS_IP_SPAN_IS_NOT_ON_THE_SAME_SUBNET_AS_THE_ROUTERS       		70043

//H323 services status
#define STATUS_NUMBER_OF_H323_SERVICES_EXCEEDED							 	70044
#define STATUS_H323_SERVICE_NAME_EXISTS									 	70045
#define STATUS_H323_SERVICE_NAME_NOT_EXISTS								 	70046
#define STATUS_NUMBER_OF_ROUTERS_IN_SERVICE_EXCEEDED						70048
#define STATUS_ROUTER_EXISTS                                                70049
#define STATUS_ROUTER_NOT_EXISTS                                            70050
#define STATUS_EMPTY_ALIAS_NAMES_LIST_IN_SPAN								70051
#define STATUS_IP_ROUTER_IS_NOT_ON_THE_SAME_SUBNET_AS_THE_OTHER_ROUTERS     70052
#define STATUS_IP_ROUTER_IS_NOT_ON_THE_SAME_SUBNET_AS_THE_SPANS				70053

//Port ranges  statuses
#define  STATUS_ILLEGAL_PORT_NUMBER_ABOVE_62999						  		70054
#define  STATUS_ILLEGAL_PORT_NUMBER_BELOW_1025						  		70055
#define  STATUS_ILLEGAL_RESERVED_PORT_IN_RANGE						  		70056
#define  STATUS_THE_NUMBER_OF_PORTS_ALLOCATED_IS_BELOW_THE_MINIMUM    		70057
#define  STATUS_INVALID_GATEKEEPER_ADDRESS                            		70058
#define  STATUS_PREFIX_MUST_BE_NUMERIC                                		70059
#define  STATUS_INVALID_GATEKEEPER_POLLING_INTERVAL                   		70060
//Port ranges  statuses
#define STATUS_ALIAS_NAMES_CANNOT_BEGIN_WITH_A_COMMA      	 				70061
#define STATUS_ALIAS_NAMES_CANNOT_INCLUDE_SEMICOLON       	 				70062
#define STATUS_ALIAS_NAMES_CANNOT_INCLUDE_QUOTATION_MARK  	 				70063
#define STATUS_ALIAS_E164_TYPE_NAMES_MUST_BE_NUMERIC      	 				70064
#define STATUS_ILLEGAL_VIDEO_PORT_ALLOCATION			   	 				70065
#define STATUS_ILLEGAL_AUDIO_PORT_ALLOCATION              	 				70066
#define STATUS_ILLEGAL_FECC_PORT_ALLOCATION			   		 				70067
#define STATUS_ILLEGAL_CONTENT_PORT_ALLOCATION                              70068

#define STATUS_UNKNOWN_CONFIGURATION_FOR_SIP_SERVERS		 				70069

#define STATUS_INVALID_NAT_IP_ADDRESS                              			70070
#define STATUS_UNKNOWN_NAT_STATUS                                  			70071
#define STATUS_UNKNOWN_DNS_STATUS                                  			70072
#define STATUS_INVALID_DNS_SERVER_ADDRESS                          			70073

#define  STATUS_INVALID_DNS_STATUS                                         	70074

#define  STATUS_AUTHENTICATION_SERVER_NAME_CANNOT_INCLUDE_SEMICOLON         70075
#define  STATUS_AUTHENTICATION_SERVER_NAME_CANNOT_INCLUDE_QUOTATION_MARK    70076
#define  STATUS_AUTHENTICATION_SERVER_PASS_NAME_CANNOT_INCLUDE_SEMICOLON    70077
#define  STATUS_AUTHENTICATION_SERVER_PASS_NAME_CANNOT_INCLUDE_QUOTATION_MARK   70078
#define  STATUS_INVALID_AUTHENTICATION_DIGEST_ELEMENT_NUMBER                    70079
#define  STATUS_INVALID_AUTHENTICATION_KERBEROS_ELEMENT_NUMBER                  70080

//incoming call STATUS
#define STATUS_UNKNOWN_SIP_ONGOING_CONFRENCES_STATUS		 				70081
#define STATUS_UNKNOWN_SIP_MEETING_ROOM_STATUS								70082
#define STATUS_UNKNOWN_SIP_ENTRY_QUEUES						 				70083
#define STATUS_UNKNOWN_SIP_ACCEPT_MEET_ME_STATUS			 				70084
#define STATUS_UNKNOWN_SIP_ACCEPT_AD_HOK_STATUS				 				70085
#define STATUS_UNKNOWN_SIP_ACCEPT_FACTORY_STATUS			 				70086
#define STATUS_UNKNOWN_SIP_REFRESH_STATUS					 				70087

//incoming call STATUS 
#define STATUS_AUTO_REGISTER_SPAN_HOST_NAME_CANNOT_BE_ENABLED	       		70088

#define STATUS_PARSING_XML_FILE_FAILED										70089
#define STATUS_OPEN_FILE_FAILED												70090
#define STATUS_WRITE_FILE_FAILED											70091
#define STATUS_DUMP_XML_DATA_AS_STRING_FAILED								70092
#define STATUS_UNKNOWN_FILE_FAILURE											70093
#define STATUS_FILE_NOT_EXIST												70094
#define STATUS_EXE_NOT_FOUND												70095
#define STATUS_WRONG_DATA_SIZE												70096

#define STATUS_INVALID_MAILBOX												70097
#define STATUS_RESPONSE_SEQ_NUMBER_IS_EMPTY									70098

#define STATUS_CLOSE_FILE_FAILED											70099

#define STATUS_FAILED_CFG_ROUTERS                                           70100
#define STATUS_FAILED_CFG_IP                                                70101
#define STATUS_FAILED_CFG_INTERFACE                                         70102
#define STATUS_FW_REQUEST_TO_CONFPARTY						                70103

#define STATUS_WAIT_FOR_RSRC_AND_ASK_AGAIN									70104
#define STATUS_INSUFFICIENT_ART_CHANNELS_RSRC								70105

#define STATUS_FW_REQUEST_TO_RESOURCE_MANGER								70106

#define STATUS_FAILED_CFG_IPV6_DEF_GW										70107
#define STATUS_RMX_PORT_GAUGE_THRESHOLD_EXCEEDED							70108

#define STATUS_UNZIP_XML_FILE_FAILED										70109

#define STATUS_LINK_FILE_FAILED                                             70110
#define STATUS_LINK_FILE_SUCCEEDED                                          70111


#define STATUS_MORE_THAN_ONE_USER_IN_LIST									70112
#define STATUS_USER_IS_NOT_ADMIN											70113

#define STATUS_AV_INITIAL_DAT_FILE											70114

#define STATUS_INSUFFICIENT_RSRC_CARD_OVERLOAD								70115

#endif /*__INTERNAL_PROCESS_STATUSES_H_*/
