#ifndef OPCODESMCMSRTMISDNMAINTENANCE_H_
#define OPCODESMCMSRTMISDNMAINTENANCE_H_



// =======================================
// ========= RTM_ISDN_MNGR range =========
// =======================================
//#define CARDS_RTM_ISDN_FIRST_OPCODE				5050000

//#define CARDS_RTM_ISDN_REQ_FIRST_OPCODE			5050001
#define RTM_ISDN_PARAMETERS_REQ						5050010	// RTM_ISDN_PARAMETERS_S
#define RTM_ISDN_SPAN_CONFIG_REQ					5050011	// RTM_ISDN_SPAN_CONFIG_REQ_S
#define RTM_ISDN_SPAN_DISABLE_REQ					5050012	// RTM_ISDN_SPAN_DISABLE_REQ_S
#define RTM_ISDN_KEEP_ALIVE_REQ						5050013
#define RTM_ISDN_VLAN_ID_REQ						5050014	// RTM_ISDN_VLAN_ID_S
//#define CARDS_RTM_ISDN_REQ_LAST_OPCODE			5054999

//#define CARDS_RTM_ISDN_IND_FIRST_OPCODE			5055000
#define RTM_ISDN_SPAN_STATUS_IND					5055010	// RTM_ISDN_SPAN_STATUS_IND_S
#define RTM_ISDN_KEEP_ALIVE_IND						5055011
//#define CARDS_RTM_ISDN_IND_LAST_OPCODE			5059998

//#define CARDS_RTM_ISDN_LAST_OPCODE				5059998



#endif /*OPCODESMCMSRTMISDNMAINTENANCE_H_*/
