#ifndef __ART_DEFINITIONS_H
#define __ART_DEFINITIONS_H

typedef enum
{
	E_NETWORK_TYPE_DUMMY,
	E_NETWORK_TYPE_IP,
	E_NETWORK_TYPE_ISDN,
	E_NETWORK_TYPE_PSTN_E1,
	E_NETWORK_TYPE_PSTN_T1,
	E_NETWORK_TYPE_LAST
} ENetworkType;


//FIPS 140
typedef enum{
	E_ART_FIPS140_SIMULATION_ERR_CODE_DUMMY,
	E_ART_FIPS140_SIMULATION_ERR_CODE_INACTIVE,
	E_ART_FIPS140_SIMULATION_ERR_CODE_FAIL_DETERMINISTIC_TEST,
	E_ART_FIPS140_SIMULATION_ERR_CODE_LAST
}EArtFips140SimulationErrCode;


typedef enum{
	E_FIPS_IND_STATUS_DUMMY,
	E_FIPS_IND_STATUS_OK,
	E_FIPS_IND_STATUS_ERROR_PRG_INIT_FAILURE,
	E_FIPS_IND_STATUS_ERROR_RANDOMIZATION_FAILURE,
	E_FIPS_IND_STATUS_ERROR_SAME_SEED_DIFFERENT_RES,
	E_FIPS_IND_STATUS_ERROR_SEED_VALUE_FAILURE,  
	E_FIPS_IND_STATUS_ERROR_SHA1_FAILURE,
	E_FIPS_IND_STATUS_ERROR_AES_FAILURE,
	E_FIPS_IND_STATUS_LAST
}EFipsIndStatusOpcodes;


#endif
