#ifndef SYS_CONFIG_KEYS_H_
#define SYS_CONFIG_KEYS_H_

///////////////////////////////////////////////////////////////////////////
#define CFG_KEY_ULTRA_SECURE_MODE "ULTRA_SECURE_MODE"

#define CFG_KEY_CIRCULAR_MAPPING_MODE_FOR_AUDIO_VIDEO_PLUS \
"CIRCULAR_MAPPING_MODE_FOR_AUDIO_VIDEO_PLUS"

#define CFG_KEY_ENHANCED_CAPACITY_PLUS_BOARDS_AND_NET \
"ENHANCED_CAPACITY_PLUS_BOARDS_AND_NET"

#define CFG_KEY_MAXIMUM_CONFRERNCE_BIT_RATE_CONFERENCE_TYPE \
"MAXIMUM_CONFRERNCE_BIT_RATE_CONFERENCE_TYPE"

#define CFG_KEY_WAIT_FOR_CHAIR_VIDEO_TYPE_OLD \
"WAIT_FOR_CHAIR_VIDEO_TYPE_OLD"

#define CFG_KEY_PRINT \
"PRINT"

#define CFG_KEY_BAUD_RATE \
"BAUD_RATE"

#define CFG_KEY_TRACE \
"TRACE"

#define CFG_KEY_RESET_CCOM_ON_FAILURE \
"RESET_CCOM_ON_FAILURE"

#define CFG_KEY_TRACE_LOGGER_APPLICATION \
"TRACE_LOGGER_APPLICATION"

#define CFG_KEY_TRACE_LOGGER_LEVEL \
"TRACE_LOGGER_LEVEL"

#define CFG_KEY_TRACE_LOGGER_MAX_FILE_SIZE \
"TRACE_LOGGER_MAX_FILE_SIZE"

#define CFG_KEY_TRACE_LOGGER_MAX_FILE_TIME_TO_LIVE \
"TRACE_LOGGER_MAX_FILE_TIME_TO_LIVE"

#define CFG_KEY_TRACE_LOGGER_MAX_NUM_OF_FILES \
"TRACE_LOGGER_MAX_NUM_OF_FILES"

#define CFG_KEY_CARD_STATUS_REQUEST \
"CARD_STATUS_REQUEST"

#define CFG_KEY_RESET_UNIT \
"RESET_UNIT"

#define CFG_KEY_RESET_CARD \
"RESET_CARD"

#define CFG_KEY_CARD_STARTUP_TIMEOUT \
"CARD_STARTUP_TIMEOUT"

#define CFG_KEY_CARD_STATUS_REQUEST_TIMEOUT \
"CARD_STATUS_REQUEST_TIMEOUT"

#define CFG_KEY_AUTO_VIDEO_PLUS_LOGGER \
"AUTO_VIDEO_PLUS_LOGGER"

#define CFG_KEY_PERIOD_TRACE \
"PERIOD_TRACE"

#define CFG_KEY_AUTO_IP_CARD_MONITOR \
"AUTO_IP_CARD_MONITOR"

#define CFG_KEY_RTP_SELF_RECOVERY \
"RTP_SELF_RECOVERY"

#define CFG_KEY_MAP_SELF_RECOVERY \
"MAP_SELF_RECOVERY"

#define CFG_KEY_EXT_ALARM \
"EXT_ALARM"

#define CFG_KEY_AUTO_PERFORMANCE_MONITORING \
"AUTO_PERFORMANCE_MONITORING"

#define CFG_KEY_PERFORMANCE_MONITORING_TIMEOUT \
"PERFORMANCE_MONITORING_TIMEOUT"

#define CFG_KEY_PM_COUNTER_ES \
"PM_COUNTER_ES"

#define CFG_KEY_PM_COUNTER_SES \
"PM_COUNTER_SES"

#define CFG_KEY_PM_COUNTER_SEFS \
"PM_COUNTER_SEFS"

#define CFG_KEY_PM_COUNTER_UAS \
"PM_COUNTER_UAS"

#define CFG_KEY_PM_COUNTER_CSS \
"PM_COUNTER_CSS"

#define CFG_KEY_PM_COUNTER_PCV \
"PM_COUNTER_PCV"

#define CFG_KEY_PM_COUNTER_LES \
"PM_COUNTER_LES"

#define CFG_KEY_PM_COUNTER_BES \
"PM_COUNTER_BES"

#define CFG_KEY_PM_COUNTER_DM \
"PM_COUNTER_DM"

#define CFG_KEY_PM_COUNTER_LCV \
"PM_COUNTER_LCV"

#define CFG_KEY_PSOS_NET_UTIL \
"PSOS_NET_UTIL"

#define CFG_KEY_FTP_LOGIN \
"FTP_LOGIN"

#define CFG_KEY_IPTERMINAL_LOGIN \
"IPTERMINAL_LOGIN"

#define CFG_KEY_ALLOW_ORDINARY_OPERATOR_TO_CHANGE_ITS_OWN_PASSWORD \
"ALLOW_ORDINARY_OPERATOR_TO_CHANGE_ITS_OWN_PASSWORD"

#define CFG_KEY_STOP_WHEN_ASSERT \
"STOP_WHEN_ASSERT"

#define CFG_KEY_RUN_DEBUGGER_WHEN_EXCEPT \
"RUN_DEBUGGER_WHEN_EXCEPT"

#define CFG_KEY_CREATE_DUMP_FILE_WHEN_EXCEPT \
"CREATE_DUMP_FILE_WHEN_EXCEPT"

#define CFG_KEY_SILENT_MODE \
"SILENT_MODE"

#define CFG_KEY_FTP \
"FTP"

#define CFG_KEY_REMOTE_DESKTOP \
"REMOTE_DESKTOP"

#define CFG_KEY_SNMP \
"SNMP"

#define CFG_KEY_SNMP_TRAP_LEVEL \
"SNMP_TRAP_LEVEL"

#define CFG_KEY_SNMP_TRAP_INTERVAL \
"SNMP_TRAP_INTERVAL"

#define CFG_KEY_SNMP_AGENTX_SOCKET \
"SNMP_AGENTX_SOCKET"

#define CFG_KEY_ISDN_COUNTRY_CODE \
"ISDN_COUNTRY_CODE"

#define CFG_KEY_ISDN_IDLE_CODE_T1 \
"ISDN_IDLE_CODE_T1"

#define CFG_KEY_ISDN_IDLE_CODE_E1 \
"ISDN_IDLE_CODE_E1"

#define CFG_KEY_ISDN_NUM_OF_DIGITS \
"ISDN_NUM_OF_DIGITS"

#define CFG_KEY_ISDN_CLOCK \
"ISDN_CLOCK"

#define CFG_KEY_ATM_CLOCK \
"ATM_CLOCK"

#define CFG_KEY_INTERNAL_CLOCK \
"INTERNAL_CLOCK"

#define CFG_KEY_MPI_CLOCK \
"MPI_CLOCK"

#define CFG_KEY_SYSTEM_NORMAL_WITH_SINGLE_CLOCK_SOURCE \
"SYSTEM_NORMAL_WITH_SINGLE_CLOCK_SOURCE"

#define CFG_KEY_CHANGE_IP_ADDRESS \
"CHANGE_IP_ADDRESS"

#define CFG_KEY_DRIVER_SMC \
"DRIVER_SMC"

#define CFG_KEY_WATCH_DOG \
"WATCH_DOG"

#define CFG_KEY_HW_WATCH_DOG \
"HW_WATCH_DOG"

#define CFG_KEY_SECURED_PORT_MANDATORY_FOR_API \
"SECURED_PORT_MANDATORY_FOR_API"

#define CFG_KEY_SECURED_PORT_MANDATORY_FOR_FILE \
"SECURED_PORT_MANDATORY_FOR_FILE"

#define CFG_KEY_DBC_2 \
"DBC_2"

#define CFG_KEY_IS_CDR_ON \
"IS_CDR_ON"

#define CFG_KEY_PRODUCT_TYPE \
"PRODUCT_TYPE"

#define CFG_KEY_H0 \
"H0"

#define CFG_KEY_ASSERT_MODE \
"ASSERT_MODE"

#define CFG_KEY_IGNORE_AIM \
"IGNORE_AIM"

#define CFG_KEY_HIGH_BIT_RATE \
"HIGH_BIT_RATE"

#define CFG_KEY_HIGH_VIDEO_FRAME_RATE \
"HIGH_VIDEO_FRAME_RATE"

#define CFG_KEY_MAX_AUDIO_PLUS_PARTIES_NUMBER_IN_MCU \
"MAX_AUDIO_PLUS_PARTIES_NUMBER_IN_MCU"

#define CFG_KEY_MAX_PARTIES_NUMBER_IN_AUDIO_CONF \
"MAX_PARTIES_NUMBER_IN_AUDIO_CONF"

#define CFG_KEY_MAX_PARTIES_NUMBER_IN_VIDEO_CONF \
"MAX_PARTIES_NUMBER_IN_VIDEO_CONF"

#define CFG_KEY_MCU_DISPLAY_NAME \
"MCU_DISPLAY_NAME"

#define CFG_KEY_ISDN_RESOURCE_POLICY \
"ISDN_RESOURCE_POLICY"

#define CFG_KEY_NUMERIC_CONF_ID_LEN \
"NUMERIC_CONF_ID_LEN"

#define CFG_KEY_NUMERIC_CONF_ID_MAX_LEN \
"NUMERIC_CONF_ID_MAX_LEN"

#define CFG_KEY_NUMERIC_CONF_ID_MIN_LEN \
"NUMERIC_CONF_ID_MIN_LEN"

//#define CFG_KEY_UNIT26_ALLOC_ENABLED
//"UNIT26_ALLOC_ENABLED"

#define CFG_KEY_IS_DOUBLE_DSP \
"IS_DOUBLE_DSP"

#define CFG_KEY_RESERVATION_CONFERENCE_ID_UNIQUE \
"RESERVATION_CONFERENCE_ID_UNIQUE"

#define CFG_KEY_PREFERRED_PORT \
"PREFERRED_PORT"

#define CFG_KEY_ENABLE_DTMF_VIA_GW \
"ENABLE_DTMF_VIA_GW"

#define CFG_KEY_DIFF_SERV_AUDIO \
"DIFF_SERV_AUDIO"

#define CFG_KEY_DIFF_SERV_VIDEO \
"DIFF_SERV_VIDEO"

#define CFG_KEY_IP_SET_ACTUAL_BITRATE_TO_FLOAT \
"IP_SET_ACTUAL_BITRATE_TO_FLOAT"

#define CFG_KEY_PARTY_MONITORING_REFRESH_PERIOD \
"PARTY_MONITORING_REFRESH_PERIOD"

#define CFG_KEY_IP_ENABLE_ROUNDTRIPDELAY \
"IP_ENABLE_ROUNDTRIPDELAY"

#define CFG_KEY_IP_UNEXPECTED_MESSAGE \
"IP_UNEXPECTED_MESSAGE"

#define CFG_KEY_SEND_RECAP_ATER_REALLOC_FOR_H323 \
"SEND_RECAP_ATER_REALLOC_FOR_H323"

#define CFG_KEY_IP_RV_TEST_APPLICATION \
"IP_RV_TEST_APPLICATION"

#define CFG_KEY_IP_PARTY_CONN_TIME_TILL_SIGNALING \
"IP_PARTY_CONN_TIME_TILL_SIGNALING"

#define CFG_KEY_CASCADE_TO_PREVIOUS_VERSION \
"CASCADE_TO_PREVIOUS_VERSION"

#define CFG_KEY_CP_REGARD_TO_INCOMING_SETUP_RATE \
"CP_REGARD_TO_INCOMING_SETUP_RATE"

#define CFG_KEY_SOFTWARE_CP \
"SOFTWARE_CP"

#define CFG_KEY_IGNORE_STREAM_VIOLATION \
"IGNORE_STREAM_VIOLATION"

#define CFG_KEY_IGNORE_STREAM_VIOLATION_IN_CHANGE_MODE \
"IGNORE_STREAM_VIOLATION_IN_CHANGE_MODE"

#define CFG_KEY_THRESHOLD_BITRATE \
"THRESHOLD_BITRATE"

#define CFG_KEY_THRESHOLD_FRACTION_LOSS \
"THRESHOLD_FRACTION_LOSS"

#define CFG_KEY_THRESHOLD_ACCUMULATE_PACKET_LOSS \
"THRESHOLD_ACCUMULATE_PACKET_LOSS"

#define CFG_KEY_THRESHOLD_INTERVAL_PACKET_LOSS \
"THRESHOLD_INTERVAL_PACKET_LOSS"

#define CFG_KEY_THRESHOLD_ACCUMULATE_OUT_OF_ORDER \
"THRESHOLD_ACCUMULATE_OUT_OF_ORDER"

#define CFG_KEY_THRESHOLD_INTERVAL_OUT_OF_ORDER \
"THRESHOLD_INTERVAL_OUT_OF_ORDER"

#define CFG_KEY_THRESHOLD_ACCUMULATE_FRAGMENTED \
"THRESHOLD_ACCUMULATE_FRAGMENTED"

#define CFG_KEY_THRESHOLD_INTERVAL_FRAGMENTED \
"THRESHOLD_INTERVAL_FRAGMENTED"

#define CFG_KEY_THRESHOLD_JITTER \
"THRESHOLD_JITTER"

#define CFG_KEY_THRESHOLD_LATENCY \
"THRESHOLD_LATENCY"

#define CFG_KEY_THRESHOLD_FRAME_RATE \
"THRESHOLD_FRAME_RATE"

#define CFG_KEY_ACTIVE_PROTECTION_NUMBERING \
"ACTIVE_PROTECTION_NUMBERING"

#define CFG_KEY_IP_LOAD_MNGR \
"IP_LOAD_MNGR"

#define CFG_KEY_H323_CALL_CONNECTED_LOAD \
"H323_CALL_CONNECTED_LOAD"

#define CFG_KEY_H245_CONNECT_LOAD \
"H245_CONNECT_LOAD"

#define CFG_KEY_IP_CHANNEL_CONNECT_LOAD \
"IP_CHANNEL_CONNECT_LOAD"

#define CFG_KEY_IP_CHANNEL_CLOSE_LOAD \
"IP_CHANNEL_CLOSE_LOAD"

#define CFG_KEY_H323_CALL_CLOSE_LOAD \
"H323_CALL_CLOSE_LOAD"

#define CFG_KEY_SIP_REGISTER_LOAD \
"SIP_REGISTER_LOAD"

#define CFG_KEY_SIP_INVITE_LOAD \
"SIP_INVITE_LOAD"

#define CFG_KEY_SIP_DEFAULT_LOAD \
"SIP_DEFAULT_LOAD"

#define CFG_KEY_SIP_SESSION_EXPIRES \
"SIP_SESSION_EXPIRES"

#define CFG_KEY_SIP_MIN_SEC \
"SIP_MIN_SEC"

#define CFG_KEY_IP_MONITORING_SHOW_FAULTY_MARK \
"IP_MONITORING_SHOW_FAULTY_MARK"

#define CFG_KEY_PREFIX_TYPE_IS_H323ID \
"PREFIX_TYPE_IS_H323ID"

#define CFG_KEY_ARQ_WHEN_CALL_IS_WITH_IP \
"ARQ_WHEN_CALL_IS_WITH_IP"

#define CFG_KEY_RRQ_WITHOUT_GRQ \
"RRQ_WITHOUT_GRQ"

#define CFG_KEY_MCU_REG_AS_320_GW \
"MCU_REG_AS_320_GW"

#define CFG_KEY_H323_ENABLE_CONFERENCE_DIALIN_IDENTIFY \
"H323_ENABLE_CONFERENCE_DIALIN_IDENTIFY"

#define CFG_KEY_IGNORE_BANDWIDTH_IN_BCF \
"IGNORE_BANDWIDTH_IN_BCF"

#define CFG_KEY_PATH_NAVIGATOR_OLD_VERSION_IN_ROUTED_MODE \
"PATH_NAVIGATOR_OLD_VERSION_IN_ROUTED_MODE"

#define CFG_KEY_REMOVE_G722_AND_GENERIC_AUDIO \
"REMOVE_G722_AND_GENERIC_AUDIO"

#define CFG_KEY_ENABLE_ALT_GK \
"ENABLE_ALT_GK"

#define CFG_KEY_IP_AUDIO_CONCEALMENT \
"IP_AUDIO_CONCEALMENT"

#define CFG_KEY_SIP_G711_FPP \
"SIP_G711_FPP"

#define CFG_KEY_IP_ENABLE_BACKGROUND_COLOR \
"IP_ENABLE_BACKGROUND_COLOR"

#define CFG_KEY_ENABLE_IP_SLIDE \
"ENABLE_IP_SLIDE"

#define CFG_KEY_IP_PACKETS_FRACTION_LOST \
"IP_PACKETS_FRACTION_LOST"

#define CFG_KEY_H323_INTERLACE_MODE \
"H323_INTERLACE_MODE"

#define CFG_KEY_H323_CHECK_ANNEX_D \
"H323_CHECK_ANNEX_D"

#define CFG_KEY_CHANGE_MODE_IN_VSW_FIXED \
"CHANGE_MODE_IN_VSW_FIXED"

#define CFG_KEY_RFC2833_DTMF \
"RFC2833_DTMF"

#define CFG_KEY_SIP_ENABLE_H264_FIXED \
"SIP_ENABLE_H264_FIXED"

#define CFG_KEY_SIP_CIF_IN_CP_FROM_RATE \
"SIP_CIF_IN_CP_FROM_RATE"

#define CFG_KEY_SIP_USER_AGENT_FLOW_CONTROL \
"SIP_USER_AGENT_FLOW_CONTROL"

#define CFG_KEY_SIP_USER_AGENT_FLOW_CONTROL_RATE \
"SIP_USER_AGENT_FLOW_CONTROL_RATE"

#define CFG_KEY_SIP_RESET_CHANNEL_ON_HOLD \
"SIP_RESET_CHANNEL_ON_HOLD"

#define CFG_KEY_SIP_REINVITE \
"SIP_REINVITE"

#define CFG_KEY_INITIATE_TIP_CONTENT_INTRA \
"INITIATE_TIP_CONTENT_INTRA"

#define CFG_KEY_SIP_FAST_UPDATE_INTERVAL_ENV \
"SIP_FAST_UPDATE_INTERVAL_ENV"

#define CFG_KEY_SIP_FAST_UPDATE_INTERVAL_EP \
"SIP_FAST_UPDATE_INTERVAL_EP"

#define CFG_KEY_SIP_MSG_TIMEOUT \
"SIP_MSG_TIMEOUT"

#define CFG_KEY_SIP_KEEPALIVE_SECOND_TIMEOUT \
"SIP_KEEPALIVE_SECOND_TIMEOUT"

#define CFG_KEY_SIP_IS_KEEPALIVE_ENABLE \
"SIP_IS_KEEPALIVE_ENABLE"

#define CFG_KEY_SIP_USER_AGENT_FPS_FIX \
"SIP_USER_AGENT_FPS_FIX"

#define CFG_KEY_SIP_FPS_FIX_TO \
"SIP_FPS_FIX_TO"

#define CFG_KEY_SIP_IMS \
"SIP_IMS"

#define CFG_KEY_SIP_PSI_SOURCE \
"SIP_PSI_SOURCE"

#define CFG_KEY_SIP_PSI_URI \
"SIP_PSI_URI"

#define CFG_KEY_SIP_ENABLE_FECC \
"SIP_ENABLE_FECC"

#define CFG_KEY_SIP_FLIP_INTRA_ENV \
"SIP_FLIP_INTRA_ENV"

#define CFG_KEY_SIP_FLIP_INTRA_EP \
"SIP_FLIP_INTRA_EP"

#define CFG_KEY_H245_TUNNELING \
"H245_TUNNELING"

#define CFG_KEY_START_HRTK \
"START_HRTK"

#define CFG_KEY_JITTER_BUF_SIZE \
"JITTER_BUF_SIZE"

#define CFG_KEY_STOP_PROCESSORS \
"STOP_PROCESSORS"

#define CFG_KEY_SIP_NORTEL_DEMO \
"SIP_NORTEL_DEMO"

#define CFG_KEY_SIP_VIDEO_DRAFT \
"SIP_VIDEO_DRAFT"

#define CFG_KEY_ENABLE_H323_PSTN \
"ENABLE_H323_PSTN"

#define CFG_KEY_USE_ISDN_NUMBER_FOR_H323_DIALING \
"USE_ISDN_NUMBER_FOR_H323_DIALING"

#define CFG_KEY_IP_MOBILE_PHONE_RATE \
"IP_MOBILE_PHONE_RATE"

#define CFG_KEY_IP_MOBILE_IDENTIFIER \
"IP_MOBILE_IDENTIFIER"

#define CFG_KEY_SIP_FREE_VIDEO_RESOURCES \
"SIP_FREE_VIDEO_RESOURCES"

#define CFG_KEY_ENABLE_IP_REDIAL_FOR_NOT_FINISH_CAPS_EXCHANGE \
"ENABLE_IP_REDIAL_FOR_NOT_FINISH_CAPS_EXCHANGE"

#define CFG_KEY_ENABLE_CONF_HIGH_CALL_RATE \
"ENABLE_CONF_HIGH_CALL_RATE"

#define CFG_KEY_SIP_CHANGE_AUDIO_CAPS_LIST_ACCORDING_TO_VENDOR \
"SIP_CHANGE_AUDIO_CAPS_LIST_ACCORDING_TO_VENDOR"

#define CFG_KEY_SIP_PRESERVE_ICE_CHANNEL_IN_CASE_OF_LOCAL_MODE \
"PRESERVE_ICE_CHANNEL_IN_CASE_OF_LOCAL_MODE"

#define CFG_KEY_SIP_ALWAYS_USE_PARTIAL_AUDIO_CAPS \
"SIP_ALWAYS_USE_PARTIAL_AUDIO_CAPS"

#define CFG_KEY_H323_FREE_VIDEO_RESOURCES \
"H323_FREE_VIDEO_RESOURCES"

#define CFG_KEY_SEARCH_FOR_H323_DEFINED_PARTY \
"SEARCH_FOR_H323_DEFINED_PARTY"

#define CFG_KEY_G729 \
"G729"

#define CFG_KEY_G722 \
"G722"

#define CFG_KEY_G728_ISDN \
"G728_ISDN"

#define CFG_KEY_G728_IP \
"G728_IP"

#define CFG_KEY_G7231 \
"G7231"

#define CFG_KEY_G722_1 \
"G722_1"

#define CFG_KEY_SIREN14 \
"SIREN14"

#define CFG_KEY_SIREN7 \
"SIREN7"

#define CFG_KEY_SIRENLPR \
"ENABLE_SIRENLPR"

#define CFG_KEY_SIRENLPRStereo \
"SIRENLPR_Stereo"

#define CFG_KEY_G722_1_320 \
"G722_1_320"

#define CFG_KEY_H320_G722 \
"H320_G722"

#define CFG_KEY_SIREN14_320 \
"SIREN14_320"

#define CFG_KEY_SIREN7_320 \
"SIREN7_320"

#define CFG_KEY_IP_H263 \
"IP_H263"

#define CFG_KEY_H263 \
"H263"

#define CFG_KEY_GW_H263 \
"GW_H263"

#define CFG_KEY_H263_ANNEX_F \
"H263_ANNEX_F"

#define CFG_KEY_H263_ANNEX_N \
"H263_ANNEX_N"

#define CFG_KEY_H263_ANNEX_T \
"H263_ANNEX_T"

#define CFG_KEY_H264_CONTENT_MBPS_VALUE \
"H264_CONTENT_MBPS_VALUE"

#define CFG_KEY_H263_ANNEX_P \
"H263_ANNEX_P"

#define CFG_KEY_H263_ANNEX_L \
"H263_ANNEX_L"

#define CFG_KEY_HIGHEST_COMMON_CUSTOM_FORMATS \
"HIGHEST_COMMON_CUSTOM_FORMATS"

#define CFG_KEY_H263_VGA_SVGA_XGA_NTSC \
"H263_VGA_SVGA_XGA_NTSC"

#define CFG_KEY_H263_4CIF \
"H263_4CIF"

#define CFG_KEY_H263_16CIF \
"H263_16CIF"

#define CFG_KEY_ENABLE_H460 \
"ENABLE_H460"

#define CFG_KEY_ALLOW_IN_VIDEO_FROM_IPVCR \
"ALLOW_IN_VIDEO_FROM_IPVCR"

#define CFG_KEY_DISABLE_GW_OVERLAY_INDICATION \
"DISABLE_GW_OVERLAY_INDICATION"

#define CFG_KEY_H320_VIDEOSWITCHING_VIDEOPROTOCOL_SELECTION_AUTOMODE_H263 \
"H320_VIDEOSWITCHING_VIDEOPROTOCOL_SELECTION_AUTOMODE_H263"

#define CFG_KEY_IP_VIDEOSWITCHING_VIDEOPROTOCOL_SELECTION_AUTOMODE_H263 \
"IP_VIDEOSWITCHING_VIDEOPROTOCOL_SELECTION_AUTOMODE_H263"

#define CFG_KEY_PROMOTION_FIELD_DROP \
"PROMOTION_FIELD_DROP"

#define CFG_KEY_LIMIT_AUTO_VSW_H263_FORMAT \
"LIMIT_AUTO_VSW_H263_FORMAT"

#define CFG_KEY_MIH \
"MIH"

#define CFG_KEY_CHAIR_CNTL \
"CHAIR_CNTL"

#define CFG_KEY_LSD4800 \
"LSD4800"

#define CFG_KEY_FECC_GW \
"FECC_GW"

#define CFG_KEY_FECC \
"FECC"

#define CFG_KEY_T120 \
"T120"

#define CFG_KEY_H323_T120 \
"H323_T120"

#define CFG_KEY_NUM_GCC_DATA_TRANSFER_PRIORITIES \
"NUM_GCC_DATA_TRANSFER_PRIORITIES"

#define CFG_KEY_GCC_PROTOCOL_VERSION \
"GCC_PROTOCOL_VERSION"

#define CFG_KEY_FREE_SERVICES \
"FREE_SERVICES"

#define CFG_KEY_VIRTUAL_CONFERENCE_SUITE \
"VIRTUAL_CONFERENCE_SUITE"

#define CFG_KEY_SCHEDULED_CONF \
"SCHEDULED_CONF"

#define CFG_KEY_3_WAY_MEETING_ROOM \
"3_WAY_MEETING_ROOM"

#define CFG_KEY_NUMBER_OF_RESERVATIONS \
"NUMBER_OF_RESERVATIONS"

#define CFG_KEY_GATEWAY \
"GATEWAY"

#define CFG_KEY_DELAY_BETWEEN_DIAL_OUT_PARTY \
"DELAY_BETWEEN_DIAL_OUT_PARTY"

#define CFG_KEY_CHANNEL_DELAY \
"CHANNEL_DELAY"

#define CFG_KEY_DELAY_BETWEEN_DIAL_OUT_AUDIO_PARTY \
"DELAY_BETWEEN_DIAL_OUT_AUDIO_PARTY"

#define CFG_KEY_ENABLE_IP_REDIAL \
"ENABLE_IP_REDIAL"

#define CFG_KEY_OFFER_SHORT_AUDIO_CODEC_LIST_AFTER_AUDIO_CALL_OFFERLESS_INVITE \
"OFFER_SHORT_AUDIO_CODEC_LIST_AFTER_AUDIO_CALL_OFFERLESS_INVITE"
//N.A. DEBUG VP8
#define CFG_KEY_ENABLE_WEBRTC_SUPPORT \
"ENABLE_WEBRTC_SUPPORT"

#define CFG_KEY_ENABLE_ISDN_REDIAL \
"ENABLE_ISDN_REDIAL"

#define CFG_KEY_REDIAL_INTERVAL_IN_SECONDS \
"REDIAL_INTERVAL_IN_SECONDS"

#define CFG_KEY_NUMBER_OF_REDIAL \
"NUMBER_OF_REDIAL"

#define CFG_KEY_HOT_BACKUP_REDIAL_INTERVAL_IN_SECONDS \
"HOT_BACKUP_REDIAL_INTERVAL_IN_SECONDS"

#define CFG_KEY_HOT_BACKUP_NUMBER_OF_REDIAL_ATTEMPTS \
"HOT_BACKUP_NUMBER_OF_REDIAL_ATTEMPTS"

#define CFG_KEY_HOT_BACKUP_FAILURE_DETECTION_IN_SECONDS \
"HOT_BACKUP_FAILURE_DETECTION_IN_SECONDS"

#define CFG_KEY_NET_PSTN_DELAY \
"NET_PSTN_DELAY"

#define CFG_KEY_NET_PSTN_DELAY2 \
"NET_PSTN_DELAY2"

#define CFG_KEY_NET_PSTN_DELAY3 \
"NET_PSTN_DELAY3"

#define CFG_KEY_NET_PSTN_CMD_ORDER \
"NET_PSTN_CMD_ORDER"

#define CFG_KEY_MESSAGE \
"MESSAGE"

#define CFG_KEY_MUSIC \
"MUSIC"

#define CFG_KEY_ENABLE_IVR_AUDIO \
"ENABLE_IVR_AUDIO"

#define CFG_KEY_ENABLE_IVR_VIDEO \
"ENABLE_IVR_VIDEO"

#define CFG_KEY_LEADER_RECOVERY_TIME \
"LEADER_RECOVERY_TIME"

#define CFG_KEY_TCS4_INFO \
"TCS4_INFO"

#define CFG_KEY_Q_A \
"Q&A"

#define CFG_KEY_LEADER_WAITING_TIME_OUT \
"LEADER_WAITING_TIME_OUT"

#define CFG_KEY_INVITE \
"INVITE"

#define CFG_KEY_VISUAL_NAME_CONVENTION \
"VISUAL_NAME_CONVENTION"

#define CFG_KEY_AUTOMATIC_ALLOCATION_OF_CONFERENCE_CHAIR_PASSWORD \
"AUTOMATIC_ALLOCATION_OF_CONFERENCE_CHAIR_PASSWORD"

#define CFG_KEY_VTX \
"VTX"

#define CFG_KEY_AUTO_AUDIO_PLUS_LOGGER \
"AUTO_AUDIO_PLUS_LOGGER"

#define CFG_KEY_AUTO_AUDIO_PLUS_LOGGER_ON_CARD_STARTUP \
"AUTO_AUDIO_PLUS_LOGGER_ON_CARD_STARTUP"

#define CFG_KEY_AUDIO_PLUS_YES_NO \
"AUDIO_PLUS_YES_NO"

#define CFG_KEY_AUDIO_PLUS_FREQUENCY \
"AUDIO_PLUS_FREQUENCY"

#define CFG_KEY_PDC_MODE \
"PDC_MODE"

#define CFG_KEY_MAXIMUM_AUDIO_PLUS_UNITS_NUMBER \
"MAXIMUM_AUDIO_PLUS_UNITS_NUMBER"

#define CFG_KEY_MUSIC_VOLUME_RATIO \
"MUSIC_VOLUME_RATIO"

//#define CFG_KEY_TERMINATE_CONF_AFTER_CHAIR_DROPPED
//"TERMINATE_CONF_AFTER_CHAIR_DROPPED"

#define CFG_KEY_ENABLE_CASCADED_LINK_TO_JOIN_WITHOUT_PASSWORD \
"ENABLE_CASCADED_LINK_TO_JOIN_WITHOUT_PASSWORD"

#define CFG_KEY_AUDIOP_TONE_GAIN \
"AUDIOP_TONE_GAIN"

#define CFG_KEY_AUDIO_PLUS_CM_FLASH_SIZE \
"AUDIO_PLUS_CM_FLASH_SIZE"

#define CFG_KEY_AUDIO_PLUS_CM_MSG_32 \
"AUDIO_PLUS_CM_MSG_32"

#define CFG_KEY_AUDIO_PLUS_CM_MSG_16 \
"AUDIO_PLUS_CM_MSG_16"

#define CFG_KEY_AUDIO_PLUS_CM_MSG_8 \
"AUDIO_PLUS_CM_MSG_8"

#define CFG_KEY_AUDIO_PLUS_CM_MSG_4 \
"AUDIO_PLUS_CM_MSG_4"

#define CFG_KEY_AUDIO_PLUS_CM_MSG_2 \
"AUDIO_PLUS_CM_MSG_2"

#define CFG_KEY_COP_SINGLE_LINE_RATE_THRESHOLD \
"COP_SINGLE_LINE_RATE_THRESHOLD"

#define CFG_KEY_COP_SINGLE_ENABLE_QCIF \
"COP_SINGLE_ENABLE_QCIF"

#define CFG_KEY_ENABLE_CLICK_AND_VIEW_SPLASH \
"ENABLE_CLICK_AND_VIEW_SPLASH"

#define CFG_KEY_ENABLE_VIDEOCOMMANDER \
"ENABLE_VIDEOCOMMANDER"

#define CFG_KEY_PARTY_NAME_ALWAYS_ON \
"PARTY_NAME_ALWAYS_ON"

#define CFG_KEY_DISPLAY_PARTY_NAME \
"DISPLAY_PARTY_NAME"

#define CFG_KEY_CP_4CIF \
"CP_4CIF"

#define CFG_KEY_4CIF_THRESHOLD \
"4CIF_THRESHOLD"

#define CFG_KEY_CP_HIGH_RES_GRAPHICS \
"CP_HIGH_RES_GRAPHICS"

#define CFG_KEY_PEOPLE_AND_CONTENT \
"PEOPLE_AND_CONTENT"

#define CFG_KEY_ENTERPRISE_PEOPLE_AND_CONTENT \
"ENTERPRISE_PEOPLE_AND_CONTENT"

#define CFG_KEY_ENABLE_IP_DUO_VIDEO \
"ENABLE_IP_DUO_VIDEO"

#define CFG_KEY_ENABLE_DUO_VIDEO \
"ENABLE_DUO_VIDEO"

#define CFG_KEY_ENABLE_VISUAL_CONCERT_PC \
"ENABLE_VISUAL_CONCERT_PC"

#define CFG_KEY_ENABLE_VISUAL_CONCERT_FX \
"ENABLE_VISUAL_CONCERT_FX"

#define CFG_KEY_CUSTOM_FORMATS_IN_H323_DUO_VIDEO \
"CUSTOM_FORMATS_IN_H323_DUO_VIDEO"

#define CFG_KEY_CIF_RESOLUTION_IN_H323_DUO_VIDEO \
"CIF_RESOLUTION_IN_H323_DUO_VIDEO"

#define CFG_KEY_H239 \
"H239"

#define CFG_KEY_GW_EPC_H239 \
"GW_EPC_H239"

#define CFG_KEY_T1CAS_WINKSTART_TIMER2 \
"T1CAS_WINKSTART_TIMER2"

#define CFG_KEY_DT_PARAMS \
"DT_PARAMS"

#define CFG_KEY_DT_CADENCE \
"DT_CADENCE"

#define CFG_KEY_B_PARAMS \
"B_PARAMS"

#define CFG_KEY_B_CADENCE \
"B_CADENCE"

#define CFG_KEY_FB_PARAMS \
"FB_PARAMS"

#define CFG_KEY_FB_CADENCE \
"FB_CADENCE"

#define CFG_KEY_ALLOW_T1_CAS_PARTICIPANTS_IN_VIDEO_CONFERENCES \
"ALLOW_T1_CAS_PARTICIPANTS_IN_VIDEO_CONFERENCES"

#define CFG_KEY_IDLE_CODE_T1_CAS \
"IDLE_CODE_T1_CAS"

#define CFG_KEY_T1CASDTMFTIMER1 \
"T1CASDTMFTIMER1"

#define CFG_KEY_T1CASDTMFTIMER2 \
"T1CASDTMFTIMER2"

#define CFG_KEY_AUTOMATICALLY_ALLOCATE_DIAL_IN_NUMBERS_IN_MEET_ME_CONFERENCES_FOR_T1_CAS_SERVICE \
"AUTOMATICALLY_ALLOCATE_DIAL-IN_NUMBERS_IN_MEET_ME_CONFERENCES_FOR_T1-CAS_SERVICE"

#define CFG_KEY_T1CAS_FORCE_ALAW \
"T1CAS_FORCE_ALAW"

#define CFG_KEY_T1CAS_PHONE_LEN \
"T1CAS_PHONE_LEN"

#define CFG_KEY_COUNTRY_CODE \
"COUNTRY_CODE"

#define CFG_KEY_IDLE_CODE_T1 \
"IDLE_CODE_T1"

#define CFG_KEY_IDLE_CODE_E1 \
"IDLE_CODE_E1"

#define CFG_KEY_NUMBER_OF_DIGITS \
"NUMBER_OF_DIGITS"

#define CFG_KEY_NET8_DEFAULT_TYPE \
"NET8_DEFAULT_TYPE"

#define CFG_KEY_SILENT_CHNL_TS \
"SILENT_CHNL_TS"

#define CFG_KEY_SILENT_CHNL_LINE \
"SILENT_CHNL_LINE"

#define CFG_KEY_MIN_TX_WINK \
"MIN_TX_WINK"

#define CFG_KEY_MAX_TX_WINK \
"MAX_TX_WINK"

#define CFG_KEY_SETTLING_TIME \
"SETTLING_TIME"

#define CFG_KEY_NO_ASNWER_TONE \
"NO_ASNWER_TONE"

#define CFG_KEY_MIN_RX_WINK \
"MIN_RX_WINK"

#define CFG_KEY_MAX_RX_WINK \
"MAX_RX_WINK"

#define CFG_KEY_PARTIAL_DIAL_TO \
"PARTIAL_DIAL_TO"

#define CFG_KEY_ENCRYPTION \
"ENCRYPTION"

#define CFG_KEY_ALLOW_NON_ENCRYPT_PARTY_IN_ENCRYPT_CONF \
"ALLOW_NON_ENCRYPT_PARTY_IN_ENCRYPT_CONF"

#define CFG_KEY_SIZE_OF_ENCRYPTION_KEY_DATABASE_FOR_POLYCOM \
"SIZE_OF_ENCRYPTION_KEY_DATABASE_FOR_POLYCOM"

#define CFG_KEY_SIZE_OF_ENCRYPTION_KEY_DATABASE_FOR_TANDBERG_IP \
"SIZE_OF_ENCRYPTION_KEY_DATABASE_FOR_TANDBERG_IP"

#define CFG_KEY_SIZE_OF_ENCRYPTION_KEY_DATABASE_FOR_TANDBERG_ISDN \
"SIZE_OF_ENCRYPTION_KEY_DATABASE_FOR_TANDBERG_ISDN"

#define CFG_KEY_H264 \
"H264"

#define CFG_KEY_GW_H264 \
"GW_H264"

#define CFG_KEY_H264_UPPER_LIMIT \
"H264_UPPER_LIMIT"

#define CFG_KEY_UPGRADE_TO_H264 \
"UPGRADE_TO_H264"

#define CFG_KEY_H264_VSW_AUTO \
"H264_VSW_AUTO"

#define CFG_HIDE_SITE_NAMES \
"HIDE_SITE_NAMES"\
#define CFG_RESTRICT_CONTENT_BROADCAST_TO_LECTURER \
"RESTRICT_CONTENT_BROADCAST_TO_LECTURER"\

#define CFG_KEY_RESOURCE_REPORT_MECHANISM \
"RESOURCE_REPORT_MECHANISM"

#define CFG_KEY_MAX_NUMBER_OF_RR_FILES \
"MAX_NUMBER_OF_RR_FILES"

#define CFG_KEY_TIME_RETRIVING_INTERVAL_FOR_RR_FILES \
"TIME_RETRIVING_INTERVAL_FOR_RR_FILES"

#define CFG_KEY_RESOURCE_REPORT_MAX_TIME_FILE_TO_LIVE \
"RESOURCE_REPORT_MAX_TIME_FILE_TO_LIVE"

#define CFG_KEY_AUTO_MUX_PLUS_LOGGER \
"AUTO_MUX_PLUS_LOGGER"

#define CFG_KEY_ENABLE_EXTERNAL_DB_ACCESS \
"ENABLE_EXTERNAL_DB_ACCESS"

#define CFG_KEY_EXTERNAL_DB_IP \
"EXTERNAL_DB_IP"

#define CFG_KEY_EXTERNAL_DB_PORT \
"EXTERNAL_DB_PORT"

#define CFG_KEY_ENABLE_ACTIVE_ALARM_NO_LAN \
"ENABLE_ACTIVE_ALARM_NO_LAN"

#define CFG_KEY_EXTERNAL_DB_LOGIN \
"EXTERNAL_DB_LOGIN"

#define CFG_KEY_EXTERNAL_DB_PASSWORD \
"EXTERNAL_DB_PASSWORD"

#define CFG_KEY_EXTERNAL_DB_DIRECTORY \
"EXTERNAL_DB_DIRECTORY"

#define CFG_KEY_ENABLE_EXTERNAL_DB_CONNECTIONLESS \
"ENABLE_EXTERNAL_DB_CONNECTIONLESS"

#define CFG_KEY_CONF_ID_MIN_LEN \
"NUM_CONF_ID_MIN_LEN"

#define CFG_KEY_CONF_ID_MAX_LEN \
"NUM_CONF_ID_MAX_LEN"

#define CFG_KEY_CONF_ID_LEN \
"NUM_CONF_ID_LEN"

#define CFG_KEY_H323_CS_ERROR_HANDLE_FIRST_TIMER_VAL \
"H323_CS_ERR_HANDLE_FIRST_TIMER"

#define CFG_KEY_H323_CS_ERROR_HANDLE_SECOND_TIMER_VAL \
"H323_CS_ERR_HANDLE_SECOND_TIMER"

#define ROLL_CALL_AUDIO_MIX_PERCENT \
"ROLL_CALL_AUDIO_MIX_PERCENT"

#define CFG_KEY_EXTERNAL_CONTENT_DIRECTORY \
"EXTERNAL_CONTENT_DIRECTORY"

#define CFG_KEY_EXTERNAL_CONTENT_IP \
"EXTERNAL_CONTENT_IP"

#define CFG_KEY_EXTERNAL_CONTENT_PORT \
"EXTERNAL_CONTENT_PORT"

#define CFG_KEY_EXTERNAL_CONTENT_POLLING_INTREVAL \
"EXTERNAL_CONTENT_POLLING_INTREVAL"

#define CFG_KEY_ENABLE_IP_PARTY_MONITORING \
"ENABLE_IP_PARTY_MONITORING"

#define CFG_KEY_APACHE_PRINT \
"APACHE_PRINT"

#define CFG_KEY_DEBUG_MODE \
"DEBUG_MODE"

#define CONF_PARTY_SIZE \
"CONF_PARTY_SIZE"

#define CFG_KEY_DELAYED_AUDIO_IVR_FOR_SPECIFIC_EP \
"DELAYED_AUDIO_IVR_FOR_SPECIFIC_EP"

#define CFG_KEY_GAIN_AUDIO_FOR_DTMF_FORWARDING \
"GAIN_AUDIO_FOR_DTMF_FORWARDING"

#define CFG_KEY_SILNECE_DURATION_FOR_DTMF_FORWARDING \
"SILNECE_DURATION_FOR_DTMF_FORWARDING"


#define CFG_KEY_SKIP_PROMPT \
"SKIP_PROMPT"

#define CFG_KEY_SKIP_NID \
"SKIP_NID"

//FIPS keys

#define CFG_KEY_FIPS140_SIMULATE_CARD_PROCESS_ERROR \
"FIPS140_SIMULATE_CARD_PROCESS_ERROR"

#define CFG_KEY_FIPS140_SIMULATE_ENCRYPTION_PROCESS_ERROR \
"FIPS140_SIMULATE_ENCRYPTION_PROCESS_ERROR"

#define CFG_KEY_FIPS140_SIMULATE_CONFPARTY_PROCESS_ERROR \
"FIPS140_SIMULATE_CONFPARTY_PROCESS_ERROR"

#define CFG_KEY_MIX_LINK_ENVIRONMENT \
"MIX_LINK_ENVIRONMENT"

#define CFG_KEY_IP_LINK_ENVIRONMENT \
"IP_LINK_ENVIRONMENT"

#define CFG_KEY_RECORDING_LINK_DISCONNECTION_TIMER_DURATION \
"RECORDING_LINK_DISCONNECTION_TIMER_DURATION"

#define CFG_KEY_RECORDING_LINK_START_RECORDING_TIMER_DURATION \
"RECORDING_LINK_START_RECORDING_TIMER_DURATION"

#define CFG_KEY_SUPPORT_VSW_FLOW_CONTROL \
"SUPPORT_VSW_FLOW_CONTROL"

#define CFG_RMX_MANAGEMENT_SECURITY_PROTOCOL \
"RMX_MANAGEMENT_SECURITY_PROTOCOL"

#define QOS_MANAGEMENT_NETWORK \
"QOS_MANAGEMENT_NETWORK"
#define CFG_MAX_RTV_RESOLUTION \
"MAX_RTV_RESOLUTION"

#define CFG_MAX_MSSVC_RESOLUTION \
"MAX_MS_SVC_RESOLUTION"


#define CFG_MS_CLIENT_AUDIO_CODEC \
"MS_CLIENT_AUDIO_CODEC"

#define CFG_FORCE_AUDIO_CODEC_FOR_MS_SINGLE_CORE \
"FORCE_AUDIO_CODEC_FOR_MS_SINGLE_CORE"

#define CFG_ENCODE_RTV_B_FRAME \
"ENCODE_RTV_B_FRAME"

#define CFG_IVR_MESSAGE_VOLUME \
"IVR_MESSAGE_VOLUME"

#define CFG_IVR_MUSIC_VOLUME \
"IVR_MUSIC_VOLUME"

#define CFG_IVR_ROLL_CALL_VOLUME \
"IVR_ROLL_CALL_VOLUME"

//#define CFG_IVR_ROLL_CALL_TONE
//"IVR_ROLL_CALL_USE_TONES_INSTEAD_OF_VOICE"

#define CFG_KEY_DTMF_FORWARDING \
"DTMF_FORWARDING"

// old mgc bonding flugs
// #define CFG_KEY_BONDING_DOWNSPEED
// "BONDING_DOWNSPEED"

// #define CFG_KEY_BONDING
// "BONDING"

// #define CFG_KEY_BONDING_CHANNEL_DELAY
// "BONDING_CHANNEL_DELAY"

// #define CFG_KEY_BONDING_6_CHANNELS_DELAY
// "BONDING_6_CHANNELS_DELAY"

// #define CFG_KEY_BONDING_REDIAL_DELAY
// "BONDING_REDIAL_DELAY"

// #define CFG_KEY_MUX_BOND_REDUCED_LATENCY
// "MUX_BOND_REDUCED_LATENCY"

#define CFG_KEY_BONDING_DIALING_METHOD \
"BONDING_DIALING_METHOD"

#define CFG_KEY_BONDING_NUM_CHANNELS_IN_GROUP \
"BONDING_NUM_CHANNELS_IN_GROUP"


#define CFG_KEY_INTERNAL_SCHEDULER \
"INTERNAL_SCHEDULER"
#define CFG_KEY_BONDING_CHANNEL_DELAY \
"BONDING_CHANNEL_DELAY"

#define CFG_KEY_BONDING_GROUP_DELAY \
"BONDING_GROUP_DELAY"
#define AUDIO_DECODER_COMPRESSED_DELAY \
"AUDIO_DECODER_COMPRESSED_DELAY"

#define CFG_KEY_CARDS_MODE_CHANGEABLE \
"CARDS_MODE_CHANGEABLE"

#define CFG_KEY_H239_FORCE_CAPABILITIES \
"H239_FORCE_CAPABILITIES"

#define CFG_KEY_H323_FORCE_25FPS_ON_HDX \
"H323_FORCE_25FPS_ON_HDX"

#define CFG_KEY_ENABLE_H239_HD1080 \
"ENABLE_H239_HD1080"

#define CFG_KEY_SIP_REGISTER_DELAY_MILLI_SEC \
"SIP_REGISTER_DELAY_MILLI_SEC"

#define CFG_KEY_SIP_REDUCE_AUDIO_CODECS_DECLARATION \
"SIP_REDUCE_AUDIO_CODECS_DECLARATION"

#define CFG_KEY_FORCE_CIF_PORT_ALLOCATION \
"FORCE_CIF_PORT_ALLOCATION"

#define CFG_KEY_CHECK_SIP_CHARS_IN_CONF_NAME \
"CHECK_SIP_CHARS_IN_CONF_NAME"

#define CFG_KEY_ENABLE_CLOSED_CAPTION \
"ENABLE_CLOSED_CAPTION"

#define CFG_KEY_CPU_TCP_KEEP_ALIVE_TIME_SECONDS \
"CPU_TCP_KEEP_ALIVE_TIME_SECONDS"

#define CFG_KEY_CPU_TCP_KEEP_INTERVAL_SECONDS \
"CPU_TCP_KEEP_INTERVAL_SECONDS"

#define  CFG_KEY_FORCE_RESOLUTION \
"FORCE_RESOLUTION"

#define  CFG_KEY_SEND_WIDE_RES_TO_ISDN \
"SEND_WIDE_RES_TO_ISDN"
#define CFG_ISDN_LEGACY_EP_CLOSE_CONTENT_FORCE_H263 \
"ISDN_LEGACY_EP_CLOSE_CONTENT_FORCE_H263"

#define  CFG_KEY_SEND_WIDE_RES_TO_IP \
"SEND_WIDE_RES_TO_IP"

#define  CFG_KEY_DISABLE_WIDE_RES_TO_SIP_DIAL_OUT \
"DISABLE_WIDE_RES_TO_SIP_DIAL_OUT"

#define  CFG_KEY_PAL_NTSC_VIDEO_OUTPUT \
"PAL_NTSC_VIDEO_OUTPUT"

// Deprecated, use CFG_KEY_ULTRA_SECURE_MODE
#define CFG_KEY_JITC_MODE \
"ULTRA_SECURE_MODE"

#define CFG_KEY_ULTRA_SECURE_MODE \
"ULTRA_SECURE_MODE"

#define CFG_KEY_FORCE_STRONG_PASSWORD_POLICY \
"FORCE_STRONG_PASSWORD_POLICY"

#define CFG_KEY_MIN_PWD_CHANGE_FREQUENCY_IN_DAYS \
"MIN_PWD_CHANGE_FREQUENCY_IN_DAYS"

#define CFG_KEY_MIN_PASSWORD_LENGTH \
"MIN_PASSWORD_LENGTH"

#define CFG_KEY_NUM_OF_LOWER_CASE_ALPHABETIC \
"NUM_OF_LOWER_CASE_ALPHABETIC"

#define CFG_KEY_NUM_OF_UPPER_CASE_ALPHABETIC \
"NUM_OF_UPPER_CASE_ALPHABETIC"

#define CFG_KEY_NUM_OF_NUMERIC \
"NUM_OF_NUMERIC"

#define CFG_KEY_NUM_OF_SPECIAL_CHAR \
"NUM_OF_SPECIAL_CHAR"

#define CFG_KEY_MIN_CHANGED_CHAR \
"MIN_CHANGED_CHAR"

#define CFG_KEY_MAX_PASSWORD_REPEATED_CHAR \
"MAX_PASSWORD_REPEATED_CHAR"

#define CFG_KEY_PASSWORD_EXPIRATION_DAYS \
"PASSWORD_EXPIRATION_DAYS"

#define CFG_KEY_PASSWORD_EXPIRATION_DAYS_MACHINE \
"PASSWORD_EXPIRATION_DAYS_MACHINE"

#define CFG_KEY_PASSWORD_EXPIRATION_WARNING_DAYS \
"PASSWORD_EXPIRATION_WARNING_DAYS"

#define CFG_KEY_PASSWORD_HISTORY_SIZE \
"PASSWORD_HISTORY_SIZE"

#define CFG_KEY_DISABLE_INACTIVE_USER \
"DISABLE_INACTIVE_USER"

#define CFG_KEY_ENABLE_CYCLIC_FILE_SYSTEM_ALARMS \
"ENABLE_CYCLIC_FILE_SYSTEM_ALARMS"

#define CFG_KEY_SESSION_TIMEOUT_IN_MINUTES \
"SESSION_TIMEOUT_IN_MINUTES"

#define CFG_KEY_USER_LOCKOUT \
"USER_LOCKOUT"

#define  CFG_KEY_USER_LOCKOUT_WINDOW_IN_MINUTES \
"USER_LOCKOUT_WINDOW_IN_MINUTES"

#define  CFG_KEY_USER_LOCKOUT_DURATION_IN_MINUTES \
"USER_LOCKOUT_DURATION_IN_MINUTES"

#define CFG_KEY_LAST_LOGIN_ATTEMPTS \
"LAST_LOGIN_ATTEMPTS"

#define CFG_KEY_PASSWORD_FAILURE_LIMIT \
"PASSWORD_FAILURE_LIMIT"

#define CFG_KEY_SYSTEM_MANAGEMENT_SESSION_LIMIT \
"SYSTEM_MANAGEMENT_SESSION_LIMIT"

#define  MAX_NUMBER_OF_MANAGEMENT_SESSIONS_PER_SYSTEM \
"MAX_NUMBER_OF_MANAGEMENT_SESSIONS_PER_SYSTEM"

#define  MAX_NUMBER_OF_MANAGEMENT_SESSIONS_PER_USER \
"MAX_NUMBER_OF_MANAGEMENT_SESSIONS_PER_USER"

#define CFG_KEY_OPENSSL_ENC_FUNC \
"OPENSSL_ENC_FUNC"

#define  CFG_KEY_SESSIONS_PER_USER \
"MAX_NUMBER_OF_MANAGEMENT_SESSIONS_PER_USER"

#define CFG_KEY_SEPARATE_NETWORK \
"SEPARATE_MANAGEMENT_NETWORK"

#define CFG_KEY_CHANGE_AD_HOC_CONF_DURATION \
"CHANGE_AD_HOC_CONF_DURATION"

#define CFG_KEY_APACHE_KEEP_ALIVE_TIMEOUT \
"APACHE_KEEP_ALIVE_TIMEOUT"

#define CFG_KEY_STAR_DELIMITER_ALLOWED \
"STAR_DELIMITER_ALLOWED"

#define CFG_SIP_AUTO_SUFFIX_EXTENSION \
"SIP_AUTO_SUFFIX_EXTENSION"

#define CFG_KEY_ENABLE_DEFAULT_ADHOC_CALLS \
"ENABLE_DEFAULT_ADHOC_CALLS"

#define CFG_KEY_ENABLE_AGC \
"ENABLE_AGC"

#define CONF_GATHERING_DURATION_SECONDS \
"CONF_GATHERING_DURATION_SECONDS"

#define PARTY_GATHERING_DURATION_SECONDS \
"PARTY_GATHERING_DURATION_SECONDS"

#define CFG_KEY_USE_GK_PREFIX_FOR_PSTN_CALLS \
"USE_GK_PREFIX_FOR_PSTN_CALLS"

#define CFG_KEY_ICE_TYPE \
"ICE_TYPE"

#define CFG_KEY_SET_AUDIO_PLC \
"SET_AUDIO_PLC"

#define CFG_KEY_SET_AUDIO_CLARITY \
"SET_AUDIO_CLARITY"


#define CFG_KEY_SET_AUTO_BRIGHTNESS \
"SET_AUTO_BRIGHTNESS"

#define CFG_KEY_ENABLE_FLOW_CONTROL_REINVITE \
"ENABLE_FLOW_CONTROL_REINVITE"

#define CFG_KEY_SIP_PREVENT_OVERFLOW \
"SIP_PREVENT_OVERFLOW"

#define CFG_KEY_ENABLE_DSP_RECOVERY_ON_KILL_PORT \
"ENABLE_DSP_RECOVERY_ON_KILL_PORT"

#define H264_MB_INTRA_REFRESH \
"H264_MB_INTRA_REFRESH"

#define CFG_KEY_PREFER_SVC_OVER_LYNC_CAPACITY \
"PREFER_SVC_OVER_LYNC_CAPACITY"

#define CFG_KEY_PERMANENT_CP_CONF_RESOURCE_ALLOC \
"PERMANENT_CP_CONF_RESOURCE_ALLOC"


#define CFG_KEY_MAXIMUM_RECORDING_LINKS \
"MAXIMUM_RECORDING_LINKS"

#define CFG_KEY_SUPPORT_HIGH_PROFILE \
"SUPPORT_HIGH_PROFILE"

#define CFG_KEY_SUPPORT_HIGH_PROFILE_WITH_ISDN \
"SUPPORT_HIGH_PROFILE_WITH_ISDN"

#define CFG_KEY_ENABLE_NO_VIDEO_RESOURCES \
"ENABLE_NO_VIDEO_RESOURCES_AUDIO_ONLY_MESSAGE"

#define CFG_KEY_DTMF_FORWARD_ANY_DIGIT_TIMER_SECONDS \
"DTMF_FORWARD_ANY_DIGIT_TIMER_SECONDS"

#define CFG_KEY_REPORT_DSP_CRASH \
"REPORT_DSP_CRASH"

#define CFG_KEY_BURN_BIOS \
"BURN_BIOS"

#define CFG_KEY_EXT_DB_IVR_PROV_TIME_SECONDS \
"EXT_DB_IVR_PROV_TIME_SECONDS"

#define CFG_KEY_ENCODER_RECURRENT_INTRA_REQ_MINUTES \
"ENCODER_RECURRENT_INTRA_REQ_MINUTES"

#define CFG_KEY_DECODER_RECURRENT_INTRA_REQ_MINUTES \
"DECODER_RECURRENT_INTRA_REQ_MINUTES"
#define CFG_KEY_MULTIPLE_SERVICES \
"MULTIPLE_SERVICES"
#define CFG_KEY_RMX2000_RTM_LAN \
"RMX2000_RTM_LAN"
#define CFG_KEY_V35_ULTRA_SECURED_SUPPORT \
"V35_ULTRA_SECURED_SUPPORT"

#define CFG_KEY_LAN_REDUNDANCY \
"LAN_REDUNDANCY"

#define NUMERIC_CONF_PASS_DEFAULT_LEN \
"NUMERIC_CONF_PASS_DEFAULT_LEN"
#define NUMERIC_CHAIR_PASS_DEFAULT_LEN \
"NUMERIC_CHAIR_PASS_DEFAULT_LEN"
#define NUMERIC_CONF_PASS_MAX_LEN \
"NUMERIC_CONF_PASS_MAX_LEN"
#define NUMERIC_CHAIR_PASS_MAX_LEN \
"NUMERIC_CHAIR_PASS_MAX_LEN"
#define CFG_KEY_OPERATOR_ASSISTANCE_THROUGH_REQUEST_ONLY \
"OPERATOR_ASSISTANCE_THROUGH_REQUEST_ONLY"

#define CFG_KEY_ITP_CROPPING \
"ITP_CROPPING"

#define CFG_KEY_PSTN_ECHO_DELAY_MILLI_SECOND \
"PSTN_ECHO_DELAY_MILLI_SECOND"

#define CFG_KEY_ENABLE_MULTI_PART_CDR \
"ENABLE_MULTI_PART_CDR"


#define CFG_KEY_MAX_KEEP_ALIVE_REQUESTS "MAX_KEEP_ALIVE_REQUESTS"

#define CFG_KEY_RESTORE_FACTORY_DEFAULTS_LOG_FILES \
"RESTORE_FACTORY_DEFAULTS_LOG_FILES"

#define CFG_KEY_ENABLE_SIP_PEOPLE_PLUS_CONTENT \
"ENABLE_SIP_PEOPLE_PLUS_CONTENT"

// MCCF
#define CFG_KEY_ENABLE_MCCF "ENABLE_MCCF"
#define CFG_KEY_WAIT_BEFORE_DISPATCH_MCCF "WAIT_BEFORE_DISPATCH_MCCF"
#define CFG_KEY_ENABLE_CDR_FOR_MCCF "ENABLE_CDR_FOR_MCCF"
#define CFG_KEY_SLIDES_ENV "SLIDES_ENV"

#define CFG_KEY_ENABLE_SIP_PPC_FOR_ALL_USER_AGENT \
"ENABLE_SIP_PPC_FOR_ALL_USER_AGENT"

#define ENABLE_VIDEO_PREVIEW \
"ENABLE_VIDEO_PREVIEW"

#define CFG_KEY_PCM_FECC \
"PCM_FECC"

#define CFG_KEY_AVOID_VIDEO_LOOP_BACK_IN_CASCADE \
"AVOID_VIDEO_LOOP_BACK_IN_CASCADE"

#define CFG_KEY_REPEAT_INTRA_NUMBER\
	"REPEAT_INTRA_NUMBER"

#define CFG_KEY_H263_HIGH_BIT_BUDGET_INTRA \
"H263_HIGH_BIT_BUDGET_INTRA"

#define CFG_KEY_SYNC_DESTROY_SOCKET \
"SYNC_DESTROY_SOCKET"

#define CFG_KEY_MS_CAC_AUDIO_MIN_BR \
"MS_CAC_AUDIO_MIN_BR"

#define CFG_KEY_MS_CAC_VIDEO_MIN_BR \
"MS_CAC_VIDEO_MIN_BR"

#define CFG_KEY_MAX_ALLOWED_RTV_HD_FRAME_RATE \
"MAX_ALLOWED_RTV_HD_FRAME_RATE"

#define CFG_KEY_SHOW_CPU_USAGE_ALARM \
    "SHOW_CPU_USAGE_ALARM"

#define CFG_KEY_ALWAYS_FORWARD_DTMF_IN_GW_SESSION_TO_ISDN \
"ALWAYS_FORWARD_DTMF_IN_GW_SESSION_TO_ISDN"

#define CFG_KEY_CASCADE_LINK_PLAY_TONE_ON_CONNECTION \
"CASCADE_LINK_PLAY_TONE_ON_CONNECTION"

#define CFG_KEY_ROUTE_NAME_CHANGE_INVALID_CHAR_TO_UNDERSCORE \
 "ROUTE_NAME_CHANGE_INVALID_CHAR_TO_UNDERSCORE"



#define CFG_KEY_VSW_CIF_BL_THRESHOLD_BITRATE \
"VSW_CIF_BL_THRESHOLD_BITRATE"

#define CFG_KEY_VSW_SD_BL_THRESHOLD_BITRATE \
"VSW_SD_BL_THRESHOLD_BITRATE"

#define CFG_KEY_VSW_HD_720p30_BL_THRESHOLD_BITRATE \
"VSW_HD_720p30_BL_THRESHOLD_BITRATE"

#define CFG_KEY_VSW_HD_720p50_60_BL_THRESHOLD_BITRATE \
"VSW_HD_720p50_60_BL_THRESHOLD_BITRATE"

#define CFG_KEY_VSW_HD_1080p_BL_THRESHOLD_BITRATE \
"VSW_HD_1080p_BL_THRESHOLD_BITRATE"

#define CFG_KEY_VSW_HD_1080p60_BL_THRESHOLD_BITRATE \
"VSW_HD_1080p60_BL_THRESHOLD_BITRATE"

#define CFG_KEY_VSW_CIF_HP_THRESHOLD_BITRATE \
"VSW_CIF_HP_THRESHOLD_BITRATE"

#define CFG_KEY_VSW_SD_HP_THRESHOLD_BITRATE \
"VSW_SD_HP_THRESHOLD_BITRATE"

#define CFG_KEY_VSW_HD_720p30_HP_THRESHOLD_BITRATE \
"VSW_HD720p30_HP_THRESHOLD_BITRATE"

#define CFG_KEY_VSW_HD_720p50_60_HP_THRESHOLD_BITRATE \
"VSW_HD720p50-60_HP_THRESHOLD_BITRATE"

#define CFG_KEY_VSW_HD_1080p_HP_THRESHOLD_BITRATE \
"VSW_HD1080p_HP_THRESHOLD_BITRATE"

#define CFG_KEY_VSW_HD_1080p60_HP_THRESHOLD_BITRATE \
"VSW_HD1080p60_HP_THRESHOLD_BITRATE"

#define CFG_KEY_ENABLE_TC_PACKAGE \
"ENABLE_TC_PACKAGE"

#define CFG_KEY_TC_LATENCY_SIZE \
"TC_LATENCY_SIZE"

#define CFG_KEY_TC_BURST_SIZE \
"TC_BURST_SIZE"

#define CFG_KEY_MIN_TIP_COMP_LINE_RATE \
	"MIN_TIP_COMPATIBILITY_LINE_RATE"

#define CFG_KEY_MAX_TIP_COMP_LINE_RATE \
	"MAX_TIP_COMPATIBILITY_LINE_RATE"

#define CFG_KEY_LOGGER_SYSTEM_LOAD_AVERAGE_THRESHOLD \
  "LOGGER_SYSTEM_LOAD_AVERAGE_THRESHOLD"

#define CFG_KEY_MFA_SYSTEM_LOAD_AVERAGE_THRESHOLD \
  "MFA_SYSTEM_LOAD_AVERAGE_THRESHOLD"

#define CFG_KEY_CM_HIGH_CPU_USAGE_INTERVAL_IN_MINUTES \
	"CM_HIGH_CPU_USAGE_INTERVAL_IN_MINUTES"

#define CFG_KEY_LOAD_AVERAGE_MINUTES \
  "LOAD_AVERAGE_MINUTES"

#define CFG_KEY_LOAD_AVERAGE_ALARM_LEVEL \
  "LOAD_AVERAGE_ALARM_LEVEL"

#define CFG_KEY_ENFORCE_SAFE_UPGRADE \
     "ENFORCE_SAFE_UPGRADE"

#define CFG_KEY_LOGGER_MAX_TRACE_LEVEL \
    "MAX_TRACE_LEVEL"

#define CFG_KEY_SYNC_DESTROY_SOCKET \
	"SYNC_DESTROY_SOCKET"

#define CFG_KEY_CASCADE_LINK_PLAY_TONE_ON_CONNECTION \
"CASCADE_LINK_PLAY_TONE_ON_CONNECTION"

#define CFG_KEY_SPLIT_TIP_VIDEO_RESOURCES \
"TIP_SPLIT_VIDEO_RESOURCES"

#define CFG_KEY_3CIF_PORTS_ON_DSP \
 "3CIF_PORTS_ON_DSP"

#define CFG_KEY_DELAY_BETWEEN_GENERATE_ENC_KEY \
  "DELAY_BETWEEN_GENERATE_ENC_KEY"

#define CFG_KEY_MONITORING_PACKET \
 "MONITORING_PACKET"

#define CFG_KEY_MEDIA_NIC_MTU_SIZE \
 "MEDIA_NIC_MTU_SIZE"

#define CFG_KEY_H264_HD_GRAPHICS_MIN_CONTENT_RATE \
	"H264_HD_GRAPHICS_MIN_CONTENT_RATE"

#define CFG_KEY_H264_HD_HIGHRES_MIN_CONTENT_RATE \
	"H264_HD_HIGHRES_MIN_CONTENT_RATE"

#define CFG_KEY_H264_HD_LIVEVIDEO_MIN_CONTENT_RATE \
	"H264_HD_LIVEVIDEO_MIN_CONTENT_RATE"
#define CFG_KEY_FORCE_CONTENT_TO_H264_HD \
   "FORCE_CONTENT_TO_H264_HD"

#define CFG_KEY_SET_DTMF_SOURCE_DIFF_IN_SEC "SET_DTMF_SOURCE_DIFF_IN_SEC"
#define CFG_KEY_SET_DTMF_SOURCE_DIFF_IN_SEC_VOIP "SET_DTMF_SOURCE_DIFF_IN_SEC_VOIP"

#define CFG_KEY_ACCEPT_H323_DTMF_TYPE "ACCEPT_H323_DTMF_TYPE"
#define CFG_KEY_ACCEPT_VOIP_DTMF_TYPE "ACCEPT_VOIP_DTMF_TYPE"

#define CFG_KEY_IP_RESPONSE_ECHO \
  "IP_RESPONSE_ECHO"

#define CFG_KEY_DUPLICATE_IP_DETECTION \
  "DUPLICATE_IP_DETECTION"

#define CFG_KEY_TCP_RETRANSMISSION_TIMEOUT \
  "TCP_RETRANSMISSION_TIMEOUT"

#define PROCESSBASE_DUMP_STATISTICS_TIMER_INTERVAL \
    "PROCESSBASE_DUMP_STATISTICS_TIMER_INTERVAL"

#define CFG_KEY_ISDN_CASCADE_LONG_RMT_AUDIO_NEGOTIATION \
 "ISDN_CASCADE_LONG_RMT_AUDIO_NEGOTIATION"

#define CFG_KEY_SIMULATE_REMOTE_XMIT_MODE_ISDN_H263_TO_H264 \
 "SIMULATE_REMOTE_XMIT_MODE_ISDN_H263_TO_H264"

#define CFG_KEY_SEND_SRTP_MKI \
 "SEND_SRTP_MKI"

#define CFG_KEY_DTMF_IVR_OPERATION_DELAY \
 "DTMF_IVR_OPERATION_DELAY"

#define CFG_KEY_ETH_INACTIVITY_DURATION \
"ETH_INACTIVITY_DURATION"

#define  CFG_KEY_GK_MANDATORY_FOR_CALLS_OUT \
"GK_MANDATORY_FOR_CALLS_OUT"

#define  CFG_KEY_GK_MANDATORY_FOR_CALLS_IN \
"GK_MANDATORY_FOR_CALLS_IN"

#define CFG_KEY_EXCLUSIVE_CONTENT_MODE \
"EXCLUSIVE_CONTENT_MODE"

#define CFG_KEY_NTP_LOCAL_SERVER_STRATUM \
"NTP_LOCAL_SERVER_STRATUM"

#define CFG_KEY_ENABLE_CONFERENCE_CLEANUP_ON_FAULT \
 "ENABLE_CONFERENCE_CLEANUP_ON_FAULT"

#define CFG_KEY_MPMX_MAX_NUMBER_OF_VIDEO_PARTIES_IN_CONF \
 "MPMX_MAX_NUMBER_OF_VIDEO_PARTIES_IN_CONF"

#define CFG_KEY_SIP_BFCP_DIAL_OUT_MODE \
 "SIP_BFCP_DIAL_OUT_MODE"

#define CFG_KEY_BFCP_HELLO_KEEP_ALIVE_COUNT \
 "NUM_OF_INITIATE_HELLO_MESSAGE_IN_CALL_ESTABLISHMENT"

#define CFG_KEY_ENABLE_REDIAL_ON_WRONG_NUMBER \
 "ENABLE_REDIAL_ON_WRONG_NUMBER"

#define CFG_KEY_WRONG_NUMBER_DIAL_RETRIES \
 "WRONG_NUMBER_DIAL_RETRIES"

#define CFG_KEY_ENABLE_MS_FEC \
"ENABLE_MS_FEC"

#define CFG_KEY_ENABLE_LYNC_RTCP_INTRA \
"ENABLE_LYNC_RTCP_INTRA"

#define CFG_KEY_ENABLE_LYNC_RTCP_INTRA_AVMCU \
"ENABLE_LYNC_RTCP_INTRA_AVMCU"

#define CFG_KEY_SEND_PREFERENCE_REQUEST_TO_AVMCU2010 \
"SEND_PREFERENCE_REQUEST_TO_AVMCU2010"

#define CFG_KEY_ENABLE_WRITE_LOG_TO_FILE \
"ENABLE_WRITE_LOG_TO_FILE"

#define CFG_KEY_BLOCK_NEW_LYNC2013_FUNCTIONALITY \
"BLOCK_NEW_LYNC2013_FUNCTIONALITY"

#define CFG_KEY_IGNORE_ICE_FOR_LYNC2013 \
"IGNORE_ICE_FOR_LYNC2013"

#define CFG_KEY_MAX_NUM_OF_MS_IN_SLAVES \
"MAX_NUM_OF_MS_IN_SLAVES"

#define CFG_KEY_DISABLE_MS_IN_SLAVES_DYNAMIC_REMOVAL \
"DISABLE_MS_IN_SLAVES_DYNAMIC_REMOVAL"

// Indication on Layout
#define CFG_KEY_DISABLE_CELLS_NETWORK_IND "DISABLE_CELLS_NETWORK_IND"
#define CFG_KEY_CELL_IND_LOCATION "CELL_IND_LOCATION"
#define CFG_KEY_NETWORK_IND_MAJOR_PERCENTAGE "NETWORK_IND_MAJOR_PERCENTAGE"
#define CFG_KEY_NETWORK_IND_CRITICAL_PERCENTAGE "NETWORK_IND_CRITICAL_PERCENTAGE"

//#define CFG_KEY_CLOUD_IP "CLOUD_IP"

#define CFG_KEY_FORCE_G711A "FORCE_G711A"

// Amdocs Encoder/Decoder Gain feature
#define CFG_KEY_AUDIO_DECODER_GAIN_G711 "AUDIO_DECODER_GAIN_G711"
#define CFG_KEY_AUDIO_ENCODER_GAIN_G711 "AUDIO_ENCODER_GAIN_G711"

#define CFG_KEY_AUDIO_DECODER_GAIN_G722 "AUDIO_DECODER_GAIN_G722"
#define CFG_KEY_AUDIO_ENCODER_GAIN_G722 "AUDIO_ENCODER_GAIN_G722"

#define CFG_KEY_AUDIO_DECODER_GAIN_G729 "AUDIO_DECODER_GAIN_G729"
#define CFG_KEY_AUDIO_ENCODER_GAIN_G729 "AUDIO_ENCODER_GAIN_G729"

#define CFG_KEY_AUDIO_DECODER_GAIN_G722_1 "AUDIO_DECODER_GAIN_G722_1"
#define CFG_KEY_AUDIO_ENCODER_GAIN_G722_1 "AUDIO_ENCODER_GAIN_G722_1"


//#define CFG_KEY_SVC_TO_AVC_SUPPORTS "SVC_TO_AVC_SUPPORTS"
//
//#define CFG_KEY_AVC_TO_SVC_SUPPORTS "AVC_TO_SVC_SUPPORTS"

#define CFG_KEY_MIN_SYSTEM_DISK_SPACE_TO_ALERT "MIN_SYSTEM_DISK_SPACE_TO_ALERT"

//#define CFG_KEY_VSW_RELAY_SUPPORT "VSW_RELAY_SUPPORT"

#define CFG_KEY_ENABLE_1080_SVC "ENABLE_1080_SVC"

#define CFG_PRINT_MESSAGE_QUEUE_STATISTICS "PRINT_MESSAGE_QUEUE_STATISTICS"

#define CFG_KEY_LOW_PRIORITY_UNITS_ON_MPM_PLUS "LOW_PRIORITY_UNITS_ON_MPM_PLUS"

#define CFG_ENABLE_WHITE_LIST "ENABLE_WHITE_LIST"

#define CFG_KEY_NUM_OF_PARTICIPANTS_TO_CHANGE_MRMP_LOG_LEVEL "NUM_OF_PARTICIPANTS_TO_CHANGE_MRMP_LOG_LEVEL"

#define FORCE_LEGACY_EP_CONTENT_LAYOUT_ON_TELEPRESENCE "FORCE_LEGACY_EP_CONTENT_LAYOUT_ON_TELEPRESENCE"

#define CFG_KEY_AVC_TO_SVC_INTRA_DELAY "AVC_TO_SVC_INTRA_DELAY"


#define BLOCK_CONTENT_LEGACY_FOR_LYNC "BLOCK_CONTENT_LEGACY_FOR_LYNC"

#define CFG_SNMP_FIPS_MODE "SNMP_FIPS_MODE"

#define CFG_KEY_SRTP_SRTCP_HMAC_SHA_LENGTH "SRTP_SRTCP_HMAC_SHA_LENGTH"

#define CFG_KEY_SIP_ENCRYPTION_KEY_EXCHANGE_MODE "SIP_ENCRYPTION_KEY_EXCHANGE_MODE"

#define CFG_OCSP_NO_NONCE "OCSP_NO_NONCE"

#define CFG_OCSP_RESPONDER_TIMEOUT "OCSP_RESPONDER_TIMEOUT"

#define CFG_KEY_DTLS_TIMEOUT "DTLS_TIMEOUT"

//_t_p_
#define CFG_KEY_FORCE_720P_2048_FOR_PLCM_TIP "FORCE_720P_2048_FOR_PLCM_TIP"

#define CFG_KEY_TIP_PACKET_LOSS_SEND_INTRA_INTERVAL_SEC "TIP_PACKET_LOSS_SEND_INTRA_INTERVAL_SEC"

#define CFG_KEY_TIP_SEND_INTRA_FOR_PLI "TIP_SEND_INTRA_FOR_PLI"

#define CFG_KEY_VIEW_RVGW_ACTIVEX "VIEW_RVGW_ACTIVEX"

#define CFG_KEY_ENABLE_SENDING_ICMP_DESTINATION_UNREACHABLE "ENABLE_SENDING_ICMP_DESTINATION_UNREACHABLE"

#define CFG_KEY_ENABLE_ACCEPTING_ICMP_REDIRECT "ENABLE_ACCEPTING_ICMP_REDIRECT"

#define CFG_KEY_AS_SIP_CONTENT_ADD_DELAY "AS_SIP_CONTENT_ADD_DELAY"

#define CFG_KEY_ENABLE_SIP_SERVER_OR_REGISTRAR_ERROR_ACTIVE_ALARM "ENABLE_SIP_SERVER_OR_REGISTRAR_ERROR_ACTIVE_ALARM"

#define CFG_KEY_ENABLE_COREDUMP_NOTIFICATIONS "ENABLE_COREDUMP_NOTIFICATIONS"


#define CFG_KEY_MINIMUM_DELAY_SNMP_READY_TIMER "MINIMUM_DELAY_SNMP_READY_TIMER"

#define CFG_KEY_TIP_RESOLUTION_ACCORDING_TO_CONF_VID_QUALITY "TIP_RESOLUTION_ACCORDING_TO_CONF_VID_QUALITY"

#define CFG_KEY_SIP_DETECT_DISCONNECT_TIMER "DETECT_SIP_EP_DISCONNECT_TIMER"
#define CFG_KEY_H323_DETECT_DISCONNECT_TIMER "DETECT_H323_EP_DISCONNECT_TIMER"

#define CFG_KEY_REMOVE_EP_FROM_LAYOUT_ON_NO_VIDEO_TIMER "REMOVE_EP_FROM_LAYOUT_ON_NO_VIDEO_TIMER"
#define CFG_KEY_RETURN_EP_TO_LAYOUT_ON_NO_VIDEO_TIMER "RETURN_EP_TO_LAYOUT_ON_NO_VIDEO_TIMER"

#define CFG_KEY_ALLOW_SIREN7_CODEC "ALLOW_SIREN7_CODEC"

#define CFG_KEY_APACHE_WAITING_LICENSING_TIME_SECONDS "APACHE_WAITING_LICENSING_TIME_SECONDS"

#define CFG_KEY_ENABLE_SELECTIVE_MIXING "ENABLE_SELECTIVE_MIXING"

#define CFG_KEY_FORCE_AVP_ON_ENCRYPT_WHEN_POSSIBLE "FORCE_AVP_ON_ENCRYPT_WHEN_POSSIBLE"

#define CFG_KEY_APACHE_LOG_LEVEL "APACHE_LOG_LEVEL"

#define CFG_KEY_V35_MULTIPLE_SERVICES "V35_MULTIPLE_SERVICES"
#define CFG_KEY_DISABLE_TEMPERATURE_CONTROL "DISABLE_TEMPERATURE_CONTROL"

#define CFG_KEY_MCU_VERSION_ID "MCU_VERSION_ID"

#define CFG_KEY_ENBLE_OS_LATENCY_DETECTION \
"ENABLE_OS_LATENCY_DETECTION"

#define CFG_KEY_OS_LATENCY_LOW_THRESHOLD \
"OS_LATENCY_LOW_THRESHOLD"

#define CFG_KEY_OS_LATENCY_HIGH_THRESHOLD \
"OS_LATENCY_HIGH_THRESHOLD"

#define CFG_MCMS_NETWORK_FINISH_TIMEOUT "MCMS_NETWORK_FINISH_TIMEOUT"
#define CFG_IPV6_AUTO_CONFIG_TIMEOUT "IPV6_AUTO_CONFIG_TIMEOUT"

#define CFG_KEY_RTCP_LYNC_PREFERENCE_REQ_INTERVAL \
"RTCP_LYNC_PREFERENCE_REQ_INTERVAL"

#define CFG_KEY_SIP_OMIT_DOMAIN_FROM_PARTY_NAME \
 "SIP_OMIT_DOMAIN_FROM_PARTY_NAME"

#define CFG_KEY_CDR_SERVICE_QUEUE_SIZE \
"CDR_SERVICE_QUEUE_SIZE"

#define CFG_KEY_CDR_SERVICE_QUEUE_FULL_THRESHOLD \
"CDR_SERVICE_QUEUE_FULL_THRESHOLD"

#define CFG_KEY_CDR_SERVICE_RETRY_TIME \
"CDR_SERVICE_RETRY_TIME"

#define CFG_KEY_BFCP_REQUEST_RETRY_TIMES \
"BFCP_REQUEST_RETRY_TIMES"

#define CFG_KEY_LICENSE_VALIDATION_INTERVAL \
"LICENSE_VALIDATION_INTERVAL"

#define CFG_KEY_ENABLE_RECORDING_CONTROL_VIA_SIPINFO \
"ENABLE_RECORDING_OPERATION_VIA_SIPINFO"

#define CFG_KEY_MAX_SINGLE_TRANSFER_FRAME_SIZE_BITS "MAX_SINGLE_TRANSFER_FRAME_SIZE_BITS"
// VBGFE-7734
#define CFG_KEY_CONF_TASK_RECEIVE_BUFFER_SIZE \
"CONF_TASK_RECEIVE_BUFFER_SIZE"

#define CFG_KEY_CONF_TASK_SEND_BUFFER_SIZE \
"CONF_TASK_SEND_BUFFER_SIZE"

#define CFG_KEY_ENABLE_DTMF_NUMBER_WO_DELIMITER \
"ENABLE_DTMF_NUMBER_WO_DELIMITER"

#define CFG_KEY_FOLLOW_SPEAKER_ON_1X1 "FOLLOW_SPEAKER_ON_1X1"

#define CFG_KEY_CS_API_XML_MODE "CS_API_XML_MODE"

#define CFG_KEY_ENABLE_DHCPV6 "ENABLE_DHCPV6"

// Traffic shaping:
#define CFG_KEY_ENABLE_RTP_TRAFFIC_SHAPING			"ENABLE_RTP_TRAFFIC_SHAPING"
#define CFG_KEY_TRAFFIC_SHAPING_WINDOW_SIZE 		"TRAFFIC_SHAPING_WINDOW_SIZE"
#define CFG_KEY_TRAFFIC_SHAPING_MTU_FACTOR 			"TRAFFIC_SHAPING_MTU_FACTOR"
#define CFG_KEY_TRAFFIC_SHAPING_MTU_MIN 			"TRAFFIC_SHAPING_MTU_MIN"

#define CFG_KEY_LIMIT_CIF_SD_PORTS_PER_MPMX_CARD \
"LIMIT_CIF_SD_PORTS_PER_MPMX_CARD"

#define CFG_KEY_VIDEO_BIT_RATE_REDUCTION_PERCENT 	"VIDEO_BIT_RATE_REDUCTION_PERCENT"

#define CFG_KEY_ENABLE_CONTENT_IN_PREFER_TIP_FOR_CALL_RATES_LOWER_THAN_768K "ENABLE_CONTENT_IN_PREFER_TIP_FOR_CALL_RATES_LOWER_THAN_768K" //BRIDGE-13154

#define CFG_KEY_SPREAD_VIDEO_ALLOCATION_ON_NETRA_UNITS \
"SPREAD_VIDEO_ALLOCATION_ON_NETRA_UNITS"

#define CFG_KEY_NUM_OF_PCM_IN_MPMX \
"NUM_OF_PCM_IN_MPMX"

#define CFG_KEY_ENABLE_CONTENT_OF_768_FOR_1024_LV \
"ENABLE_CONTENT_OF_768_FOR_1024_LV"

#define CFG_KEY_LPR_CONTENT_RATE_ADJUST_WEAK_LPR \
"LPR_CONTENT_RATE_ADJUST_WEAK_LPR"

#define CFG_KEY_RETRIEVE_OCCUPIED_UDP_PORTS_TIMER \
	"RETRIEVE_OCCUPIED_UDP_PORTS_TIMER"
#endif // SYS_CONFIG_KEYS_H_
