#ifndef MPLINTERNALOPCODES_H_
#define MPLINTERNALOPCODES_H_

//#define MPL_INTERNAL_FIRST_OPCODE_IN_RANGE				30000001

#define   MPL_INTERNAL_DUMMY_OPCODE                      	30999999

//#define MPL_INTERNAL_LAST_OPCODE_IN_RANGE					31000000
#endif /*MPLINTERNALOPCODES_H_*/
