/*
********************************************************************************
*
* Copyright (C) 2003 Polycom Israel Ltd.
* This file contains confidential information proprietary to POLYCOM ISRAEL Ltd.
* The use or disclosure of any information contained In this file without the
* written consent of an officer of POLYCOM ISRAEL Ltd is expressly forbidden.
*
********************************************************************************

*****************************************************************************

 General Description: File contains the defintions of the audio controller requests structures

 Generated By: Eyal Leviav      Date: 7/25/2005

*****************************************************************************/

#ifndef __ART_AUD_CTRL_REQUEST_STRUCTS_H
#define __ART_AUD_CTRL_REQUEST_STRUCTS_H

/***** Include Files *****/

/***** Constants *****/

/***** Macros *****/

/***** Type Definition *****/

////////////////////////////////////
// Open conference request struct 
////////////////////////////////////
typedef struct  
{   
	APIU32			bunVideoSpeaker;			// Video Speaker flag	
	APIU32			unTalkHoldTime;	   			// Talk Hold Time		

	APIU32			bunAudioSpeaker;			// Audio Speaker flag	
	APIU32			unAudioSpeakerWindow;		// Audio Speaker Window	

	APIU32			unReqAudioMixDepth;	   		// Audio Mix Depth	

	APIS32			enConfSpeakerChangeMode; 	// 0 - default   1 - Fast
	APIU32			bunSelectiveMixing;	 		// 0 – off (default) 1 - on
	APIU32			unLastSpeakerPreference;	// default is 0, 1 for TIP conferencess
	
}	TAcOpenConfReq;

////////////////////////////////////
// Close conference request struct 
////////////////////////////////////
typedef struct  
{   
	APIU32			unDummy;
}	TAcCloseConfReq;											

////////////////////////////////////////////////
// Update conference params request struct 
///////////////////////////////////////////////
typedef struct  
{   	
	APIU32			bunVideoSpeaker;			// Active Speaker flag	
	APIU32			unTalkHoldTime;	   			// Talk Hold Time		

	APIU32			bunAudioSpeaker;			// Audio Speaker flag	
	APIU32			unAudioSpeakerWindow;		// Audio Speaker Window	

	APIU32			unReqAudioMixDepth;	   		// Audio Mix Depth		
	
}	TAcUpdateConfParamsReq;

////////////////////////////////////////////////
// Audio Controller request struct 
///////////////////////////////////////////////
typedef struct

{
    APIU32           unBoardId;
    APIU32           unSubBoardId;   
    APIU32           unUnitId;
    APIU32 		     eAudioContollerType;		// EAudioContollerType enam

}  TAcTypeReq;



/***** Public Global Variables *****/

/***** Public Functions Prototypes *****/


#endif

