#ifndef INSTALLERDEFINES_H_
#define INSTALLERDEFINES_H_


#define VERSION_NAME_PREFIX		"RMX_"
#define AMOS_VERSION_NAME_PREFIX "RMX4000_"
#define CG_VERSION_NAME_PREFIX "CALLGENERATOR_"



#endif /*INSTALLERDEFINES_H_*/
