#if !defined(_CONFPARTYOPCODES_H)
#define _CONFPARTYOPCODES_H

#define CHANGEMODE_TIME		100 // all internal MCU units receive 5 seconds to reply, and the network has 50 second -> 5+5+50+5+5 <= 100

//////////////////////////////////// API opcodes ////////////////////////
		// Party api consts
		// Party Api Timer opcode 1001 - 1500
const WORD  SYNCLOSS				= 1018;
const WORD  H221CONTOUT				= 1019;
const WORD  CHANGEMODETOUT			= 1020;
const WORD  IDENTCHNLTOUT			= 1021;
const WORD  EXNGCAPTOUT				= 1022;
const WORD  GWESTABLISHEDTOUT		= 1023;
const WORD  GW_TEXT_ON_SCREEN_TOUT	= 1024;
const WORD  ADDASSIPCONTENTTOUT		= 1025;

		//Party Api General flow 1600 - 2150
const WORD  REJECTCALL				= 2000;
const WORD  ESTABLISHCALL			= 2001;
const WORD  CONFCHANGEMODE			= 2002;
const WORD  CONFCONTENTCHANGEMODE	= 2003;
const WORD  CONFEXNGCAP				= 2004;
const WORD  LOBBYDESTROY			= 2006;
const WORD  LOBBYTRANS				= 2007;
const WORD  LOBBYIDENT				= 2008;
const WORD  LOBBYNETIDENT			= 2009;
const WORD  PARTYTRANSFER			= 2010;
const WORD  NETTRANSFER				= 2011;
const WORD  SETVIDPARAM				= 2012;
const WORD  SETSOFTWARECPVIDPARAM	= 2013;
const WORD  SETAUDPARAM				= 2014;
const WORD  SETAUDPLUSPARAM			= 2015;
const WORD  SETDATPARAM				= 2016;
const WORD  ENDH221CON				= 2017;
const WORD  ENDCHAGEMODE			= 2018;
const WORD  RMTCAP					= 2019;
const WORD  ALLRMTCAPSRECEIVED		= 2020;

const WORD	TOKENRECAPCOLLISIONEND	= 2021;

const WORD  NETCONNECT				= 2023;
const WORD  NETCONTOUT				= 2024;
const WORD  DISCONNECT				= 2025;
const WORD  ENDIDENTCHNL			= 2026;
const WORD  RMTH230					= 2027;
const WORD  ADDNETCHNL				= 2028;
const WORD  ADDNETCHNLDESC			= 2029;
const WORD BONDREQCHNL                              = 2030;
const WORD BONDCONNECT                              = 2031;
const WORD BONDREQPARAMS                            = 2032;
const WORD BONDDISCONNECT                           = 2033;
const WORD  CHANNEL_DIALING_TIMER   = 2034;
const WORD  SETCONTENTPARAM			= 2035;
const WORD  SINGE_INTRA_AV_MCU					= 2036;
const WORD  UPDATEVIDPARAM			= 2037;
const WORD  UPDATENETCHANNEL		= 2038;
const WORD  UPDATECHANNELACK		= 2039;
const WORD  AUDVALID				= 2040;
const WORD  VIDVALID				= 2041;
const WORD  SYNCTIMER				= 2042;
const WORD  ENDDISCONNECT			= 2043;
const WORD  VCUTOUT					= 2044;
const WORD  T120VALID				= 2045;
const WORD  AUDIOPLUSBLOCK			= 2046;
const WORD  SNMPCONNECTIONINFO		= 2047;
const WORD  SYMMODE					= 2048;

const WORD  RMTXFRMODE				= 2050;
const WORD  EXPORT					= 2051;
const WORD  IMPORT					= 2052;
const WORD  SENDAUDMSG				= 2053;
const WORD  SETMLPPARAM				= 2054;
const WORD  MSYNCFOUND				= 2055;
const WORD  AUDLOOP					= 2056;
const WORD  REDIALPARTY				= 2057;
const WORD  CONNECTDELAY			= 2058;
const WORD  DISCONNECTDELAY			= 2059;
const WORD  VIDSLIDE				= 2060;
const WORD  MEDIAERR				= 2061;
const WORD  VIDREJECT				= 2062;
const WORD  VIDAIRIND				= 2063;
const WORD  CANCELVIDAIRIND			= 2064;
const WORD  AUDIOSILANCE			= 2065;
const WORD  AUDIOVOLUME				= 2069;
const WORD  MUTEAUDPLSPARTY			= 2070;
const WORD  PARTY_ENCRYPTION_STATE	= 2071;
const WORD  CONFUPDATELOCALCAPS		= 2072;
const WORD  STREAMS_INTRA_REQ		= 2073;
const WORD  HANDLE_SINGEL_FEC_OR_RED_WITH_AV_MCU2013 = 2074;

// party ==> bond-control events
const WORD  BOND_CONNECT			   = 2080;
const WORD  BOND_ADD_CHANNEL		   = 2081;
const WORD  BOND_DISCONNECT			   = 2082;

// bond-control ==> party events
const WORD  BOND_END_NEGOTIATION       = 2090;
const WORD  BOND_ALIGNED               = 2091;
const WORD  BOND_CALL_FAILED           = 2092;
const WORD  BOND_CALL_DISCONNECTED     = 2093;
const WORD  REALLOCATERTM              = 2094;
const WORD  REALLOCATERTM_ACK          = 2095;

const WORD  BOARDFULL    			= 2098;
const WORD  BOARDFULL_ACK    		= 2099;


const WORD  STARTCOMMANDH230SEQ		= 2100;
const WORD  VISUALMVCACCEPT			= 2101;
const WORD  VISUALMVCREJECT			= 2102;
const WORD  SERVICENAME				= 2103;
const WORD  BACKGROUNDCOLOR			= 2104;
const WORD CONFCONTENTTOKENMSG                      = 2105;
const WORD CONTENTRATECHANGE                        = 2106;
const WORD  CONTENTFREEZEPIC		= 2107;
const WORD CONTENTVIDREFRESH                        = 2108;
const WORD  SETMOVEPARAMS			= 2109;
// const WORD XML_EVENT                             = 2110; move to opcodes.h
const WORD  LISTENINGAUDIOVOLUME	= 2111;
const WORD CONTENTRATECHANGEDONE                    = 2112;
const WORD  DISCONNECTENC				= 2113;
const WORD  PARTYEXCHANGECAPS			= 2114;
const WORD  H264CHANGEPARAM         	= 2115;
const WORD  CONTENTMASTERRATECHANGE		= 2116;
const WORD	AMC_CONTENT_VIDEO_MODE		= 2117;
const WORD  RESUME_RMT_SYNC_TOUT		= 2118;
const WORD  AMC_LOGICAL_CHANNEL_INACTIVE= 2119;
const WORD  AMC_MCS						= 2120;
const WORD  FLOW_CONTROL_RELEASE_RES	= 2122;
const WORD  PARTYVIDSELFLOOP			= 2123;
const WORD  VTX_SETUP_TIMEOUT			= 2124;
const WORD  SIP_EVENT_PACKAGE			= 2125;
const WORD	SIP_CX_PACKAGE				= 2126;
const WORD	SIP_REFER					= 2127;
const WORD  CONTENT_MESSAGE_FROM_MASTER = 2128;
const WORD  SMART_RECOVERY 				= 2129;
const WORD  VIDEO_READY_FOR_IVR         = 2130;
const WORD  LPR_CHANGE_RATE				= 2131;
const WORD  OBSERVER_TYPE_PCM			= 2132;

// isdn encryption
const WORD START_ENC                    = 2134;
const WORD KEY_REQ_TOUT                 = 2135;
const WORD ENC_CONNECTION_TOUT          = 2136;

// Content - simulate indication for intra
const WORD CONTENTVIDSIMINDREFRESH		= 2137;
const WORD RTCP_FLOW_CONTROL			= 2138; /* Send RTCP flow control timer - for IBM-811*/
const WORD CHANGE_CONTENT_BIT_RATE_BY_LPR = 2139;// VNGFE-8204

//const WORD DEBUG_PROXY_CORE            = 2139;

//LYNC2013_FEC_RED:
const WORD FEC_RED_CHANGE_RATE			= 2150;
const WORD FEC_RED_VIDEO_RATE_UPDATED	= 2151;
const WORD UPDATE_NEW_FEC_RED_RATE    	= 2152;
const WORD SIP_PARTY_SINGLE_FEC_RED_MSG 		= 2153;
const WORD SIP_PARTY_CONTROL_SINGLE_FEC_RED_MSG = 2154;

				//API H323 2200 - 2500
const WORD  H323ESTABLISHCALL				 = 2200;
const WORD  ENDCHANNELCONNECT				 = 2201;
const WORD	ENDH323DISCONNECT				 = 2202;
const WORD  DISCONNECTH323					 = 2203;
const WORD  IPDISCONNECTCHANNEL				 = 2204;
const WORD  IPLOGICALCHANNELCONNECT			 = 2205;
const WORD  IPLOGICALCHANNELDISCONNECT		 = 2206;
const WORD  H323GATEKEEPERSTATUS			 = 2207;
const WORD  IPPARTYMONITORING				 = 2208;
const WORD  IPPARTYMONITORINGFORSOFTWARECP	 = 2209;
const WORD  STREAMOFF					 	 = 2210;
const WORD  STREAMON					 	 = 2211;
const WORD  REMOTECAPABILITIESIND		 	 = 2212;
const WORD  H323PASSGWCONFCAPS			 	 = 2213;
const WORD  H323NONSTANDARDIND		     	 = 2214;
const WORD  H323RMTCI				 	 	 = 2215;
const WORD  ADDPROTOCOL				     	 = 2216;
const WORD  REMOVEPROTOCOL               	 = 2217;
const WORD  H323SOFTWCPPARTYVIDEOUPDATE  	 = 2218;
const WORD  SETVIDEORATE                 	 = 2219;
const WORD  AUTODETECTRANSFER  				 = 2220;	// AUTODETECT transfer of CNetChnlCntl
const WORD  AUTODETECTINIT	   				 = 2221;  //
const WORD  AUTODETECTMUXINIT  				 = 2222;  //
const WORD  CHECK_FOR_ANOTHER_CONNECTED_PARTY= 2223;
const WORD	DUMPCONF		   				 = 2224;
const WORD  PARTY_CLOSE_CHANNEL			 	 = 2225;
const WORD	END_AUDIO_RECONNECT			 	 = 2226;
const WORD	END_CONTENT_RECONNECT		 	 = 2227;
const WORD  PARTY_FLOWCONTROL            	 = 2228;  //send flow control from conf to party

//Multiple links for ITP in cascaded conference feature:
const WORD  PARTY_SEND_ITPSPEAKER_ACKREQ     = 2229;
const WORD  VB_SEND_ITPSPEAKER_REQ           = 2230;

const WORD  CONF_UPDATE_CAPS_AND_AUDIORATE 	 = 2236;

const WORD  PARTY_FLOWCONTROL_2CHANNELS  	 = 2260;  //send flow control from conf to party for both channels
const WORD  LSDCHANNEL					 	 = 2261;
const WORD  IPPARTYPACKETSFRACTIONLOST	 	 = 2262;
const WORD  AUD_DECODER_MUTED_TOUT       	 = 2263;
const WORD	IPPARTYMONITORINGREQ		 	 = 2264;
const WORD  RECONNECT_STREAM			 	 = 2265;
const WORD  REJECT_NEW_CHANNEL		     	 = 2266;
const WORD  IP_STREAM_VIOLATION			 	 = 2267;
const WORD  REMOTE_SENT_RE_CAPS			 	 = 2268;
const WORD  PARTY_CHANEG_VID_MODE        	 = 2269;
const WORD  H323_CHANEG_DATA_MODE        	 = 2270;
const WORD  SECONDARYCAUSEH323			 	 = 2271;
const WORD  DISCONNECTH323MMLP			 	 = 2272;
const WORD  H323TERMINALINDASSIGNMENT	 	 = 2273;
const WORD  H323CONNECTCHAIRCNTL		 	 = 2274;
const WORD  RMT323COMMODUPDATE			 	 = 2275;
const WORD  IPDATATOKENMSG				 	 = 2276;
const WORD	IPLOGICALCHANNELUPDATE		 	 = 2277;
const WORD  H323DBC2COMMAND			     	 = 2278;
const WORD  PARTY_RECEIVE_RECAPS		 	 = 2279;
const WORD  SET_CAPS_ACCORDING_TO_NEW_ALLOCATION 	 = 2280;
const WORD  IPFECCKEYMSG				 	 		 = 2281;
const WORD  PARTY_REMOVE_SELF_FLOWCONTROL_CONSTRAINT = 2282;//update party that we remove it's flow control request constraint
const WORD  UPDATE_VIDEO_RESOLUTION 		 = 2283;
const WORD  REMOTE_SENT_DISCONNECT_BRIDGES 	 = 2284;
const WORD  REMOTE_SENT_CONNECT_BRIDGES 	 = 2285;
const WORD  UPDATE_VIDBRDG_TELEPRESENSE_EP_INFO  	= 2286; //_e_m_
const WORD  UPDATE_VIDEO_AFTER_VSR_MSG 		 = 2287;
const WORD  SINGLE_UPDATE_PACSI_INFO 		 = 2288;
// TIP recap
const WORD	TIP_REMOTE_SENT_RE_CAPS_FOR_SLAVE= 2290;
const WORD  TIP_MUTE_SLAVE_IF_NEEDED		 = 2291;
const WORD	PARTY_SLAVE_TO_MASTER_RECAP_ACK	 = 2292;
const WORD	SLAVE_END_CHANGE_MODE			 = 2293;
const WORD  TIP_SLAVE_RECAP_TOUT			 = 2294;
const WORD TIP_UPDATE_RTP_FOR_SLAVE		    		= 2295;
const WORD CHANGE_VIDEO_OUT_TIP_POLYCOM		    	= 2296;
const WORD  UPDATE_LAST_TARGET_MODE_MSG 	 = 2297;


const WORD  UPDATE_CAPS				     	 = 2300;
const WORD	INCREASE_DISCONNECT_TIMER	 	 = 2301;
const WORD  INACTIVATE_CHANNEL			 	 = 2302;
const WORD  DRQ_TIMER					 	 = 2303;
const WORD  UPDATERSRCCONFID			 	 = 2304;
const WORD  UPDATE_GK_CALL_ID			 	 = 2305;
const WORD  TIMER_TCS_4_MESSAGE          	 = 2306;
const WORD  UPDATE_VIDEO_RATE          	     = 2307;
const WORD  CLEAN_VIDEO_RATE_LIMIT			 = 2308;
const WORD  UPDATE_VIDEO_FLOW_CNTL_RATE		 = 2309;
const WORD  LPR_VIDEO_RATE_UPDATED			 = 2310;
const WORD  LPR_PARTY_FLOWCONTROL			 = 2311;
const WORD  UPDATELPRACTIVATION				 = 2312;
const WORD  START_PREVIEW_PARTY				 = 2313;
const WORD  STOP_PREVIEW_PARTY				 = 2314;
const WORD  REQUEST_PREVIEW_INTRA			 = 2315;
const WORD  LEADER_CHANGED					 = 2316;
const WORD  SET_FECC_PARTY_TYPE				 = 2317;
const WORD  CONTENT_SPEAKER_INTRA_SUPPRESSION_TIMER		 = 2318;
const WORD  SEND_INFO_TO_RSS				 = 2320;
const WORD  UPDATE_NO_RESOURCES_FOR_VIDEO_PARTY	 = 2321;
const WORD UPDATE_LPR_CHANNEL_HEADER  = 2322;
const WORD SEND_MUTE_VIDEO  = 2323; // ask party to send channel active/inactive
const WORD SIPALLOCATEDBANDWIDTHSTATUS  = 2324;
const WORD COP_USE_SMART_SWITCH_ACCORDING_TO_VENDOR = 2325;
const WORD SIPBANDWIDTHREINVITENEEDED     = 2326;
const WORD CONTENT_INTRA_TOUT             = 2327;
const WORD ALL_MS_IN_SLAVES_CONNECTED     = 2328;
const WORD LOCAL_RMX_AV_MCU_MSI     	  = 2329;
const WORD DELETE_AV_MCU_IN_SLAVE_REQ     = 2330;


				 //API of IVR in party 2950 - 3030
const WORD	IVR_END_OF_FEATURE		  	= 2950;
const WORD	DTMF_STRING_IDENT		   	= 2951;
const WORD	DTMF_OPCODE_IDENT		   	= 2952;
const WORD	IVR_PLAY_ONHOLD_MESSAGE	 	= 2953;
const WORD	IVR_EROR_FEATURE			= 2954;
const WORD	OPER_ASSIST_INCONF			= 2955;
const WORD	OPER_ASSISTANCE_SET_HOLD	= 2956;
const WORD	IVR_RESET					= 2957;
const WORD	MUTE_ALL_BUT_X				= 2958;
const WORD	IVR_CONFTERMINATE			= 2959;
const WORD	OPER_ASSIST_IVR				= 2960;
const WORD  DTMF_VOTE_IDENT				= 2961;
const WORD  IVR_MSG_ONCE_GENERAL		= 2962;
const WORD  IVR_GENERAL_EVENT			= 2963;
const WORD  IVR_SYSTEM_MESSAGES_EVENT	= 2964;
const WORD  INVITE_PARTY				= 2965;
const WORD  IVR_MESSG					= 2966;
const WORD  IVR_SUB_FEATURE_MESSG		= 2967;
const WORD	IVR_INVITE_RESULT_ALLOC		= 2968;
const WORD	UPDATE_PHONE_PARTY			= 2969;
const WORD	START_DIAL_OUT				= 2970;
const WORD	DELETE_INVITEE				= 2971;
const WORD	DISCONNECT_INVITEE			= 2972;
const WORD	UPDATE_GROUP_ID				= 2973;
const WORD	FIRST_DTMF_WAS_DIALED		= 2974;
const WORD	INVITEE_CONNECTED			= 2975;
const WORD	DISCONNECT_INVITER			= 2976;
const WORD  START_IVR                   = 2977;
const WORD  MSG_RECORDED				= 2978;
const WORD	RECORD_REQUEST				= 2979;
const WORD  END_ROLL_CALL				= 2980;
const WORD	INVITEE_MOVE_TO_CONF		= 2981;
const WORD	DTMF_RECORD_REQUEST			= 2982;
const WORD	EXCLUSIVE_SPEAKER			= 2983;
const WORD	PLAY_DIAL_TONE_AFTER_MESSAGE= 2984;
const WORD  OPERATOR_ASSIST				= 2985;
const WORD	EXTENSION_DTMF_TIMER		= 2987;
const WORD  VC_REJECTED					= 2988;
// const WORD EXT_DB_PWD_CONFIRM                    = 2989; moved to common place
// const WORD EXT_DB_CONF_CONFIRM                   = 2990; moved to common place
const WORD	CREATE_AD_HOC_CONFERENCE	= 2991;
const WORD  DTMF_FORWARDING				= 2992;
const WORD  DTMF_FORWARDING_TIMER		= 2993;
const WORD  CREATE_AD_HOC_CONF			= 2994;
const WORD  START_IVR_MUTE_NOISY_LINE	= 2995;
const WORD  START_MUTE_NOISY_LINE_MENU  = 2996;
const WORD	RECORDING_LINK_STATUS		= 2997;
const WORD  OPEN_RECORDING_SESSION_IND	= 2998;
const WORD  CLOSE_PLAYBACK_SESSION_IND	= 2999;
const WORD  CAM_READY_FOR_IVR			= 3000;
const WORD  CHAIR_DROPPED_TERMINATE		= 3001;
const WORD  SET_PARTY_AS_LEADER			= 3002;
const WORD  IVR_PARTY_READY_FOR_SLIDE	= 3003;
const WORD  IVR_PARTY_STOP_IVR			= 3004;
const WORD  RECORD_CONF_FAILED			= 3005;
const WORD  SET_GW_DTMF_FORWARD			= 3006;
const WORD  GW_DTMF_FORWARD             = 3007;
const WORD  SET_INVITED_DTMF_FORWARD	= 3008;
const WORD  INVITED_DTMF_FORWARD		= 3009;
const WORD  SET_IVR_SERVER_DTMF_FORWARD	            = 3010; //DTMF-Forward-IBM
const WORD  IVR_SERVER_DTMF_FORWARD	                = 3011; //DTMF-Forward-IBM
const WORD END_WAIT                                 = 3012; //IVR for TIP
const WORD  STOP_ROLL_CALL_TIMER		= 3013;
const WORD  STOP_ROLL_CALL_RECORDING	= 3014;
const WORD  STOP_ROLL_CALL_RECORDING_ACK	= 3015;

// recording Link events
const WORD ADD_RECORDING_LINK_PARTY	= 3033;
const WORD DISCONNECT_RECORDING_LINK_PARTY	= 3034;

const WORD	IVR_SHOW_PARTICIPANTS		= 3035;
const WORD	IVR_SHOW_GATHERING			= 3036;

const WORD EXTDB_IVR_PROV_TIMER                     = 3037;        // ivrProviderEQ
const WORD SIP_CONF_NID_CONFIRM_IND                 = 3038;        // ivrProviderEQ
const WORD SIP_CONF_NID_CONFIRM_REQ                 = 3039;        // ivrProviderEQ


const WORD ACTIVATE_AUTO_TERMINATION_CHECK_FOR_AV_MCU	= 3040;

// recording and playback
const WORD STOP_RECORDING_SESSION	= 3050;
const WORD END_RECORDING_SESSION	= 3051;
const WORD PAUSE_RECORDING_SESSION	= 3052;
const WORD RESUME_RECORDING_SESSION	= 3053;
const WORD PAUSE_RECORDING_IND		= 3054;
const WORD UPDATE_RECORDING_FORMAT	= 3055;

// IVR opcodes 3100 - 3200
const WORD IVR_FIRST_OPCODE				= 3100;
const WORD IVR_PARTY_START_MOVE_FROM_EQ	= 3101;
const WORD IVR_PARTY_UPDATE_STATUS		= 3102;
const WORD IVR_PARTY_START_MOVE_FROM_CONF = 3103;
const WORD IVR_INVITE_PARTY_TO_CONF 	= 3104;
const WORD EXTERNAL_IVR_PALY_MUSIC			= 3105; //AT&T
const WORD EXTERNAL_IVR_SHOW_SLIDE			= 3106; //AT&T
const WORD EXTERNAL_IVR_COLLECT_DIGITS		= 3107; //AT&T
const WORD EXTERNAL_IVR_MESSAGE_FOR_TIP_SLAVE    = 3108; //AT&T
const WORD EXTERNAL_IVR_PLAY_MEDIA_COMPLETE_SLAVE_TO_MASTER = 3109; //AT&T
const WORD EXTERNAL_IVR_DTMF_BARGE_IN_MASTER_TO_SLAVE = 3110; //AT&T
const WORD EXTERNAL_IVR_DIALOG_TIMEOUT_MASTER_TO_SLAVE = 3111; //AT&T
const WORD EXTERNAL_IVR_DIALOG_START		= 3112; //AT&T
const WORD EXTERNAL_IVR_DTMF_BARGE_IN		= 3113; //AT&T

const WORD PLAY_MESSAGE_AUX					= 3115; //IVR for TIP
const WORD STOP_PLAY_MESSAGE_AUX			= 3116; //IVR for TIP
const WORD PLAY_ROLL_CALL_AUX				= 3117; //IVR for TIP
const WORD MASTER_END_FEATURES				= 3118; //IVR for TIP
const WORD RECORD_PLAY_MESSAGE_ACK_SLAVE_TO_MASTER = 3119; //IVR for TIP
const WORD EXTERNAL_IVR_PLAY_MESSAGE_AUX    = 3120; //AT&T
const WORD PLAY_MESSAGE_ACK_SLAVE_TO_MASTER = 3121; //AT&T
const WORD TIP_MASTER_STARTED_IVR = 3122; //AT&T
const WORD TIP_MASTER_PARTY_MUTE = 3123;
const WORD TIP_MASTER_PARTY_UNMUTE = 3124;
const WORD TIP_MASTER_PARTY_PLAY_MENU = 3125;
const WORD TIP_MASTER_PARTY_INC_VOLUME = 3126;
const WORD TIP_MASTER_PARTY_DEC_VOLUME = 3127;

const WORD IVR_LAST_OPCODE				= 3200;

// added for redial on wrong numberconst
const WORD PARTY_INVITE_RESULT_IND     	= 3201;

// added for DTMF disconnect invited participant function in DTMF invite feature
const WORD DISCONNECT_INVITED_PARTICIPANT_REQ = 3202;

				   //API of conf
const WORD  IVRVC_MSG			= 5049;
const WORD  PARTY_MSG			= 5050;
const WORD  BRDG_MSG			= 5051;
const WORD  VIDEO_BRIDGE_MSG	= 5052;
const WORD  CHAIRCNTL_MSG		= 5053;
const WORD  FECC_BRIDGE_MSG		= 5054;
const WORD  HSDCNTL_MSG			= 5055;
const WORD  MLPCNTL_MSG			= 5056;
const WORD  AUDIO_BRIDGE_MSG	= 5057;
const WORD  EXCEPTION			= 5058;
const WORD  CARDFAIL			= 5059;
							//   5060 exist @ Confapi
const WORD GCC_COMMAND			= 5061;
const WORD  VID_PROC_MSG		= 5062;
const WORD  FINISH_ANNEXD		= 5063;
const WORD  TERM_MSG			= 5064;
const WORD  CONTENTCNTL_MSG		= 5065;
const WORD  PARTY_RSRC_ID_MSG	= 5066;
const WORD  CONF_MPL_MSG		= 5067;
const WORD  CONFAPP_MNGR_MSG	= 5068;
const WORD	EXTERNAL_PARTY_MSG 	= 5069;
const WORD  SEQUENCE_NUM_IND	= 5070;
							//   5071 exist @ Confapi
const WORD  PCM_MNGR_MSG		= 5072;
const WORD  XCODE_BRDG_MSG                            = 5073;

const WORD  ADD_IN_PARTY	  = 5000;
const WORD  ADD_IN_PARTY_CHNL	= 5001;
const WORD  FORCE_KILL			= 5002;

const WORD  ADDPARTY			= 5100;
const WORD  DELPARTY			= 5101;
const WORD  ADDINPARTY			= 5102;
const WORD  ADDPARTYCHNL		= 5103;
const WORD  ENDADDPARTY			= 5104;
const WORD  ENDDELPARTY			= 5105;
// const WORD ENDCHNGMODEPARTY                      = 65106;
const WORD  ADDPARTYCHNLDESC	= 5107;
const WORD  RECONPARTY			= 5108;
const WORD  REALLOCNET			= 5109;
const WORD  H323ADDINPARTY		= 5110;
const WORD	SIPADDINPARTY		= 5111;
const WORD	REDAILPARTY			= 5112;
const WORD	ADDDIALSTRING		= 5113;
const WORD	DIALOUTSERVICENAME	= 5114;
const WORD  REDIALHOTBACKUPPARTY = 5115;

const WORD	TMPPHONENUMBER_GET   = 6040;
const WORD	TMPPHONENUMBER_FREE  = 6041;
const WORD  CONF_FLOWCONTROL	 = 6042;//send flow control from party to conf
const WORD  OLD_CALCULATION      = 6043;
const WORD  ENDAUDRECONNECT   = 6050;
const WORD  ENDEXPPARTY	   = 6051;
const WORD  EXPPARTY		  = 6052;
const WORD  ENDIMPPARTY	   = 6053;
const WORD  IMPPARTY		  = 6054;
const WORD	BACKUPPARTYRES	= 6055;
const WORD ADDUSERCONNECTTOUT    = 6056;	//AVMCU timers
const WORD MSMNGRDISCONNECTTOUT    = 6057; //const WORD NOATEMP    = 6051;


const WORD  ISCONFREADYFORMOVE = 6066;

const WORD  REMOVPARTYCONNECTION = 6060;
const WORD  HANDLE_TERMINAL_EVENT = 6061;
const WORD  TERMINAL_RECURRENT_INTRA_REQ_TOUT = 6062;
const WORD  DELPARTYVIOLENT		  = 6063;

const WORD MESSAGE_QUEUE_TOUT                         = 6214;
const WORD  DELAY_ISDN_LINK_DISCONNECT_TOUT = 6215;
const WORD  DTMF_FWD_ALL_TOUT = 6216;
const WORD  PRE_TERMINATION_DEFAULT_EQ   = 6217;
const WORD  ALERTOUT			 = 6218;
const WORD  STARTCONF			= 6219;
const WORD  CONFTOUT			 = 6220;
const WORD  DELAY_UPDATE_CONTENT_TOUT				= 6221;


// const WORD OPENATTN                              = 6256;
// const WORD CLOSEATTN                             = 6257;
const WORD CHANGEINCONFAUDCONN                      = 6258;
const WORD CHANGEMESSAGEAUDCONN                     = 6259;
const WORD CHANGESILENCEAUDCONN                     = 6260;
const WORD CHANGESILENCEAUDMODE                     = 6261;
const WORD IMPORTPARTY                              = 6262;
const WORD EXPORTPARTY                              = 6263;
const WORD SENDPARTYH230COMMSEQ                     = 6264;


// Video Plus
const WORD TSSTREAMCONNECT                          = 6280;
const WORD INPUTSTREAMCONN                          = 6281;
const WORD OTHERVIDREFRESH                          = 6282;
const WORD MAPSYNCIND                               = 6283;

const WORD SELFRECOVERY                             = 6290;
const WORD ANNEXDTOUT                               = 6383;
const WORD OTHERTSSTREAMCON                         = 6384;
const WORD SYNCDECMCVREQ                            = 6385; // Added for sync on MCV

// ~~~~~~~VideoCommander opcodes ~~~~~~~~~~
const WORD VC_VISUAL_COMMAND                        = 6386;
const WORD VC_ACTION_COMMAND                        = 6387;

const WORD SET_SITE_AND_VISUAL_NAME                 = 6388;
const WORD UPDATEENCODERPARAMS                      = 6389;
const WORD UPDATEDECODERPARAMS                      = 6390;

// ~~~~~~~Error resilience opcodes ~~~~~~~~~~
const WORD DBC2EP                                   = 6391;
const WORD DBC2RTP                                  = 6392;
const WORD DBC2EPIND                                = 6393;
const WORD DBC2RTPIND                               = 6394;
const WORD DBC2                                     = 6395; // for simulation use


//   6221 and up- is used for other const;
const WORD  AUDBRDGCONNECT			= 6432;
const WORD  AUDBRDGDISCONNECT		= 6433;
const WORD  VIDBRDGCONNECT			= 6434;
const WORD  VIDBRDGDISCONNECT		= 6435;
const WORD  MLPBRDGCONNECT			= 6436;
const WORD  MLPBRDGDISCONNECT		= 6437;
const WORD  TIMERMLPBRDGDISCTERM	= 6438;
const WORD  CONTENTBRDGDISCONNECT	= 6439;
const WORD  CONTENTBRDGCONNECT		= 6440;
const WORD  FECCBRDGCONNECT			= 6441;
const WORD  FECCBRDGDISCONNECT		= 6442;
const WORD  BRDGSDISCONNECT			= 6443;
const WORD  BRDGSCONNECT			= 6444;
const WORD XCODEBRDGCONNECT                         = 6445;
const WORD XCODEBRDGDISCONNECT                      = 6446;


const WORD  OPENDATACHNL		 = 6450;
const WORD  CLOSEDATACHNL		= 6451;
const WORD  CHANGERATEDATACHNL   = 6452;

//const WORD ONHOLDPARTY                            = 6454;
const WORD   T120ONOFF		   = 6455;
const WORD   PARTYENDINITCOM	 = 6456;
const WORD  PARTY323CAPABILITIES = 6457;
const WORD  PARTY320CAPABILITIES = 6458;

const WORD   CHANGEMSG			 = 6459;
const WORD   STOPMSG			 = 6460;
const WORD   CONFLEADERTOUT	  = 6462;
const WORD   PLAYMESSAGEONCE	 = 6463;

const WORD   LOCK_CONFERENCE	 = 6464;


//Vote
//const WORD   START_VOTE			 = 6465;
//const WORD   STOP_VOTE			 = 6466;
const WORD	 DTMF_VOTE			 = 6467;
//const WORD   NEW_VOTE			 = 6468;
//const WORD   CANCEL_VOTE		 = 6469;
const WORD   SET_VOTE_PARAMS     = 6470;
//Q&A
const WORD   ADDPARTY_QA		 = 6471;
const WORD   REMOVEPARTY_QA		 = 6472;
const WORD   MARK_NEXT_QA		 = 6473;
const WORD   UNMARK_CURR_QA		 = 6474;
const WORD	 MOVETOBOTTOM_QA	 = 6475;
const WORD	 CLEAR_QA			 = 6476;
const WORD	 MOVETOTOP_QA		 = 6477;
const WORD   INC_PARTY_QA		 = 6478;
const WORD   DEC_PARTY_QA		 = 6479;
const WORD   SET_AUTOTERM_TIMER  = 6480;

// JOIN
const WORD   JOIN_CONFERENCE			= 6481;
const WORD   JOIN_CONFERENCE_REQUEST	= 6482;
const WORD   JOIN_CONFERENCE_ACK		= 6483;
const WORD   JOIN_CONFERENCE_CANCEL		= 6484;
const WORD   JOIN_CONFERENCE_CANCELIND	= 6485;

const WORD   SET_MUSIC_TO_PARTY         = 6486;
const WORD   DELETE_IVR_LANG            = 6487;
const WORD   SECURE_CONFERENCE			= 6488;
const WORD	 CHANGE_PASSWORDS			= 6489;

//Roll Call Opcodes
//const WORD   ROLL_CALL_NAMES_REVIEW      = 6490;
const WORD   ROLL_CALL_STOP_NAMES_REVIEW = 6491;
const WORD   ROLL_CALL                   = 6492;
const WORD   SEQUENCE_MSG                = 6493;
const WORD   RECORD_MSG                  = 6494;

// Leader
const WORD	LEADER_WAITING_TIMEOUT		= 6495;
const WORD	UPDATE_AGC_EXEC				= 6496;
const WORD	PLAY_SEQUENCE_MESSAGE_ONCE	= 6497;

const WORD	EXPORT_TOUT	= 6498;
const WORD	MOVE_CHANGE_MODE_TOUT	= 6499;
const WORD	UPDATE_T1TONE_DETECTION		= 6500;

			  // api for bridge controller
const WORD  CONNECTCONF		  = 6501;
const WORD  DISCONNECTCONF	   = 6502;
const WORD  CONNECTPARTY		 = 6503;
const WORD  DISCONNECTPARTY	  = 6504;
const WORD  ENDCONNECTCONF	   = 6505;
const WORD  ENDDISCONNECTCONF	= 6506;
const WORD  CONNECTCONFTOUT	  = 6507;
const WORD  DISCONNECTCONFTOUT   = 6508;
const WORD  ENDDISCONNECTPARTY   = 6509;
const WORD  ENDCONNECTPARTY	  = 6510;
const WORD  ENDVIDSWITCH		 = 6511;
const WORD  VOICEACTIVATE		= 6512;
const WORD  SIMSPKRCHNG		  = 6513;
const WORD  SPEAKERCHANGE		= 6514;
const WORD  VIDEOVALID		   = 6515;
const WORD  AUDIOVALID		   = 6516;
const WORD  VIDEOMUTE			= 6517;
const WORD  AUDIOMUTE			= 6518;
const WORD  AUDIOBLOCK		   = 6519;
const WORD  SETVIDSRCCP		  = 6520;
const WORD  VOICEACTIVATECP	  = 6521;
//const WORD  SETCONFVIDLAYOUT   = 6522;
const WORD  CHANGEVIDLAYOUTCP	= 6523;
const WORD  UPDATECOMP		   = 6524;
const WORD  MCVREQ			   = 6525;
const WORD  VCSREQ			   = 6526;
const WORD  VCSCANCELREQ		 = 6527;
const WORD  VIDNOTDECODEDMBIND   = 6528;
const WORD UPDATEVISUALEFFECTS                      = 6529;
const WORD  VIDCOMREQ			= 6530;
const WORD  VIDVCACTREQ			= 6531;
const WORD  ENDAUDPLUSCLOSEPORT	= 6532;
//const WORD  ENDCONNECTPARTY_LEGACY    = 6533;
const WORD ENDCONTENTSWITCH                         = 6534;
//const WORD  SPEAKERCHANGED		= 6536;
const WORD  TERMINATE			= 6537;
const WORD  ENDEXPORTPARTY		= 6538;

const WORD  UPGRADE_TO_MIX_AVC_SVC           		    = 6539;
const WORD  DOWNGRADE_MIX_AVC_SVC            		    = 6540;
const WORD  END_VIDEO_UPGRADE_TO_MIX_AVC_SVC 		    = 6541;
const WORD  END_AUDIO_UPGRADE_TO_MIX_AVC_SVC 		    = 6542;
const WORD  END_VIDEO_DOWNGRADE_MIX_AVC_SVC  		    = 6543;
const WORD  END_AUDIO_DOWNGRADE_MIX_AVC_SVC  		    = 6544;
const WORD  END_AVC_TO_SVC_ART_TRANSLATOR_CONNECT       = 6545; // From IsdnParty to IsdnPartyCntl
const WORD  END_AVC_TO_SVC_ART_TRANSLATOR_DISCONNECTED  = 6546;// From IsdnParty to IsdnPartyCntl

  // api for data brdg controller
const WORD  DATATOKENREQ			 = 6600;
const WORD  DATATOKENACCEPT		  = 6601;
const WORD  DATATOKENREJECT		  = 6602;
const WORD  DATATOKENRERETAIN		= 6603;
const WORD  DATATOKENRELEASE		 = 6604;
const WORD  DATATOKENRELEASEFREE	 = 6605;
const WORD  DATATOKENRESERVE		 = 6606;
const WORD  DATATOKENWITHDRAW		= 6607;
const WORD  DATATOKENWITHDRAWANDFREE = 6608;
const WORD  DATATOKENLOCK			= 6609;
const WORD  DATATOKENFREE			= 6610;
const WORD  ENDOPENDATACHANNEL	   = 6611;
const WORD  ENDCLOSEDATACHANNEL	  = 6612;
const WORD  ENDRATECHANGEDATACHANNEL = 6613;
const WORD  DATAAPPOPCODE			= 6614;
const WORD  RETRYCLOSECHANNEL		= 6615;
const WORD  DISCONNECTPARTYFAILURE   = 6616;
const WORD  DATATOKENRELEASEREQ	  = 6617;
const WORD  DATAINDICATERESPONSE	 = 6618;
const WORD  UPDATELSDBITRATE         = 6619;
const WORD  BLOCKLSDTOKENTOUT        = 6620;

const WORD  DELETE_ALL_CONFS_TOUT            = 6631;
const WORD  MAX_TIME_DELETE_ALL_CONFS_TOUT   = 6632;

const WORD  TIMER_START_ICE_INITIALIZATION   = 6633;
const WORD  ALLOC_UNFREE_MEMORY   = 6634;

			  // api for party controller
const WORD  PARTYRMTCAP		 = 6015;
const WORD  PARTYCONNECT		= 6016;
const WORD  PARTYDISCONNECT	 = 6017;
const WORD  PARTYCONNECTTOUT	= 6018;
const WORD  PARTYDISCONNECTTOUT = 6019;
const WORD  CONNECTTOUT		 = 6020;
const WORD  PARTYENDDISCONNECT  = 6021;
const WORD  PARTYEXPORTTOUT	 = 6022;
const WORD  PARTYIMPORTTOUT	 = 6023;
const WORD  PARTYEXPORT		 = 6024;
const WORD  PARTYIMPORT		 = 6025;
const WORD  H323PARTYCONNECT	= 6026;
const WORD  DESTROYAUDIOPLUSCONNECTION = 6027;
const WORD  ENDNETCHNLDISCONNECT  = 6028;
const WORD  H323DISCONNECTMMLP    = 6029;
const WORD  BRIDGEDISCONNECT    = 6030;
const WORD  H323PARTYCONNECTALL = 6031;
const WORD  IPPARTYUPDATEBRIDGES = 6032;
const WORD  IPPARTYCONNECTED    = 6033;
const WORD  IP_MUTE_MEDIA		= 6034;
//const WORD IP_ACTIVE_MEDIA                        = 6035;
const WORD  IP_STREAM_IS_OFF	= 6036;
const WORD  MPLDISCONNECTTOUT	  = 6037;
const WORD  RACONNECTTOUT	      = 6038;
const WORD  RADISCONNECTTOUT	  = 6039;

const WORD  VIDEO_UPDATE_TIMEOUT  = 6070;
const WORD  MFACONNECTTOUT		  = 6071;
const WORD  WAIT_BEFORE_CONNECT_TO_VB_TIMER = 6072;
const WORD  SIP_GLARE_TIMER		  = 6073;
const WORD	SIP_SEND_INTRA_AFTER_TRANS_TOUT = 6074;
const WORD	PCM_DISCONNECTPARTY_TOUT = 6075;
const WORD  IP_SEND_INTRA_TO_PARTY_TOUT = 6076;
const WORD  RTPCONTENTACKTOUT		= 6077; // RTP ack for Content On/Off tout
const WORD  RTPEVACUATEACKTOUT		= 6078; // RTP ack for Content On/Off tout
const WORD  SIP_CONTENT_PROVIDER_TOUT = 6079; // Sip initiation of content provider identity (owner) message timer.
const WORD  ADDSLAVEPARTY 	= 6080;
const WORD  PARTY_CONTROL_SLAVE_TO_MASTER 	= 6081;
const WORD  PARTY_CONTROL_MASTER_TO_SLAVE 	= 6082;
const WORD  PARTY_PARTYCONTROL_SLAVE_TO_MASTER 	= 6083;
const WORD  PARTY_PARTYCONTROL_MASTER_TO_SLAVE 	= 6084;
const WORD  PARTY_CONTROL_SLAVE_TO_MASTER_ACK 	= 6085;
const WORD  PARTYCONTROL_PARTY_SLAVE_TO_MASTER 	= 6086;
const WORD  PARTYCONTROL_PARTY_MASTER_TO_SLAVE 	= 6087;
const WORD  FORWARD_RMTH230						= 6088;
const WORD  SLAVE_SEND_RTCP_FAST_UPDATE			= 6089;
const WORD  NEWNAMEWITHROOMID 					= 6090;
const WORD  SLAVEPARTY_RSRCID 					= 6091;
const WORD  FALL_BACK_FROM_TIP_TO_REGULAR_SIP   = 6092;
const WORD  SLAVE_SEND_MONITORING_REQ			= 6093;
const WORD  CREATE_SLAVE_ACK_TOUT				= 6094;
const WORD  SIP_SEND_VIDEO_PREFERENCE_TOUT 		= 6095;
const WORD  DISCONNECT_SLAVE_ACK				= 6096;
const WORD  DISCONNECT_SLAVE_PARTY_TOUT			= 6097;
const WORD  DISCONNECT_SLAVE_ACK_TOUT			= 6098;
const WORD  LOGICALDELNETCHNL  = 6099;
const WORD  PARTYWELCOMEMSGTOUT  = 6100;
const WORD  PARTYVIDEOMSGTOUT	= 6101;
const WORD  ENDATTENDEDMODEPARTY = 6102;
const WORD  PARTYCHANGELEADERSTATUS = 6103;

//Multiple links for ITP in cascaded conference feature:
const WORD  ADDSUBLINKSPARTIES      = 6104;
const WORD  CONNECTLINKTOUT         = 6105;


const WORD UPGRADETOMIXTOUT		 =  6106;
const WORD SIP_SEND_VIDEO_PREFERENCE_END_TRANS_TOUT = 6107;
const WORD MSORGANIZERENDCONNECT = 6108;
const WORD  MSFOCUSENDCONNECT     = 6110;
const WORD  MSSUBSCRIBERENDCONNECT = 6111;
const WORD  MSFT_AVMCU2013DETECTED = 6112;
const WORD  SIP_MSFT_OUTSLAVES_CREATED = 6113;
const WORD  MSFOCUSENDDISCONNECT     = 6114;
const WORD  MSSUBSCRIBERENDDISCONNECT = 6115;


const WORD  PARTYENDCHANGEMODE   = 6116;
const WORD  PARTYCHANGEMODETOUT  = 6117;
const WORD  PARTYSTARTZEROMODE   = 6118;
const WORD  PARTYENDZEROMODE	 = 6119;
const WORD  DELNETCHNL			 = 6120;
const WORD  ENDDELNETCHNTL		 = 6121;
const WORD  FREENETRSRC			 = 6122;
const WORD  NETCHNLCONNECTED	 = 6123;
const WORD  UPDATELECTUREMODE	 = 6124;
const WORD  UPDATEPARTYVIDEOSRC	 = 6125;
const WORD  UPDATEPARTYMUXDESC	 = 6126;
const WORD  UPDATEALLPARTYSRC	 = 6127;
const WORD	IPPARTYMSECONDARY    = 6128;
const WORD	MFARESPONSE_TOUT  	 = 6129;
const WORD	UPDATELECTURERNAME   = 6130;
const WORD	TIP_NEGOTIATION_TOUT = 6131;
const WORD	TIP_WAIT_FALLBACK_TOUT = 6132;

//Multiple links for ITP in cascaded conference feature:
const WORD  ITPSPEAKERIND          = 6133;
const WORD  ITPSPEAKERACKIND       = 6134;
const WORD  TELEPRESENCE_PARTY_CONNECTION_TIMER   = 6135;
const WORD UNMUTE_MEDIA_AFTER_RESUME_TIMER          = 6136;
const WORD PARTY_TO_PARTYCONTROL_SLAVE				= 6137;
const WORD DISCONNECT_ALL_SLAVES_FROM_MASTER_PARTY_CONTROL = 6138;
const WORD  DISCONNECT_ALL_MS_SLAVES_TOUT		= 6139;
const WORD	CONTENT_WAIT_REINVITE_TOUT = 6140;



// Send MRMP channel handle:
const WORD SIP_PARTY_SEND_CHANNEL_HANDLE			= 6150;

///Update current FocusUri 
const WORD	UPDATEFOCUSURI   	= 6151;


const WORD  SETVIDSRC			= 6221;
const WORD  SETENDTIME		   = 6222;
const WORD  VIDREFRESH_VSW_ENC	   = 16223;
const WORD  VIDREFRESH		   = 6223;
const WORD  REJVIDREQ			= 6224;
const WORD  SETDATSRC			= 6225;
const WORD  LOOPBACK			 = 6226;
const WORD  DELVIDSRC			= 6227;
const WORD  BLNKVIDSRC		   = 6228;
const WORD  ADDVIDSRC			= 6229;
const WORD  CPSPEAKERON		  = 6230;
const WORD  CPSPEAKEROFF		 = 6231;
const WORD  ONAIRIND			 = 6232;
const WORD  CANCELONAIRIND	   = 6233;
const WORD  FREEZPIC			 = 6234;
const WORD  SEND_VIN			  	= 6235;
const WORD  AUTOTERMINATE		= 6236;
const WORD  SETMIHCAP			= 6237;
const WORD  INTRA_ASK			 = 6238;
const WORD  INTRA_SEND			 = 6239;
const WORD  SOFTWCPPARTYVIDREFRESH = 6240;

const WORD  MLPRETSTATUS		 = 6241;
const WORD  MLPCALLBACK		  = 6242;
const WORD  MLPTERMINATE		 = 6243;
const WORD  MLPEJECTFATAL		= 6244;
const WORD  BONDINGDOWNSPEED	 = 6245;

const WORD  CHANGEAUDIOVOLUMEMSG = 6246;
const WORD	UPDATEAUTOLAYOUT	 = 6247;
const WORD  WAIT_FOR_RSRC_AND_ASK_AGAIN = 6248;

const WORD  SEND_MMS			= 6249;
const WORD  SEND_MCC			= 6250;
// MVC cap support
const WORD  ACPTVISUALMVC		= 6251;
const WORD  REJVISUALMVC		 = 6252;

//Conf Spreading
const WORD  WAIT_FOR_BRIDGES_CONNECTION	= 6253;

// old PeopleContent support
const WORD  SETCONTENT			= 6255;
const WORD CONFASSIPTOUT                            = 6256;


//Auto Redial
const WORD  SETAUTOREDIAL =  6270;

const WORD  FAILADDPARTY		 = 6323;
const WORD  SCMCHANGEMODE		= 6324;

// VIN in cascade
const WORD  SENDINGVIN			 = 6325;
const WORD  H264CHANGERCVPROTOCOL = 6326;

const WORD  AUDCONNECT			= 6400;
const WORD  AUDCONTOUT			= 6402;
const WORD  AUDDISCONNECT		= 6403;
const WORD  AUDDISCONTOUT		= 6404;
const WORD  VIDCONNECT			= 6405;
const WORD  VIDCONTOUT			= 6406;
const WORD  VIDDISCONNECT		= 6407;
const WORD  VIDDISCONTOUT		= 6408;
const WORD  DATCONNECT			= 6409;
const WORD  DATCONTOUT			       = 6410;
const WORD  DATDISCONNECT		       = 6411;
const WORD  DATDISCONTOUT		       = 6412;
const WORD  WAITBEFOREUNMUTE	       = 6413;
const WORD  CONTENTCONNECT	    = 6414;
const WORD  CONTENTCONTOUT	    = 6415;
const WORD  CONTENTDISCONNECT   = 6416;
const WORD  CONTENTDISCONTOUT	= 6417;
const WORD  WINK_RECEIVED		= 6418;
const WORD  T1TONE_IND			= 6419;
const WORD  VIDDESTROY  		= 6420;
const WORD  CHANGETOUT		   = 6329;
const WORD  VIDEO_OUT_CHANGELAYOUT_TIMEOUT		= 6330;
const WORD  SITE_NAME_DISPLAY_OFF	= 6331;
const WORD  TEXT_ON_SCREEN_DISPLAY_OFF   = 6332;
const WORD  COP_NO_VIDEO_UPDATES_TOUT	= 6333;

const WORD  VIFRTOUT			 = 6334;
const WORD  SETAVMODE			= 6335;
const WORD  SETNODETYPE		  = 6336;
const WORD  H263VIDTOUT		  = 6337;
const WORD  CALLPROCEEDINGTOUT   = 6338;
const WORD  VIDREFRESHTOUT       = 6339;
const WORD  VPSYNCTOUT			 = 6340;
const WORD  MAPSYNC				 = 6341;
const WORD  BCHSYNC				 = 6342;
const WORD  DECSYNC				 = 6343;
const WORD  MAPSYNCTOUT		     = 6344;
const WORD  VCUVPTOUT			 = 6345; // Temp
const WORD  VPFURTOUT			 = 6346;

// New timer for delaying the disconnection process of a party for another T261TOUT timer.
const WORD  DELAYDELPC			 = 6347;
// Indicate l-video sync loss in delay
const WORD  DELAYSYNCINDTOUT      = 6348;
const WORD  CLOSEPORT             = 6349;
// COP
const WORD  COPVIDREFRESH		  = 6350;

const WORD  H264VIDTOUT		      = 6351;
const WORD  FREQUENTVIDREFRESH    = 6352;
const WORD  VIDEOREFRESHBEFORERECORDING = 6353;

// Repeated Intra
const WORD  ENCODER_RECURRENT_INTRA_REQ_TIMEOUT = 6354;
const WORD  DECODER_RECURRENT_INTRA_REQ_TIMEOUT = 6355;
const WORD  TIP_GRADUAL_TIMER					= 6356;

const WORD  CHANGE_MODE_LOOP                    = 6357;

//Video Relay
const WORD  VIDEO_OUT_CHANGESTREAMS_TIMEOUT		= 6360;
const WORD  STOP_SHOW_SLIDE_TIMEOUT             = 6361;

//FIR people timer
const WORD  FIR_PEOPLE_TIMER		= 6370;
const WORD FIR_TREATMENT_MAP_TIMER 					= 6371;

// Timer for returning a muted cell
const WORD MEDIA_DISCONNECTION_RESUME_CELL_TIMER = 6380;

// api for audioPlus
const WORD  DELETE_CONF_TIMEOUT				= 7000;
const WORD  GROUPONHOLD						= 7001;
const WORD  APORT_STATE_ASK					= 7002;
const WORD  MUTEINCOMINGPAERTIES			= 7003;
const WORD  DTMF_ASK						= 7004;
const WORD	JOIN_PARTY						= 7005;
const WORD	ROLL_CALL_TIMER					= 7006;
const WORD  PLAY_ROLL_CALL_MESSAGE			= 7007;
const WORD	DTMF_CREATE						= 7008;
const WORD	DEL_PARTY_AFTER_ROLL_CALL_TIMER	= 7009;
const WORD  PRINT_APPORTS					= 7010;
const WORD  SET_MUSIC_TO_SINGLE_PARTY		= 7011;
const WORD  UPDATE_PARTY_NOISE_DETECTION	= 7012;
const WORD  UPDATE_RECORDING_CONTROL		= 7013;
const WORD  DISCONNECT_RECORDING_LINK		= 7014;
const WORD  START_RECORDING_PROCESS			= 7015;
const WORD	STOP_RECORDING_PROCESS			= 7016;

const WORD	DTMF_CREATE_GATEWAY				= 7017;
const WORD  VTX_STATUS_IND					= 7018;
const WORD  INFORM_AUDIO_NET_CONNECTED		= 7019;

// New Audio Bridge OPCODES
const WORD  CONNECT_AUDIO_IN				= 7100;
const WORD  DISCONNECT_AUDIO_IN				= 7101;
const WORD  AUDIO_IN_CONNECTED				= 7102;
const WORD  AUDIO_IN_DISCONNECTED			= 7103;
const WORD  CONNECT_AUDIO_OUT				= 7104;
const WORD  DISCONNECT_AUDIO_OUT			= 7105;
const WORD  AUDIO_OUT_CONNECTED				= 7106;
const WORD  AUDIO_OUT_DISCONNECTED			= 7107;
const WORD  UPDATE_AUDIO_ALGORITHM			= 7108;
const WORD  UPDATE_MUTE						= 7109;
const WORD  UPDATE_AUDIO_VOLUME				= 7110;
const WORD  UPDATE_CONF_PARAMS				= 7111;
//const WORD  ACTIVE_SPEAKER_IND				= 7112;
//const WORD  AUDIO_SPEAKER_IND				= 7113;
const WORD	PARTY_AUDIO_CONNECTED			= 7114;
const WORD	PARTY_AUDIO_DISCONNECTED		= 7115;
const WORD  PARTY_AUDIO_EXPORTED			= 7116;
const WORD  AUDIO_EXPORT					= 7117;
const WORD  UPDATE_STANDALONE				= 7118;
const WORD	UPDATE_NOISE_DETECTION			= 7119;
const WORD  INCREASE_AUDIO_VOLUME			= 7120;
const WORD  DECREASE_AUDIO_VOLUME			= 7121;
const WORD	AUDIO_IN_VOLUME_CHANGED			= 7122;
const WORD	AUDIO_OUT_VOLUME_CHANGED		= 7123;
const WORD CONNECT_LEGACY_TO_SAC_TRANSLATOR           = 7124;
const WORD DISCONNECT_LEGACY_TO_SAC_TRANSLATOR        = 7125;
const WORD UPDATE_RELAY_AUDIO_PARAMETERS              = 7126;
const WORD LEGACY_TO_SAC_TRANSLATOR_CONNECTED         = 7127;
const WORD LEGACY_TO_SAC_TRANSLATOR_DISCONNECTED      = 7128;
const WORD CONNECT_AVC_TO_SVC_ART_TRANSLATOR          = 7129;
const WORD DISCONNECT_AVC_TO_SVC_ART_TRANSLATOR       = 7130;
const WORD DISCONNECT_AVC_TO_SVC_ART_TRANSLATOR_TOUT  = 7131;
const WORD UPDATE_USE_SPEAKER_SSRC_FOR_TX             = 7132;
const WORD UPDATE_ACTIVE_SPEAKERS_LIST           	= 7133;
const WORD UPDATE_AUDIO_ON_SEEN_IMAGE				= 7134;
const WORD UPDATE_MEDIA_TYPE			            = 7135;

// New Video Bridge OPCODES
const WORD  CONNECT_VIDEO_IN				 = 7200;
const WORD  CONNECT_VIDEO_OUT				 = 7201;
const WORD  DISCONNECT_VIDEO_IN				 = 7202;
const WORD  DISCONNECT_VIDEO_OUT			 = 7203;
const WORD  VIDEO_IN_CONNECTED				 = 7204;
const WORD  VIDEO_OUT_CONNECTED				 = 7205;
const WORD	VIDEO_IN_DISCONNECTED			 = 7206;
const WORD  VIDEO_OUT_DISCONNECTED			 = 7207;
const WORD  PARTYLAYOUTCHANGED				 = 7208;
const WORD	VIDEO_IN_SYNCED					 = 7209;
const WORD  PRIVATELAYOUT_ONOFF_CHANGED		 = 7210;
const WORD  SETPRIVATEVIDLAYOUT				 = 7211;
const WORD  SETPRIVATEVIDLAYOUTONOFF		 = 7212;
const WORD	PARTY_VIDEO_CONNECTED			 = 7213;
const WORD	PARTY_VIDEO_DISCONNECTED		 = 7214;
const WORD  VIDEO_DECODER_SYNC				 = 7215;
const WORD  ENDCONNECTPARTY_IVR_MODE	     = 7216;
const WORD  PARTY_VIDEO_IVR_MODE_CONNECTED	 = 7217;
const WORD  PARTY_VIDEO_EXPORTED			 = 7218;
const WORD  VIDEO_EXPORT					 = 7219;
const WORD	IMAGE_IN_CELL_ZERO_CHANGED		 = 7220;
const WORD	PARTY_VIDEO_IN_UPDATED			 = 7221;
const WORD	PARTY_VIDEO_OUT_UPDATED			 = 7222;
const WORD  UPDATE_VIDEO_IN_PARAMS			 = 7223;
const WORD  UPDATE_VIDEO_OUT_PARAMS			 = 7224;
const WORD  ADDIMAGE                     	 = 7225;
const WORD  DELIMAGE                     	 = 7226;
const WORD  MUTEIMAGE                    	 = 7227;
const WORD  UNMUTEIMAGE                 	 = 7228;
//const WORD  CHANGESPEAKER                	 = 7229;
const WORD  CHANGECONFLAYOUT             	 = 7230;
const WORD  CHANGEPARTYLAYOUT				 = 7231;
const WORD  CHANGEPARTYPRIVATELAYOUT		 = 7232;
const WORD  SETPARTYPRIVATELAYOUTONOFF   	 = 7233;
const WORD  FASTUPDATE						 = 7234;
const WORD  PLC_SETPARTYPRIVATELAYOUTTYPE	 = 7235;
const WORD  PLC_FORCECELLZERO				 = 7236;
const WORD  PLC_CANCELALLPRIVATELAYOUTFORCES = 7237;
const WORD  PLC_RETURNPARTYTOCONFLAYOUT		 = 7238;
const WORD  ENCODER_RESOLUTION_CHANGED		 = 7239;
const WORD	UPDATE_PARTY_LECTURE_MODE_ROLE	 = 7240;
const WORD  REJECT_PLC						 = 7241;
const WORD  AUDIO_SPEAKER_CHANGED			 = 7242;
const WORD  SPEAKERS_CHANGED     			 = 7243;
const WORD  IVR_JOIN_CONF_VIDEO				 = 7244;
const WORD	DELETED_PARTY_FROM_CONF			 = 7245;
const WORD	SETCONFVIDLAYOUT_SEEMEALL		 = 7246;
const WORD	SETCONFVIDLAYOUT_SEEMEPARTY		 = 7247;
const WORD	UPDATE_DECODER_DETECTED_MODE	 = 7248;
const WORD	END_CHANGE_LAYOUT				 = 7249;
const WORD  SET_PARTY_FORCE                  = 7250;
const WORD  DISPLAY_TEXT_ON_SCREEN			 = 7251;
const WORD  SLIDE_INTRA_TOUT				 = 7252;
const WORD  SEND_H239_VIDEO_CAPS			 = 7253;
const WORD  UPDATE_VIDEO_CLARITY             = 7254;
// LPR
const WORD  PARTY_LPR_VIDEO_OUT_RATE_UPDATED = 7255;
//LEGACY
const WORD  CONTENT_BRIDGE_START_PRESENTATION = 7256;
const WORD  CONTENT_BRIDGE_STOP_PRESENTATION  = 7257;
const WORD  ENDCONNECT_CONTENT_DECODER        = 7258;
const WORD  END_DISCONNECT_CONTENT_DECODER    = 7259;
const WORD  END_DESTROY_CONTENT_DECODER       = 7260;
const WORD  CONTENT_DECODER_VIDEO_IN_SYNCED          = 7261;
const WORD  CONTENT_DECODER_SYNC_LOST                = 7262;
const WORD  ADD_CONTENT_IMAGE                        = 7263;
const WORD  DEL_CONTENT_IMAGE                        = 7264;
const WORD  CONTENT_DECODER_ALLOC_RSRC_FAIL          = 7265;
const WORD  CONTENT_DECODER_RESET_FAIL_STATUS        = 7266;


//COP
const WORD  END_CONNECT_COP_ENCODER  			     = 7267;
const WORD  END_DISCONNECT_COP_ENCODER               = 7268;
const WORD  END_CONNECT_COP_DECODER  			     = 7269;
const WORD  END_DISCONNECT_COP_DECODER               = 7270;
const WORD  CHANGECOPLAYOUT                          = 7271;
const WORD  CHANGECOPLAYOUTATTRIBUTES                = 7272;
const WORD  VIDCLOSE								 = 7273;
const WORD  END_CLOSE_COP_DECODER					 = 7274;
const WORD  CLOSE_VIDEO_IN							 = 7275;
const WORD  VIDEO_IN_CLOSED							 = 7276;
const WORD  VIDEO_REFRESH_COP_DECODER                = 7277;
const WORD  COP_VIDEO_IN_CHANGE_MODE                 = 7278;
const WORD  VIDEO_IN_SYNCED_COP_DECODER				 = 7279;
const WORD  SET_MESSAGE_OVERLAY		               	 = 7280;

const WORD  SET_AUTOSCAN_INTERVAL					 = 7281;
const WORD  SET_AUTOSCAN_ORDER						 = 7282;
const WORD  UPDATE_FLOW_CONTROL_RATE	             = 7283;
const WORD  COP_VIDEO_OUT_CHANGE_MODE	             = 7284;

const WORD  START_LOOK_FOR_ACTIVE_SPEAKER            = 7285;
const WORD  SET_HIDE_TEXT_BOX						 = 7286;
const WORD  COP_ENCODER_VIDEO_OUT_UPDATED			 = 7287;
const WORD  COP_UPDATE_CASCADE_LINK_LECTURE_MODE     = 7288;
const WORD COP_START_CASCADE_LINK_LECTURE_MODE      = 7289;

// PCM opcodes inside Video Bridge
const WORD  PCM_CONNECTED							 = 7290;
const WORD	PCM_DISCONNECTED						 = 7291;
const WORD  PCM_UPDATED								 = 7292;
const WORD	CONNECT_PARTY_TO_PCM					 = 7293;
const WORD	DISCONNECT_PARTY_FROM_PCM				 = 7294;
const WORD	CHANGE_SPEAKER_NOTATION_PCM_FECC		 = 7295;
// API PCM <--> PartyCntl
const WORD	PCM_PARTY_STATE_CHANGED					 = 7296;

const WORD	PARTY_IMAGE_UPDATED			 	 = 7297;
const WORD  UPDATEIMAGE                 	 = 7298;
const WORD  VIDEO_GRAPHICS_SHOW_ICON                 = 7299;

// New FECC Bridge OPCODES
const WORD	FECC_PARTY_BRIDGE_CONNECTED		= 7300;
const WORD	FECC_PARTY_BRIDGE_DISCONNECTED	= 7301;

// Content Bridge OPCODES
const WORD	PARTY_CONTENT_CONNECTED		= 7310;
const WORD	PARTY_CONTENT_DISCONNECTED	= 7311;
const WORD	PARTY_CONTENT_DISCONNECTED_SLAVE_ACTIVE	= 7312;

// VENUS
const WORD  VENUS_SETPARTYPRIVATELAYOUTTYPE		= 7313;
const WORD  VENUS_FORCECELLZERO				 	= 7314;
const WORD  VENUS_CANCELALLPRIVATELAYOUTFORCES	= 7315;
const WORD  VENUS_RETURNPARTYTOCONFLAYOUT		= 7316;
const WORD  REJECT_VENUS						= 7317;

const WORD  PARTY_IVR_MODE_ON_RESUME		 = 7330;
const WORD  PARTY_CONNECT_AUDIO_ON_RESUME	 = 7331;
const WORD  END_PARTY_IVR_MODE_ON_RESUME	 = 7332;
const WORD  PARTY_ON_HOLD_IND				 = 7333;
const WORD  PARTY_RESUMING_FROM_HOLD		 = 7334;

// layout management for telepresence sublinks (calculated in the main link for all room links, and sent to each sublink)
const WORD  CHANGEPARTYLAYOUT_TPROOM_SUBLINK = 7335;


// TelePresence
const WORD TURN_ON_OFF_TELEPRESENCE                  = 7400;
const WORD UPDATE_PARTY_TELEPRESENCE_MODE            = 7401;
const WORD UPDATE_AUTO_BRIGHTNESS                    = 7402;

// Continue New Video Bridge OPCODES
const WORD SET_PARTY_MESSAGE_OVERLAY                 = 7403;
const WORD SET_SITE_NAME                             = 7404;
const WORD REFRESHLAYOUT                             = 7405;

// Indication on Layout
const WORD NOTIFY_VB_ON_NETWORK_QUALITY_CHANGE       = 7406; // VB incoming request for the Network Quality only update
const WORD INDICATION_ICONS_CHANGE                   = 7407; // generic outgoing request
const WORD  UPDATEONIMAGESVCTOAVC					=7408;
const WORD  UPDATEONIMAGEAVCTOSVC					=7409;
// XCode
const WORD PARTY_XCODE_CONNECTED                      = 7410;
const WORD PARTY_XCODE_DISCONNECTED                   = 7411;
const WORD XCODE_DISCONNECTPARTY_TOUT				  = 7412;

const WORD GET_PARTY_VIDEO_DATA_REQ                 = 7413;
const WORD GET_PARTY_VIDEO_DATA_IND                 = 7414;

const WORD UPDATE_LAYOUT_HANDLER_TYPE				= 7415;


//VNGR-26449 - unencrypted conference message
const WORD SET_ALL_PARTIES_SECURE_MESSAGE 			 = 7450;
const WORD STOP_PARTY_SECURE_MESSAGE				 = 7451;
const WORD CONF_SECURE_MESSAGE_TIMER				 = 7452;
const WORD CONF_SECURE_MESSAGE_DURATION              = 7453;
const WORD CONF_MESSAGE_OVERLAY_TIMER				 = 7454;
const WORD SECUREMESSAGEDURATION					 = 7455;

//Multiple links for ITP in cascaded conference feature:
const WORD  NEW_ITP_SPEAKER_IND              = 7500;

 // api for chair brdg  controller
const WORD CHAIRTOKENREQ	= 8600;
const WORD CHAIRTOKENRELEASE	= 8601;
const WORD CHAIRDROPPARTY= 8602;
const WORD CHAIRDROPCONF = 8603;
const WORD CHAIRVIDBROADCAST= 8604;
const WORD CHAIRTOKENWITHDRAWAL= 8605;
const WORD CHAIRFLOORREQ= 8606;
const WORD CHAIRCONNECT= 8607;
const WORD CHAIRDISCONNECT= 8608;
const WORD CHAIRTOKENACCEPT= 8609;
const WORD CHAIRTOKENREJECT= 8610;
const WORD CHAIRTCUREQ	 = 8611;
const WORD CHAIRTILACCEPT   =8612;
const WORD MBECMD		   =8613;
const WORD SBECMD		   =8614;
const WORD PARTYSTRINGCMD   =8615;
const WORD INDICATESTRING   =8616;
const WORD PARTYIDENTIFYCMD =8617;
const WORD PARTYPERSONALIDENT =8618;
const WORD PARTYINDNUMINFO=8619;
const WORD CHAIRTOKENRELEASEREQ	= 8620;
const WORD INDICATETERMINALNUM	= 8621;
const WORD INDICATEDROPTERMINALNUM	= 8622;
const WORD TERMINALCOMMANDUPDATE=8623;
const WORD TERMINALINDASSIGNMENT=8624;
const WORD INDICATEPERSONALIDENT =8625;
const WORD TERMINALEXTENSIONADDRESS = 8626;
const WORD CHAIRCANCELVIDBROADCAST= 8627;
const WORD NUMBERINGMESSAGE       = 8628;

// Concerning cascade situation
const WORD CANCELMULTIPOINTINDMASTER =8700;
const WORD MULTIPOINTINDMASTER	   =8701;
const WORD MULTIPOINTCOMMANDCONFERENCE =8702;
const WORD TERMINALINDLIST			 =8703;
//const WORD TERMINALCOMMANDUPDATE	   =8704;
const WORD TERMINLINDENDOFLIST		 =8705;
const WORD MULTIPOINTINDJOINEDREALCONF =8706;
const WORD RANDOMNUMBER				=8707;
const WORD CHAIRINDICATERESPONSE	   =8708;
const WORD TERMINATECONF			   =8709;
const WORD TOKENCOMMANDASSOCIATION	 =8710;
const WORD CANCELMULTIPOINTCOMMANDCONFERENCE =8711;
const WORD MULTIPOINTINDHIERARCHY	   =8712;
const WORD MULTIINDVISUALIZE           =8713;
const WORD CANCELMULTIINDVISUALIZE     =8714;


const WORD  CONTENT_DECODER_DISCONNECTED             = 8730;


//mcu get til only in cascade situation

const WORD PARTYTCS4STRINGCMD               = 8630;
const WORD TCS_4STRING                      = 8631;
const WORD EXTENSIONADDRESS                 = 8632;
const WORD TERMGWCONF                       = 8633;
const WORD IISSENT                          = 8634;
const WORD PARTYVIDBRDGDISVDTOTR            = 8636;
const WORD INFORMATIONINDICATIONSRTING      = 8637;
const WORD H323CALLCONNECTEDIND             = 8638;
const WORD ENDGWSETUP			            = 8639;
const WORD ENDGWPARTYSETUP			        = 8640;
const WORD ENDDTMFINVITEPARTYSETUP          = 8641;

// Api for CConnectedModeCntl
const WORD CHANGEMODEMSG  = 9101;
const WORD ENDCHANDESPEEDMSG = 9102;
const WORD ENDCHANGEMODEMSG  = 9103;

// Api for IP Terminal
//API of Lobby
const WORD ACCEPT_UNRESERVED_PARTY = 10000;
const WORD REJECT_UNRESERVED_PARTY = 10001;
const WORD RELEASE_UNRESERVED_PARTY = 10002;
const WORD REJECT_START_MEETING_ROOM = 10003;
const WORD END_CALL_PROCEEDING	   = 10004;
const WORD ADD_MULTI_INVITE			= 10005;
const WORD GK_LRQ_IND				= 10006;
const WORD START_MEETING_ROOM        = 10007;
const WORD RELEASE_RESERVED_PARTY    = 10008;
const WORD CONF_ON_AIR               = 10009;
const WORD START_GATEWAY_CONF        = 10010;
const WORD RELEASE_AVMCU_PARTY       = 10011;

//Move API (lobby / IVR
const WORD MOVE_PARTY_TO_CONF_OR_MR   = 10020;

//LOBBY
const WORD SUSPEND_IVR_PARTY          = 10021;
const WORD LOBBY_START_AD_HOC_CONF    = 10022;

const WORD START_MNG_ASSIST_TASK      = 10023;
const WORD PROCESS_MEMINFO_PRINT      = 10024;

const WORD PARTYSUSPENDTOUT		   = 10030;
//const WORD GATEWAYSUSPENDTOUT	   = 10030;  //both were 10010 yoella

const WORD CLEAN_FAILED_CONFERENCE = 10031;

const WORD CLEAN_FAILED_PARTY = 10032;

// Api for LoadMngr
const WORD NEWMESSAGE        = 12000;
const WORD TIMERDELETEOLD    = 12001;
const WORD LOADACCEPTMSGACK	 = 12002;

// Api for ContentCntl (Content bridge)
const OPCODE  NEWTOKENHOLDER		    =  12100;
const OPCODE  NOTOKENHOLDER				=  12101;
const OPCODE  PARTY_TOKEN_ACQUIRE	    =  12102;
const OPCODE  PARTY_TOKEN_RELEASE		=  12103;
const OPCODE  PARTY_TOKEN_WITHDRAW_ACK	=  12104;
const OPCODE  TOKEN_WITHDRAW			=  12105;
const OPCODE  ROLE_PROVIDER_IDENTITY	=  12106;
const OPCODE  MEDIA_PRODUCER_STATUS		=  12107;
const OPCODE  PARTY_CONTENT_RATE_CHANGED=  12108;
const OPCODE  STARTCONTENT				=  12109;
const OPCODE  STOPCONTENT				=  12110;
const OPCODE  EPC_SIMULATION_EVENT		=  12111;
const OPCODE  PARTY_BFCP_TOKEN_QUERY    =  12112;
const OPCODE  TOKENNOROLEPROVIDER		=  12113;
const OPCODE  PARTY_TOKEN_ACQUIRE_ACK     =  12114;
const OPCODE  PARTY_TOKEN_ACQUIRE_NAK     =  12115;
const OPCODE  PARTY_TOKEN_RELEASE_ACK     =  12116;
const OPCODE  PARTY_TOKEN_WITHDRAW        =  12117;
const OPCODE  PARTY_TOKEN_MESSAGE		  =  12118;
const OPCODE  FLOW_CONTROL_RELEASE_REQ	  =  12119;
const OPCODE  HW_CONTENT_ON_OFF_ACK	  =  12120;
const OPCODE  RTP_EVACUATE_ON_OFF_ACK	  =  12121;
const OPCODE  PARTY_IN_CONF_IND			  =  12122;
const OPCODE  UPDATE_PRESENTATION_OUT_STREAM  =  12123;
const OPCODE  PRESENTATION_OUT_STREAM_UPDATED =  12124;
const OPCODE  MASTER_START_CONTENT =  12125;
const OPCODE  MASTER_RATE_CHANGE   =  12126;
const OPCODE  FORWARD_TOKEN_MSG_TO_MASTER = 12127;
const OPCODE  LINK_CONNECT      = 12128;
const OPCODE  LINK_DISCONNECT   = 12129;
const OPCODE UPDATE_CONTENT_PROTOCOL = 12130;
const OPCODE FLOW_CONTROL_RELEASE_NAK = 12131;
const OPCODE  CG_PARTY_TOKEN_MESSAGE = 12132;	// for Call Generator

/* Api for Duo: */
//Api for H323Part
const WORD  PARTY_OPEN_DUO_IN			=  12140;
const WORD  PARTY_END_OPEN_DUO_IN       =  12141;
const WORD  PARTY_CLOSE_DUO_IN          =  12142;
const WORD  PARTY_END_CLOSE_DUO_IN      =  12143;
const WORD  PARTY_END_CLOSE_DUO_OUT     =  12144;
/* Api for ECS */
const WORD  PARTY_RECEIVE_ECS			=  12150;
/* Api for Faulty resources */
const WORD  PARTY_FAULTY_RSRC           =  12151;
const WORD  PARTY_FAULTY_PORT           =  12152;
//API FOR CALL GENERATOR
const WORD PARTY_CG_START_CONTENT       =  12153;
const WORD PARTY_CG_STOP_CONTENT        =  12154;
//Api for AppServer
const WORD  ON_CONNECT_SERVER			=  12200;

// Api for IP party
//msgs from controller to party
const WORD IP_RTP_DIFF_PAYLOAD_TYPE		=  12500;
const WORD DTMF_FWD_INVITOR_TOUT		=  12501;
const WORD DTMF_IVR_DELAY_TOUT  		=  12502;
const WORD PARTY_TRANSLATOR_ARTS_CONNECTED = 12503;
const WORD PARTY_TRANSLATOR_ARTS_DISCONNECTED = 12504;
const WORD H323_PARTY_CHANS_UPDATED		= 12505;
const WORD DTMF_IVR_CLEAR_BUFFER        = 12506;
const WORD UPDATE_MUTE_ICON  			= 12507;


// Api for Sip

// msgs from conf
const WORD SIP_CONF_ESTABLISH_CALL		=  13000;
const WORD SIP_CONF_CONNECT_CALL		=  13001;
const WORD SIP_CONF_DISCONNECT_CHANNELS =  13002;
const WORD SIP_CONF_BRIDGES_UPDATED		=  13003;
const WORD SIP_CONF_BRIDGES_UPDATED_RES =  13004;


const WORD PARTY_CONF_PWD_MSG_IND        = 13010;  // LyncCCS: Conf to Party
const WORD SIP_PARTY_CONF_PWD_STAUTS_ACK = 13011;  // LyncCCS: Party to Conf
const WORD SIP_PARTY_AUTH_PWD_STATUS     = 13012;  // LyncCCS: SipCntl to SipParty
const WORD CCS_PLUGIN_AUTH_TIMEOUT       = 13013;
const WORD LYNC_CONF_INFO_UPDATED        = 13014;  // Notification message from LyncEventManager to subscribers
const WORD SRS_RECORDING_CONTROL_IND       = 13015; //Session Recording Service: Con - > Party to send Recording control message
const WORD SRS_RECORDING_CONTROL_STATUS       = 13016; //Session Recording Service: SipCntl - > Party to send Recording control status
const WORD SRS_RECORDING_CONTROL_ACK       = 13017; //Session Recording Service: SipParty - > Conf to send Recording control status
const WORD SRS_LAYOUT_CONTROL_PARTY_LOCAL       = 13018; //Session Recording Service: SipCntl - > Party to send Layout change request
const WORD SRS_LAYOUT_CONTROL_PARTY_TO_CONF       = 13019; //Session Recording Service: SipParty - > Conf to send Layout change request



// msgs from EP
const WORD SIP_PARTY_CALL_CLOSED		=  13100;
const WORD SIP_PARTY_RMT_CLOSE_CALL		=  13101;
const WORD SIP_PARTY_CALL_FAILED		=  13102;
const WORD SIP_PARTY_CHANS_CONNECTED    =  13103;
const WORD SIP_PARTY_CHANS_DISCONNECTED	=  13104;
const WORD SIP_PARTY_RECEIVED_200OK		=  13105;
const WORD SIP_PARTY_RECEIVED_ACK		=  13106;
const WORD SIP_PARTY_BAD_STATUS			=  13107;
const WORD SIP_PARTY_RECEIVED_MONITOR   =  13108;
const WORD SIP_PARTY_ORIGINAL_RMOTCAP	=  13109;
const WORD SIP_PARTY_CHANS_UPDATED		=  13110;
const WORD SIP_PARTY_REINVITE_RESPONSE	=  13111;
const WORD SIP_PARTY_RECEIVED_REINVITE	=  13112;
const WORD SIP_PARTY_TRANSPORT_ERROR    =  13113;
const WORD SIP_RATE_CHANGE_BY_REMOTE    =  13114;
const WORD SIP_PARTY_UNMUTE_CHANNEL     =  13115;
const WORD SIP_PARTY_CALL_REINVITE		=  13116;
const WORD SIP_PARTY_SLAVES_RECAP_FINISHED = 13117;

const WORD SIP_PARTY_CHANS_START_DTLS	= 13119;
const WORD SIP_PARTY_PENDING_TRANS		=  13120; //BRIDGE-15745

// msgs - proxy manager
const WORD SIP_PROXY_REGISTER			=  13200;
const WORD SIP_PROXY_DUMP				=  13201;
const WORD KILLONECONF					=  13202;
const WORD SIP_SERVICE					=  13203;
const WORD SIP_SUBSCRIBE				=  13204;
const WORD REGISTRAR_STATUS				=  13205;

// msgs - Dns resolution
const WORD SIP_PARTY_DNS_RES			=  13250;
// Api for Recording Manager
const WORD REC_MNGR_DUMP				=  13300;
const WORD DELETE_RECORDING_FILE		=  13301;
const WORD DELETE_ALL_RECORDING_FILES	=  13302;
const WORD DELETE_RECORDING_DIRECTORY   =  13303;
const WORD UPDATE_FILE_REMARK			=  13304;
const WORD ADD_FILE_TO_DB				=  13305;
const WORD DEL_FILE_FROM_DB				=  13306;
const WORD INIT_DIRECTORIES_DB			=  13307;
const WORD BACKUP_APP_MSG_ERROR			=  13308;

// Api for H239 Cascade
const WORD END_MASTER_WAIT_FOR_RATE_CHANGE			=  13350;


// msgs from SipTransaction to SipParty
const WORD SIP_TRANSACTION_MSG				= 13400;
const WORD SIP_TRANS_END_TRANSACTION 		= 13401;
const WORD SIP_TRANS_PARTY_RECEIVE_RECAP	= 13402;
const WORD SIP_TRANS_UPDATE_CHANS_STATUS	= 13403;
const WORD SIP_TRANS_CHANS_CONNECTED		= 13404;
const WORD SIP_TRANS_REMOTE_CAPS_RECEIVED	= 13405;
const WORD SIP_TRANS_REMOTE_CONNECTED		= 13406;
const WORD SIP_TRANS_MUTE_MEDIA   			= 13407;
const WORD SIP_TRANS_ORIGINAL_RMOTCAP		= 13408;
const WORD SIP_TRANS_SITE_VISUAL_NAME		= 13409;
const WORD SIP_TRANS_UPDATE_ENC_STATUS		= 13410;
const WORD SIP_TRANS_HANDLE_CONNECTIVITY_CHECK 	= 13411;
const WORD SIP_TRANS_PARTY_CHANGE_VIDEO_RES = 13412;
const WORD SIP_TRANS_DISCONNECT_BRIDGES		= 13413;
const WORD SIP_TRANS_CONNECT_BRIDGES		= 13414;
const WORD SIP_TRANS_UPDATE_DB				= 13415;
const WORD SIP_TRANS_SLAVE_CLOSE_CHANS		   = 13416;
const WORD SIP_TRANS_SLAVE_OPEN_CHANS		   = 13417;
const WORD SIP_TRANS_SLAVE_UPDATE_CHANS		   = 13418;
const WORD SIP_TRANS_SEND_CHANNEL_HANDLE	   = 13419;
const WORD SIP_TRANS_SEND_TOKEN_RELEASE_FOR_HOLD  = 13420;
const WORD SIP_TRANS_PARTY_CHANGE_VIDEO_AFTER_VSR_MSG = 13421;
const WORD SIP_TRANS_SINGLE_UPDATE_PACSI_INFO_MSG = 13422;
const WORD SIP_TRANS_PARTY_LAST_TARGET_MODE_MSG = 13423;


// msgs from SipParty to SipTransaction
const WORD SIP_PARTY_ESTABLISH_CALL		=  13450;
const WORD SIP_PARTY_SEND_REINVITE		=  13451;




//CDR_MCCF:
const WORD SIP_PARTY_STATISTIC_INFO            =  13452;
const WORD IP_CM_PARTY_STATISTIC_INFO_IND_TOUT = 13453;
const WORD IP_CM_PARTY_WAITING_FOR_STATISTIC_INFO_IND = 13454;
const WORD SIP_PARTY_DTLS_STATUS		=  13455;

const WORD PARTY_UPGRADE_TO_MIXED		=  13456;
const WORD PARTY_UPGRADE_TO_MIX_CHANNELS_UPDATED =  13457;
const WORD H323_TRANS_END_TRANSACTION 		= 13458;
const WORD SIP_PARTY_DTLS_CHANS_DISCONNECTED	= 13459;

// msgs to TipRtcpCntl
const WORD SIP_PARTY_START_TIP_NEGOTIATION	= 13470;
const WORD SIP_PARTY_NEGOTIATION_HANDLED	= 13471;
const WORD SIP_PARTY_CLOSE_TIP_SESSION		= 13472;

// msgs from TipRtcpCntl
const WORD TIP_CNTL_NEGOTIATION_RESULT		= 13480;
const WORD TIP_CNTL_CONTENT_MSG_IND			= 13481;
const WORD TIP_CNTL_LAST_ACK_RECEIVED          = 13482;
const WORD SIP_PARTY_TIP_EARLY_PACKET   	= 13483;

// msgs for ICE
const WORD MAKE_ANSWER_IND				=  13500;
const WORD MAKE_OFFER_IND				=  13501;
const WORD ICE_PROCESS_ANS_IND			=  13502;
const WORD ICE_MODIFY_OFFER_IND			=  13503;
const WORD ICE_MODIFY_ANSWER_IND		=  13504;
const WORD CLOSE_ICE_SESSION_IND		=  13505;
const WORD ICE_CONN_CHECK_COMPLETE_IND  =  13506;
const WORD TRANS_ICE_CONN_CHECK_COMPLETE_IND = 13507;
const WORD UPDATEICEPARAMS				=  13508;
const WORD FALL_BACK_FROM_ICE_TO_SIP	= 13509;
const WORD ICE_BANDWIDTH_IND		    =  13510;
const WORD ICE_INSUFFICIENT_BANDWIDTH	=  13511;
const WORD UPDATE_REMOTE_CAPS_FROM_PARTY       = 13512;

// msgs from CS BFCP to SipControl
const WORD SIP_PARTY_BFCP_MSG_IND		=  13520;
const WORD SIP_PARTY_BFCP_TRANSPORT_IND	=  13521;
const WORD SIP_PARTY_BFCP_DELAY_ACK_MSG	=  13522;

// msg for RTCP
const WORD SIP_PARTY_UPDATE_VIDEO_PREFERENCE	=  13523;
const WORD SIP_TRANS_UPDATE_VIDEO_PREFERENCE	=  13524;
const WORD VIDEO_BRIDGE_UPDATED_WITH_NEW_RES	=  13525;
const WORD START_VIDEO_PREFERENCE	=  13526;
//msg for RTCP VSR

const WORD 	SIP_PARTY_VSR_MSG_IND =  13527;
const WORD 	SIP_PARTY_MULTI_VSR_REQ =  13528;
const WORD 	SIP_PARTY_SINGLE_VSR_MSG_IND =  13529;
//const WORD 	SLAVES_CONTROLLER_MSG =  ;
const WORD 	SINGLE_PACSI_INFO_IND =  13530;
const WORD 	FULL_PACSI_INFO_IND =  13531;
const WORD 	FULL_PACSI_INFO_TIMER =  13532;
const WORD  ACTIVE_MEDIA_FOR_AVMCU_LYNC = 13533;
const WORD 	SIP_TRANS_VSR_MSG_IND =  13534;


// msgs from BFCP control to SipControl

// msgs BFCP Control
const WORD	BFCP_START_REESTABLISH_CONNECTION	= 13550;
const WORD	BFCP_END_REESTABLISH_CONNECTION		= 13551;
const WORD	BFCP_MESSAGE_REQUEST_TOUT			= 13552;
const WORD  BFCP_HELLO_KEEP_ALIVE               = 13553;

//FEC
const WORD FECINTRATOUT							= 13600;

// Lync2013
const WORD VSR_INIT_ACK_TOUT							= 13700;
const WORD ADDMSSLAVEPARTY								= 13701;
const WORD PARTY_CONTROL_MS_SLAVE_TO_MAIN_ACK 			= 13702;
const WORD DELMSSLAVEPARTY								= 13703;
const WORD PARTY_CONTROL_ALL_MS_OUT_SLAVES_CONNECTED	= 13704;
const WORD PARTY_CONTROL_ALL_MS_IN_SLAVES_CONNECTED		= 13705;
const WORD PARTY_CONTROL_ALL_MS_SLAVES_DELETED			= 13706;
const WORD MS_LYNC_SLAVES_CONTROLLER_MSG				= 13707;
const WORD MS_LYNC_MAIN_PARTY_CNTL_MSG 					= 13708;
const WORD MS_LYNC_CONF_PARTY_CNTL_MSG 					= 13709;
const WORD PARTY_PARTYCONTROL_MSSLAVE_TO_MAIN			= 13710;
const WORD PARTY_CONTROL_MS_SLAVE_TO_MAIN_MSG 			= 13711;
const WORD MS_SLAVE_VIDEO_IN_SYNCED						= 13712;
const WORD MS_SLAVE_VIDREFRESH							= 13713;
		
const WORD CONNECT_MS_OUT_SLAVES_TIMER					= 13714;
const WORD CONNECT_MS_IN_SLAVES_TIMER					= 13715;

const WORD CAM_TO_IVR_PARTY_MEDIA_CONNECTED					= 13716;
const WORD CAM_TO_IVR_PARTY_MEDIA_DISCONNECTED					= 13717;

// Api for ConfParty Manager
// ConfAppManager EVENTS
const WORD FIRST_CAM_EVENTS				=  14000;
const WORD CAM_END_OF_FEATURE			=  14001;
const WORD LAST_CAM_EVENTS				=  14200;
// END ConfAppManager EVENTS

// PCMManager EVENTS
const WORD CHAIRPERSON_ENTERED			=  14201;
const WORD CHAIRPERSON_LEFT				=  14202;
const WORD FECC_KEY_IND					=  14203;
const WORD PARTY_CONNECTED_TO_PCM_ENCODER		=  14204;
const WORD PARTY_DISCONNECTED_FROM_PCM_ENCODER	=  14205;
const WORD DTMF_IND_PCM					=  14206;
const WORD PCM_RESOLUTION_CHANGED		=  14207;
const WORD PCM_INVITE_PARTY				=  14208;
const WORD PCM_CLICK_AND_VIEW			=  14209;
const WORD CHAIRPERSON_START_MOVE_FROM_CONF	=  14210;

// END PCMManager EVENTS

//AT&T
const WORD MCCF_IVR_START_DIALOG		=  14230;
const WORD ACK_PLAY_MESSAGE				=  14231;
const WORD ACK_SHOW_SLIDE				=  14232;
const WORD ACK_RECORD_PLAY_MESSAGE		=  14233; //IVR for TIP

// Content Command Listing
const OPCODE  CONTENT_ROLE_LABEL					= 15000;//0x8F;
const OPCODE  CONTENT_ROLE_TOKEN_ACQUIRE			= 15001;//0x90;
const OPCODE  CONTENT_ROLE_TOKEN_ACQUIRE_ACK		= 15002;//0x91;
const OPCODE  CONTENT_ROLE_TOKEN_ACQUIRE_NAK		= 15003;//0x92;
const OPCODE  CONTENT_ROLE_TOKEN_RELEASE			= 15004;//0x93;
const OPCODE  CONTENT_ROLE_TOKEN_RELEASE_ACK		= 15005;//0x94;
const OPCODE  CONTENT_ROLE_TOKEN_WITHDRAW			= 15006;//0x95;
const OPCODE  CONTENT_ROLE_TOKEN_WITHDRAW_ACK		= 15007;//0x96;
const OPCODE  CONTENT_ROLE_PROVIDER_IDENTITY		= 15008;//0x97;
const OPCODE  CONTENT_NO_ROLE_PROVIDER			    = 15009;//0x98;
const OPCODE  CONTENT_MEDIA_FLOW_CNTL_CONTENT		= 15010;//0x99;
const OPCODE  CONTENT_MEDIA_FLOW_CNTL_INDICATION	= 15011;//0x9A;
const OPCODE  CONTENT_ON							= 15012;//0x9B;
const OPCODE  CONTENT_RATE_CHANGE					= 15013;//0x9C;
const OPCODE  CONTENT_OFF							= 15014;//0x9D;
const OPCODE  CONTENT_H230_C_I					    = 15015;//0x9E;
const OPCODE  CONTENT_H230_MBE					    = 15016;//0x9F;
const OPCODE  CONTENT_PP_H221_ESC_TBL_ON			= 15017;//0xA0;
const OPCODE  CONTENT_PP_H221_ESC_TBL_OFF			= 15018;//0xA1;
const OPCODE  CONTENT_MEDIA_PRODUCER_STATUS		    = 15019;//0xA2;
const OPCODE  CONTENT_REQUEST_RATE_CHANGE			= 15020;//0xA3;
const OPCODE  SET_EXCLUSIVE_CONTENT					= 15021;//0xA4;//Restricted content
const OPCODE  REMOVE_EXCLUSIVE_CONTENT				= 15022;//0xA5;//Restricted content
const OPCODE  CONTENT_ROLE_TOKEN_PENDING			= 15023;
const OPCODE  CONTENT_ROLE_BFCP_HELLO				= 15024;
const OPCODE  CONTENT_ROLE_BFCP_HELLO_ACK			= 15025;
const OPCODE  CONTENT_ROLE_BFCP_ERROR				= 15026;
const OPCODE  CONTENT_ROLE_BFCP_FLOOR_REQ_STATUS_ACK = 15027;
const OPCODE  CONTENT_ROLE_BFCP_ERROR_ACK			= 15028;
const OPCODE  CONTENT_ROLE_BFCP_FLOOR_STATUS_ACK	= 15029;
const OPCODE  CONTENT_ROLE_BFCP_GOODBYE				= 15030;
const OPCODE  CONTENT_ROLE_BFCP_GOODBYE_ACK			= 15031;
const OPCODE  SET_MUTE_INCOMING_LECTURE_MODE		= 15032;//0xA4;//Restricted content
const OPCODE  SET_EXCLUSIVE_CONTENT_MODE			= 15033;//0xA4;//Restricted content
const OPCODE  CONTENT_SIM_CHANGE_RATE_FOR_LINKS		= 15034;//0xA5;//in switch content we need to notify links to restart content
//const OPCODE  SET_CONF_AVC_SVC_MEDIA_STATE			= 15035; // moved to OpcodesMcmsInternal.h - sent from RA to ConfParty
const OPCODE  SET_PARTY_AVC_SVC_MEDIA_STATE			= 15036;

// Gathering
const OPCODE  GATHERING_TEMPORARY_TIMER				= 15100;//0xA3FC;
const OPCODE  GATHERING_UPDATE_TIMER				= 15101;//0xA3FD;
const OPCODE  GATHERING_PARTY_CONNECTING_TIMER		= 15102;//0xA3FF;
const OPCODE  GATHERING_PARTY_CONNECTED_MSG			= 15103;//0xA3FF;
const OPCODE  CONFPARTY_IS_MCU_STARTUP_FINISHED_TIMER		= 15121;// 0x3B11

// VideoRelayBridgePartyCntl
const OPCODE  ADD_VIDEORELAY_IMAGE_TO_MIX 			= 15200;
const OPCODE  RELAY_IMAGE_SVC_AVC_TRANS_UPDATE		= 15201;
const OPCODE  ADD_AVC_IMAGE							= 15202;
const OPCODE  LAST_AVC_IMAGE_REMOVED				= 15203;
const OPCODE  SVC_AVC_TRANSLATOR_DISCONNECTED       = 15204;
const OPCODE  AVC_SVC_TRANSLATOR_DISCONNECTED       = 15205;
const OPCODE  NON_RELAY_IMAGE_AVC_SVC_TRANS_UPDATE	= 15206;
const OPCODE  SVC_AVC_TRANSLATOR_CONNECTED   	    = 15207;
const OPCODE  AVC_SVC_TRANSLATOR_CONNECTED 	        = 15208;

// VideoRelay Intra
const OPCODE  RELAY_ASK_ENDPOINT_FOR_INTRA			= 15210;
const OPCODE  RELAY_ASK_ENDPOINTS_FOR_INTRA			= 15211;
const OPCODE  RELAY_ENDPOINT_ASK_FOR_INTRA			= 15212;
const OPCODE  RELAY_EP_INTRA_SUPRESSION_TIMER		= 15213;

// VideoRelay SCP
const WORD SCP_REQUEST_BY_EP						= 15240;
const WORD SIP_PARTY_SCP_REQUEST_FROM_EP			= 15241;
const WORD SIP_PARTY_ACK_FOR__SCP_REQ				= 15242;
const WORD SCP_NOTIFICATION_REQ						= 15243;
const WORD SIP_PARTY_SCP_NOTIFICATION_ACK_FROM_EP	= 15244;
const WORD CONF_API_SCP_NOTIFICATION_ACK_FROM_EP	= 15245;
const WORD SCP_NOTIFICATION_REQ_TOUT				= 15246;
const WORD SCP_NOTIFICATION_TO_MRMP_REQ				= 15247;
const WORD SIP_PARTY_SCP_NOTIFICATION_IND_FROM_EP	= 15248;
const WORD SCP_NOTIFICATION_BY_EP					= 15249;
const WORD SIP_PARTY_ACK_FOR_SCP_NOTIFICATION_IND	= 15250;
const WORD UPDATE_SCM_STREAMS                       = 15251;
const WORD SCP_IVR_SHOW_SLIDE_REQ					= 15252;	// From VB to PartyCntl
const WORD SCP_IVR_STOP_SHOW_SLIDE_REQ				= 15253;	// From VB to PartyCntl
const WORD SCP_IVR_STATE_NOTIFICATION_REQ			= 15254; 	// From PartyCntl to Party
const WORD SCP_IVR_STATE_NOTIFICATION_REQ_TOUT			= 15255;
const WORD SCP_PIPES_MAPPING_NOTIFICATION_REQ			= 15256;
const WORD SCP_PIPES_MAPPING_NOTIFICATION_REQ_TOUT		= 15257;
const WORD SCP_PIPES_MAPPING_NOTIFICATION_TO_MRMP_REQ	= 15258;
const WORD ACK_ON_IVR_SCP_SHOW_SLIDE                    = 15259;    //From PartyCntl to VB
const WORD ACK_ON_IVR_SCP_STOP_SHOW_SLIDE               = 15260;    //From PartyCntl to VB

// Other Relay opcodes
const OPCODE UPDATE_ART_WITH_SSRC_REQ					= 15301;
const OPCODE UPDATE_ART_WITH_SSRC_ACK					= 15302;
const OPCODE START_AVC_TO_SVC_ART_TRANSLATOR            = 15303;
const OPCODE REMOVE_AVC_TO_SVC_ART_TRANSLATOR           = 15304;

const OPCODE SEND_MRMP_STREAM_IS_MUST_REQ               = 15305;
const OPCODE SEND_MRMP_STREAM_IS_MUST_ACK               = 15306;
const OPCODE REQUEST_SEND_CHANGE_LAYOUT       	        = 15307;

//VB continue:
const WORD UPDATE_MUTE_ALL_VIDEO_EXCEPT_LEADER          = 15308;
const WORD SET_PARTY_AS_LEADER_FOR_VB                   = 15309;
const WORD UPDATE_MUTE_ALL_INCOMING_VIDEO_EXCEPT_LEADER = 15310;

const WORD  CONF_AUDIO_NUMBER_INDICATION_GAP_TOUT      = 15401;
const WORD  CONF_AUDIO_NUMBER_INDICATION_DISPLAY_TOUT = 15402;
const WORD  PARTY_AUDIO_NUMBER_INDICATION_DISPLAY_TOUT = 15403;

/*Begin:added by Richer for BRIDGE-12062 ,2014.3.3*/
const WORD  VIDEORECOVERYDISCONNECTPARTYCORDING = 15405;
const WORD  VIDEORECOVERYBYE = 15406;
/*End:added by Richer for BRIDGE-12062 ,2014.3.3*/
//Custom slides for IVR
const WORD  CONFPARTY_CHECK_MCCF_SLIDE_PROCEEDING_TIMER = 15501;
const WORD  CONFPARTY_DELETE_USELESS_IVR_FILES_TIMER    = 15502;

// TELEPRESENCE_LAYOUTS
const WORD  SET_TELEPRESENCE_LAYOUT_MODE = 15407;

const WORD	SIP_WEBRTC_PARTY_CONNECT_REQ_TIMER 		= 15408;
const WORD	SIP_WEBRTC_PARTY_CONNECT_IND_TIMER 		= 15409;
const WORD	SIP_WEBRTC_PARTY_ESTABLISH_CALL = 15410;

// High Profile

// data & mlp types
const WORD  LSD                = 1;
const WORD  HSD                = 2;
const WORD  MLP                = 3;
const WORD  HMLP               = 4;
const WORD  VIDEO              = 5;
const WORD  AUDIO              = 6;
const WORD  CONTENT            = 7;

// LSD Modes
#define LSD_NONE                 1
#define LSD_DYNAMIC_6400_ONLY    2
#define LSD_DYNAMIC              3
#define LSD_FIXED                4
#define LSD_DYNAMIC_4800_ONLY    5


#endif   /*  _CONFPARTYOPCODES_H */
