#ifndef _COP_CONFPARTY_DEFS_
#define _COP_CONFPARTY_DEFS_

#define NUM_OF_LEVEL_ENCODERS 4
#define NUM_OF_COP_DECODERS   16

#define LM_DECODER_INDEX   17
#define VSW_DECODER_INDEX   18
#define VSW_ENCODER_INDEX   6

#endif //_COP_CONFPARTY_DEFS_
