//=================================================================================================
//
//Copyright (C) 2000 ACCORD Networks Ltd.
//This file contains confidential information proprietary to ACCORD Networks Ltd. The use or 
//disclosure of any information contained in this file without the written consent of an officer of
//ACCORD Networks Ltd. is expressly forbidden.
//
//=================================================================================================

//=================================================================================================
//
//Module Name:  PartyVoice.h
//
//General Description:  
//
//    1. 
//    2.
//
//Generated By: Natalie                            Date: 14.05.00
//
//Revisions and Updates: 
//
//Date         Updated By         Description
//========   ==============   =====================================================================

//=================================================================================================

#ifndef _ISDNVOICEPARTY_H
#define _ISDNVOICEPARTY_H

//===== Include Files =====
#include  "IsdnParty.h"

extern  const char* GetStatusAsString(const int status);

class CIsdnVoiceParty : public CIsdnParty
{
	CLASS_TYPE_1(CIsdnVoiceParty, CIsdnParty)
public:             
	// Constructors
	CIsdnVoiceParty();
	virtual ~CIsdnVoiceParty();  
	virtual const char* NameOf() const { return "CIsdnVoiceParty";}
	virtual void PartySpecfiedIvrDelay();
	
	// Initializations
	void  Create(CSegment& appParam);	

	// Operations
protected: 
	// Attributes 
	void  OnConfDelNetCntl(CSegment* pParam);
	void  OnConfDelNetCntlIdle(CSegment* pParam);
	void  OnConfDelNetCntl_CauseOFRSR_DIFF(CSegment* pParam);
	void  ReplayToNetWhenNoResource(DWORD opcode,CIsdnNetSetup & netSetup)const;
	void  OnConfDelNetCntlChangeStateToRsrDiff(CSegment* pParam);
	void  OnPartyUpdateConfRsrcIdForInterfaceAnycase(CSegment* pParam);
	void  OnConfDisconnectANYSTATE(CSegment* pParam);
//	void  OnAudioPlusVTXStatusIndConnect(CSegment* pParam);
//	void  StartVTXSetup();

	void  ConnectHardware();
	
	PDECLAR_MESSAGE_MAP   
};

#endif /* _ISDNVOICEPARTY_H */
