//=================================================================================================
//
//Copyright (C) 2005 POLYCOM Networks Ltd.
//This file contains confidential information proprietary to POLYCOM Networks Ltd. The use or 
//disclosure of any information contained in this file without the written consent of an officer of
//POLYCOM Networks Ltd. is expressly forbidden.
//
//=================================================================================================

//=================================================================================================
//
//Module Name:  IvrApiCommandCreator.H
//
//
//Generated By: Amir         Date: 16.06.05
//
//=================================================================================================

#ifndef __IVRINTERFACE_H__
#define __IVRINTERFACE_H__

#include "IvrApiStructures.h"

//////////////////////////////////////////////////////
//				CIvrInterface	
//////////////////////////////////////////////////////
class CIvrApiCommandCreator
{
public:             
	// Constructors
	CIvrApiCommandCreator() {}
	~CIvrApiCommandCreator() {}
	
public:
	// Play Message
	int PreparePlayMessageBase();
	int PreparePlayMessageConf();
	int PreparePlayMessageParty( SIVRPlayMessageStruct* pm );


/*
	int PreparePlayMessageConf();
	int PreparePlayMessageParty();
	int PrepareStopPlayMessage();
	// Play Music
	int PreparePlayMusicBase();
	int PreparePlayMusicConf();
	int PreparePlayMusicParty();
	int PrepareStopPlayMusic();
	// Play Tone
	int PreparePlayToneBase();
	int PreparePlayToneConf();
	int PreparePlayToneParty();
	// DTMF
	int PrepareSendDTMF();
	// Roll-Call
	int PrepareRollCallRecord();
	int PrepareRollCallReviewBasic();
	int PrepareRollCallReviewConf();
	int PrepareRollCallReviewParty();
	// Slide
	int PrepareShowSlide();
	int PrepareStopSlide();
*/
// public variables
public:  

// protected variables
protected: 

};





#endif	// __IVRINTERFACE_H__ 

