#ifndef AUDIOAPIDEFINITIONSSTRINGS_H_
#define AUDIOAPIDEFINITIONSSTRINGS_H_

static const char* EAudioAlgorithmNames[] =
{
	"E_AUDIO_ALGORITHM_DUMMY",
	"E_AUDIO_ALGORITHM_UNCOMPRESSED",
	"E_AUDIO_ALGORITHM_HALF_COMPRESSED",
	"E_AUDIO_ALGORITHM_G711A_64",
	"E_AUDIO_ALGORITHM_G711A_56",
	"E_AUDIO_ALGORITHM_G711A_48",
	"E_AUDIO_ALGORITHM_G711U_64",
	"E_AUDIO_ALGORITHM_G711U_56",
	"E_AUDIO_ALGORITHM_G711U_48",
	"E_AUDIO_ALGORITHM_G722_64",
	"E_AUDIO_ALGORITHM_G722_56",
	"E_AUDIO_ALGORITHM_G722_48",
	"E_AUDIO_ALGORITHM_G722_Stereo_128",
	"E_AUDIO_ALGORITHM_G7221_16",
	"E_AUDIO_ALGORITHM_G7221_24",
	"E_AUDIO_ALGORITHM_G7221_32",
	"E_AUDIO_ALGORITHM_G7222_0660",
	"E_AUDIO_ALGORITHM_G7222_0885",
	"E_AUDIO_ALGORITHM_G7222_1265",
	"E_AUDIO_ALGORITHM_G7222_1425",
	"E_AUDIO_ALGORITHM_G7222_1585",
	"E_AUDIO_ALGORITHM_G7222_1825",
	"E_AUDIO_ALGORITHM_G7222_1985",
	"E_AUDIO_ALGORITHM_G7222_2305",
	"E_AUDIO_ALGORITHM_G7222_2385",
	"E_AUDIO_ALGORITHM_G723_53",
	"E_AUDIO_ALGORITHM_G723_63",
	"E_AUDIO_ALGORITHM_G728",
	"E_AUDIO_ALGORITHM_G729",
	"E_AUDIO_ALGORITHM_SIREN7_16",
	"E_AUDIO_ALGORITHM_SIREN7_24",
	"E_AUDIO_ALGORITHM_SIREN7_32",
	"E_AUDIO_ALGORITHM_SIREN14_24",
	"E_AUDIO_ALGORITHM_SIREN14_32",
	"E_AUDIO_ALGORITHM_SIREN14_48",
	"E_AUDIO_ALGORITHM_G7221C_24",
	"E_AUDIO_ALGORITHM_G7221C_32",
	"E_AUDIO_ALGORITHM_G7221C_48",
	"E_AUDIO_ALGORITHM_SIREN14S_48",
	"E_AUDIO_ALGORITHM_SIREN14S_56",
	"E_AUDIO_ALGORITHM_SIREN14S_64",
	"E_AUDIO_ALGORITHM_SIREN14S_96",
	"E_AUDIO_ALGORITHM_G719_32",
	"E_AUDIO_ALGORITHM_G719_48",
	"E_AUDIO_ALGORITHM_G719_64",
	"E_AUDIO_ALGORITHM_SIREN22_32",
	"E_AUDIO_ALGORITHM_SIREN22_48",
	"E_AUDIO_ALGORITHM_SIREN22_64",
	"E_AUDIO_ALGORITHM_G719S_64",
	"E_AUDIO_ALGORITHM_G719S_96",
	"E_AUDIO_ALGORITHM_G719S_128",
	"E_AUDIO_ALGORITHM_SIREN22S_64",
	"E_AUDIO_ALGORITHM_SIREN22S_96",
	"E_AUDIO_ALGORITHM_SIREN22S_128",
	"E_AUDIO_ALGORITHM_SIRENLPR_32",
	"E_AUDIO_ALGORITHM_SIRENLPR_48",
	"E_AUDIO_ALGORITHM_SIRENLPR_64",
	"E_AUDIO_ALGORITHM_SIRENLPRStereo_64",
	"E_AUDIO_ALGORITHM_SIRENLPRStereo_96",
	"E_AUDIO_ALGORITHM_SIRENLPRStereo_128",
	// TIP
	"E_AUDIO_ALGORITHM_AAC_LD",
	// Relay
	"E_AUDIO_ALGORITHM_SAC_32",
	"E_AUDIO_ALGORITHM_SAC_48",
	"E_AUDIO_ALGORITHM_SAC_64",
	"E_AUDIO_ALGORITHM_SAC_Stereo_64",
	"E_AUDIO_ALGORITHM_SAC_Stereo_96",
	"E_AUDIO_ALGORITHM_SAC_Stereo_128",

	// iLBC
	"E_AUDIO_ALGORITHM_iLBC_13"
	"E_AUDIO_ALGORITHM_iLBC_15"

    // opus
    "E_AUDIO_ALGORITHM_OPUS_64",   			// 68
    "E_AUDIO_ALGORITHM_OPUS_Stereo_128"		// 69
};


static const char * ESampleRateNames[] =
{
	"E_SAMPLE_RATE_DUMMY",
	"E_SAMPLE_RATE_8KHZ",
	"E_SAMPLE_RATE_16KHZ",
	"E_SAMPLE_RATE_32KHZ",
	"E_SAMPLE_RATE_48KHZ"
};


static const char * EAudioConnectionStatusNames[] =
{
	"E_AUDIO_CONNECTION_STATUS_DUMMY",
	"E_AUDIO_CONNECTION_STATUS_UNUSED",
	"E_AUDIO_CONNECTION_STATUS_NOT_CONNECTED",
	"E_AUDIO_CONNECTION_STATUS_SILENT",
	"E_AUDIO_CONNECTION_STATUS_BLOCKED",
	"E_AUDIO_CONNECTION_STATUS_LOOP",
	"E_AUDIO_CONNECTION_STATUS_MIX",
	"E_AUDIO_CONNECTION_STATUS_FORCE",
	"E_AUDIO_CONNECTION_STATUS_EXCLUSIVE",
	"E_AUDIO_CONNECTION_STATUS_MUSICED",
	"E_AUDIO_CONNECTION_STATUS_NOISY_MIX"
};


static const char * EPartyMediaTypeNames[] =
{
	"E_PARTY_MEDIA_TYPE_DUMMY",
	"E_PARTY_MEDIA_TYPE_AUDIO",
	"E_PARTY_MEDIA_TYPE_VIDEO"
};


static const char * EAudioChannelTypeNames[] =
{
	"E_AUDIO_CHANNEL_TYPE_DUMMY",
	"E_AUDIO_CHANNEL_TYPE_DECODER",
	"E_AUDIO_CHANNEL_TYPE_ENCODER",
	"E_AUDIO_CHANNEL_TYPE_CONFERENCE_MUSIC",
	"E_AUDIO_CHANNEL_TYPE_CONFERENCE_IVR",
	"E_AUDIO_CHANNEL_TYPE_PARTICIPANT_MUSIC",
	"E_AUDIO_CHANNEL_TYPE_PARTICIPANT_IVR"
};


static const char * EMediaTypeUpdateNames[] =
{
	"E_MEDIA_TYPE_UPDAETE_NO_NEED",
	"E_MEDIA_TYPE_AUDIO_TO_VIDEO",
	"E_MEDIA_TYPE_VIDEO_TO_AUDIO"
};

static const char * EAudioGainPresetNames[] =
{
	"E_AUDIO_GAIN_PRESET_DUMMY",
	"E_AUDIO_GAIN_PRESET_0",
	"E_AUDIO_GAIN_PRESET_1",
	"E_AUDIO_GAIN_PRESET_2",
	"E_AUDIO_GAIN_PRESET_3",
	"E_AUDIO_GAIN_PRESET_4",
	"E_AUDIO_GAIN_PRESET_5",
	"E_AUDIO_GAIN_PRESET_6",
	"E_AUDIO_GAIN_PRESET_7",
	"E_AUDIO_GAIN_PRESET_8",
	"E_AUDIO_GAIN_PRESET_9",
	"E_AUDIO_GAIN_PRESET_10"
};


static const char * ENoiseDetectionThresholdNames[] =
{
	"E_NOISE_DETECTION_THRESHOLD_DUMMY",
	"E_NOISE_DETECTION_THRESHOLD_1",
	"E_NOISE_DETECTION_THRESHOLD_2",
	"E_NOISE_DETECTION_THRESHOLD_3",
	"E_NOISE_DETECTION_THRESHOLD_4",
	"E_NOISE_DETECTION_THRESHOLD_5",
	"E_NOISE_DETECTION_THRESHOLD_6",
	"E_NOISE_DETECTION_THRESHOLD_7",
	"E_NOISE_DETECTION_THRESHOLD_8",
	"E_NOISE_DETECTION_THRESHOLD_9",
	"E_NOISE_DETECTION_THRESHOLD_10"
};


static const char * ENetworkTypeNames[] =
{
	"E_NETWORK_TYPE_DUMMY",
	"E_NETWORK_TYPE_IP",
	"E_NETWORK_TYPE_ISDN",
	"E_NETWORK_TYPE_PSTN_E1",
	"E_NETWORK_TYPE_PSTN_T1",
	"E_NETWORK_TYPE_LAST"
};


static const char * EMsftClientTypeNames[] =
{
	"MSFT_CLIENT_DUMMY",
	"MSFT_CLIENT_MOC",
	"MSFT_CLIENT_LYNC",
	"MSFT_CLIENT_AVMCU",
	"MSFT_CLIENT_LYNC2013",
	"MSFT_CLIENT_AVMCU2013",
	"MSFT_CLIENT_NONE_MSFT",
	"MSFT_CLIENT_LAST"
};


static const char * ECallDirectionNames[] =
{
	"E_CALL_DIRECTION_DUMMY",
	"E_CALL_DIRECTION_DIAL_IN",
	"E_CALL_DIRECTION_DIAL_OUT"
};


static const char * EAudioToneNames[] =
{
	"E_AUDIO_TONE_DUMMY",
	"E_AUDIO_TONE_SILENCE",
	"E_AUDIO_TONE_DTMF_0",
	"E_AUDIO_TONE_DTMF_1",
	"E_AUDIO_TONE_DTMF_2",
	"E_AUDIO_TONE_DTMF_3",
	"E_AUDIO_TONE_DTMF_4",
	"E_AUDIO_TONE_DTMF_5",
	"E_AUDIO_TONE_DTMF_6",
	"E_AUDIO_TONE_DTMF_7",
	"E_AUDIO_TONE_DTMF_8",
	"E_AUDIO_TONE_DTMF_9",
	"E_AUDIO_TONE_DTMF_STAR",
	"E_AUDIO_TONE_DTMF_PAUND",
	"E_AUDIO_TONE_DTMF_A",
	"E_AUDIO_TONE_DTMF_B",
	"E_AUDIO_TONE_DTMF_C",
	"E_AUDIO_TONE_DTMF_D",
	"E_AUDIO_TONE_OLD_100_HZ",
	"E_AUDIO_TONE_OLD_200_HZ",
	"E_AUDIO_TONE_OLD_300_HZ",
	"E_AUDIO_TONE_OLD_400_HZ",
	"E_AUDIO_TONE_OCTAVE_A3",
	"E_AUDIO_TONE_OCTAVE_B3",
	"E_AUDIO_TONE_OCTAVE_C4",
	"E_AUDIO_TONE_OCTAVE_D4",
	"E_AUDIO_TONE_OCTAVE_E4",
	"E_AUDIO_TONE_OCTAVE_F4",
	"E_AUDIO_TONE_OCTAVE_G4",
	"E_AUDIO_TONE_OCTAVE_A4",
	"E_AUDIO_TONE_OCTAVE_B4",
	"E_AUDIO_TONE_OCTAVE_C5",
	"E_AUDIO_TONE_OCTAVE_D5",
	"E_AUDIO_TONE_OCTAVE_E5",
	"E_AUDIO_TONE_OCTAVE_F5",
	"E_AUDIO_TONE_OCTAVE_G5",
	"E_AUDIO_TONE_DIAL_TONE",
	"E_AUDIO_TONE_BUSY",
	"E_AUDIO_TONE_FAST_BUSY",
	"E_AUDIO_TONE_RING_BACK",
	"E_AUDIO_TONE_CALL_WAITING",
	"E_AUDIO_TONE_DING",
	"E_AUDIO_TONE_DONG",
	"E_AUDIO_TONE_DING_DONG",
	"E_AUDIO_TONE_NEW_DING_PART1",
	"E_AUDIO_TONE_NEW_DING_PART2",
	"E_AUDIO_TONE_NEW_DONG_PART1",
	"E_AUDIO_TONE_NEW_DONG_PART2",
	"E_AUDIO_TONE_TEST_4",
	"E_AUDIO_TONE_LAST"
};

static const char * EGetMixMode[] =
{
	"E_MIX_MODE_GET_DUMMY",
	"E_MIX_MODE_GET_OTHERS",
	"E_MIX_MODE_GET_MYSELF",
	"E_MIX_MODE_GET_NOTHING",
	"E_MIX_MODE_GET_ALL",
	"E_MIX_MODE_GET_LAST"

};

#endif /*AUDIOAPIDEFINITIONSSTRINGS_H_*/
