/*
*****************************************************************************
*
* Copyright (C) 2005 POLYCOM NETWORKS Ltd.
* This file contains confidential information proprietary to POLYCOM NETWORKSO
*  Ltd. The use or disclosure of any information contained
* in this file without the written consent of an officer of POLYCOM NETWORKS
* Ltd is expressly forbidden.
*
*****************************************************************************

*****************************************************************************

 Module Name: LinuxSystemCallsApi.h

 General Description:  Module "" contains:

      1. 

 Generated By:	Yigal Mizrahi       Date: 26.4.2005

*****************************************************************************/
#ifndef _MCMSCOM_H_
#define _MCMSCOM_H_


/***** Include Files *****/
#include  <stdio.h>
#include  <string.h>
#include  <sys/types.h>
#include  <arpa/inet.h>
#include  <sys/socket.h>
#include  <netinet/in.h>
#include  <string.h>
#include  <pthread.h> 
#include  <unistd.h>
#include  <sched.h>

#include "SocketApiTypes.h" 
#include "SocketApiWrap.h"
#include "LinuxSystemCallsApi.h"
#include "McmsApi.h"

#define	MAX_MSG_EMA_COUNT	32
#define	MAX_MSG_EMA_SIZE	40000

typedef struct	t_EmaMsg
{
	char Message[MAX_MSG_EMA_SIZE];
	int messageSize;
	e_TcpConn eID;
}EmaMsg;


#endif //_MCMSCOM_H_
