#ifndef GENERATED_STATUS_H
#define GENERATED_STATUS_H

enum GeneratedStatus
{
    STATUS_SUCCESS = 0
    , STATUS_INVALID_UNKNOWN
    , STATUS_INVALID_INPUT_FILE
    , STATUS_FAILED_TO_LOAD_FILE
    , STATUS_FAILED_TO_OPEN_FILE
    , STATUS_INVALID_VIDEO_ALGO
    , STATUS_INVALID_VIDEO_PROFILE
    , STATUS_INVALID_TARGET_RESOLUTION
    , STATUS_INVALID_TARGET_BIT_RATE
    , STATUS_INVALID_TARGET_FRAME_RATE
    , STATUS_BAD_ALLOC
    , STATUS_INVALID_RESOLUTION_OF_SOURCE_IMAGE
};

#endif

